microsoft/onefuzz

src/cli/mypy.ini
src/cli/onefuzz/cli.py
src/cli/onefuzz/templates/afl.py
src/cli/requirements.txt

This PR enables adding documentation to CLI sub-command arguments via docstring_parser.
1. This includes adding docstring_parser as a prereq to the CLI.
2. Adds  support for parsing the docstrings of functions, and optionally passing the help strings as argument documentation if the documentation doesn't already exist.
Run `onefuzz template afl basic --help |grep -i afl`
Previously, the argument 'fuzzer_setup_container' wasn't documented beyond "CONTAINER".  Now, afl_container says "Specify the AFL container to use in the job"

Enable documentation of CLI sub-command arguments

---

docs/tasks.md
src/agent/onefuzz-supervisor/src/setup.rs

Adds an environment variable that exposes the task specific setup container as it exists on the fuzzing node
This sets `ONEFUZZ_TASK_SETUP_PATH` to the path for the `setup` container in the work set.
1. Execute a task with the following setup.sh: 
``` bash
set -ex
[ -f $ONEFUZZ_TASK_SETUP_PATH/setup.sh ]
```

set ONEFUZZ_TARGET_SETUP_PATH prior to executing task setup

---

src/api-service/__app__/daily_events/__init__.py
src/api-service/__app__/scaleset_events/__init__.py
src/api-service/__app__/scheduled_events/__init__.py

Finishes the pre-1.0 scaleset state refactor
1. Only executes `scaleset.update_configs` once every 24 hours, instead of once every 90 seconds.
2. Removes the ORM state-based event queuing that was replaced by `scaleset_events`
1. Create a new pool
2. Create a scaleset as part of the new pool
3. Assign a task to the new pool, verify it gets executed

finish scaleset state refactor

---

src/agent/onefuzz-supervisor/src/main.rs

Flush telemetry when supervisor agent exits due to an error.

Flush telemetry on supervisor agent error

---

src/agent/onefuzz-supervisor/src/coordinator.rs
src/agent/onefuzz-supervisor/src/scheduler.rs
src/agent/onefuzz/src/input_tester.rs
src/pytypes/onefuzztypes/models.py

- Fix command polling
- Claim commands after receipt
- Add a `stop` node command, to transition the supervisor agent to `done`
- Update (unused) command schemas to use new `EnumModel` base

Add `stop` node command

---

src/agent/onefuzz-supervisor/src/agent/tests.rs
src/agent/onefuzz-supervisor/src/auth.rs
src/agent/onefuzz-supervisor/src/config.rs
src/agent/onefuzz-supervisor/src/coordinator.rs
src/agent/onefuzz-supervisor/src/debug.rs
src/agent/onefuzz-supervisor/src/setup.rs
src/agent/onefuzz-supervisor/src/work.rs
src/agent/onefuzz-supervisor/src/worker.rs
src/agent/onefuzz-supervisor/src/worker/tests.rs
src/agent/onefuzz/src/blob/url.rs

- Provide full sets of `expose[..]` methods for `Secret`
- Redact serialized work unit config in logging
- Use `BlobContainerUrl` for work set setup URL

Redact work set fields

---

src/cli/examples/integration-test.py
src/cli/onefuzz/templates/afl.py
src/cli/onefuzz/templates/libfuzzer.py
src/cli/onefuzz/templates/radamsa.py

Migrates the majority of internal CICD tooling for integration testing into something consumable outside of Azure Devops.
* Each of the job templates now returns the Job (in the case of --dryrun, returns None)
* Uses the onefuzz-samples released artifacts of basic fuzzing binaries for testing.
The process followed:
1. Creates pools & scalesets needed (optionally uses existing pools if the user specifies their pools on the cmdlien)
2. Launches the templates specifying the above pools
3. Monitors each of the launched jobs until either the tasks fail or a report is created in the job specific container
4. Launches repro VMs for all of the successful tasks using one of the reports report
5. Monitors each of the repro VMs until either it fails or verifies the `rip` register works as expected. …

add end-to-end integration testing of fuzzing pipelines

---

.github/workflows/ci.yml
src/api-service/__app__/agent_can_schedule/__init__.py
src/api-service/requirements-dev.txt
src/ci/onefuzztypes.sh
src/cli/onefuzz/status/cache.py
src/cli/requirements-lint.txt
src/pytypes/onefuzztypes/models.py
src/pytypes/requirements-lint.txt

Re-adds [black](https://pypi.org/project/black/) to lint stages

re-add black to lint stages

---

.github/workflows/ci.yml
src/agent/onefuzz-agent/build.rs
src/agent/onefuzz-supervisor/build.rs
src/api-service/dev-deploy.sh
src/ci/get-version.sh
src/ci/unset-versions.sh
src/proxy-manager/build.rs

Unless Onefuzz is built in Github from a 'refs/tags', append the SHA and potentially .localchanges to the version string.
This provides an easy marker for identifying if the system has local changes included or not.
* Updates the each of the `build.rs` to to check GITHUB_REF and `git diff --quiet` to identify local changes
* Adds a util to reset setting versions (reset-versions.sh)
* Adds a util to get the version string without setting it (get-version.sh)
* Updates the service API deploy-dev.sh to package onefuzztypes & the api with the stamped in build strings
Manual inspection of built artifacts.  Locally built should be:
* 1.0.0-HASH or 1.0.0-HASH.localchanges in the case of modifying code locally without checking it in.
* CI builds should be 1.0.0-HASH
* Tag builds should be 1.0.0

set more detailed version information during builds

---

.github/workflows/ci.yml

Locally adding `--clean` to the command helps in making a exe w/o caching.
Locally if helps to attain the clean exe.

Using a clean flag

---

src/api-service/__app__/agent_commands/__init__.py
src/api-service/__app__/onefuzzlib/pools.py
src/api-service/dev-deploy.sh

Fixes `NodeMessage.delete_messages` incorrectly using `batch`.
Updates the call to batch to use it like a context manager, per [TableService docs](https://docs.microsoft.com/en-us/python/api/azure-cosmosdb-table/azure.cosmosdb.table.tableservice.TableService?view=azure-python#batch-table-name--timeout-none-)
In addition, the ORM layer auto-maps contextual types, like UUIDs to strs for primary & row keys.  Until we add 'batch' to ORM.py, we should just iterate over the items directly.
In the post 1.0.0 builds, nodes should no longer generate the following exception as they connect in:
`Exception: AttributeError: '_GeneratorContextManager' object has no attribute 'delete_entity'`

Remove use of `batch` in NodeMessages

---

src/api-service/__app__/onefuzzlib/azure/creds.py
src/api-service/__app__/onefuzzlib/azure/monkeypatch.py

Reduces the log levels to `WARN` for multiple third-party libraries early in processing.
There doesn't appear to be a supported mechanism to reset logging levels on a per logger method for Azure Functions.  As such, this makes sets the log level for the most verbose of the 3rd party libraries we use.
Hopefully, the python Azure Functions runtime will provide a better mechanism to reduce these log levels in the future.
https://github.com/Azure/azure-functions-python-worker/issues/743
Install, note we don't see all of the INFO logging from APIs like msrest in app insights.

Set log levels in Azure Functions by hand for 3rd party libraries

---

src/api-service/__app__/onefuzzlib/tasks/main.py
src/cli/examples/integration-test.py
src/cli/onefuzz/api.py

Fixes `DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead`

Always use logging.warning in python

---

src/api-service/__app__/onefuzzlib/notifications/ado.py
src/pytypes/onefuzztypes/enums.py

When notifications related to a report fail, the task that generated the report should be marked as failed
This traps on the python Exceptions related to configuration errors in ADO notifications and marks the task that generated the report as failed.
Use an invalid ADO notification config (such as invalid username for assign to), generate a report (such as via `onefuzz debug notification job`) and observe that the crash reporting job is marked as failed.

mark task as failued if ADO notification fails

---

src/cli/onefuzz/templates/__init__.py

wait_for_running was broken during the re-architecture.  This fixes the behavior.

fix --wait_for_running in the templates

---

src/api-service/__app__/agent_events/__init__.py
src/api-service/__app__/onefuzzlib/notifications/ado.py
src/api-service/__app__/onefuzzlib/pools.py
src/api-service/__app__/onefuzzlib/tasks/main.py

There is no ability to stopping tasks cleanly at the moment.  VMs are reimaged and queues are deleted.
This prevents marking tasks as having failed that were otherwise fine prior to being shut down.

only record failures generated prior to stopping

---

src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
src/agent/onefuzz-agent/src/tasks/merge/generic.rs
src/agent/onefuzz/src/expand.rs
src/agent/onefuzz/src/input_tester.rs

input marker was set as a path instead of a string value

fixing input marker expansion in the supervisor task

---

src/cli/onefuzz/debug.py

Enables the following RDP & SSH debug workflows:
* Remote into the first libfuzzer_fuzz node for a given job:
`onefuzz debug job task ssh $JOB_ID libfuzzer_fuzz`
* Remote into the first node for a given task:
`onefuzz debug task $TASK_ID`
* Remote into a specific node for a given task:
`onefuzz debug task $TASK_ID --node_id $NODE_ID`
* List nodes working on a specific task:
`onefuzz debug task list_ndoes $TASK_ID`
Based on data exposed in #54

add onefuzz debug commands to easily get to nodes running on scalesets

---

src/cli/onefuzz/template.py

In 'onefuzz template stop', the project was ignored, causing jobs that had the same 'name', and build if provided, to stop.

fix bug stopping templates

---

src/api-service/__app__/agent_registration/__init__.py
src/api-service/__app__/onefuzzlib/azure/creds.py
src/api-service/__app__/onefuzzlib/extension.py
src/api-service/__app__/onefuzzlib/notifications/common.py
src/api-service/__app__/onefuzzlib/tasks/config.py
src/api-service/__app__/pool/__init__.py

Updates crash report notifications `repro_cmd` to go from:
`onefuzz repro create_and_connect container file`
to:
`onefuzz --endpoint https://INSTANCE.azurewebsites.net repro create_and_connect container file`
This is extremely valuable to help users that support multiple OneFuzz instances.
In addition to the aforementioned change to notifications, updates everywhere that was building the URL to the instance to use the new helper method
1. Create a crash reporting task
2. Create a notification that uses `{{ repro_cmd }}`
3. Create a crash report for said task.
4. Note the repro_cmd is updated to include --endpoint for the instance.

add '--endpoint' to 'repro_cmd' for integrations

---

CONTRIBUTING.md
docs/specs/spec-template.md

Add basic contributors guide, lifted heavily from [microsoft/terminal](https://github.com/microsoft/terminal) and [microsoft/vscode](https://github.com/microsoft/vscode)

add basic contributors guide

---

src/deployment/data_migration.py
src/deployment/deploy.py
src/deployment/register_pool_application.py

This checks if the azcopy we provide are compatible with the host used for deployment and otherwise makes use of the user-installed azcopy.
This enables deployment on non-x86_64 Linux/Windows platforms (such as OSX)
1. The deployment scripts still prefer the built-in azcopy, but will use the system provided azcopy if our built-in versions are incompatible.
2. Addresses lint issues in the deploy code
3. Adds missing copyright to code written by MSFT
Run deployment from a linux/x86_64 platform and an OSX platform.  Both should succeed.

use installed azcopy if the packaged azcopy versions are not compatable

---

src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
src/agent/onefuzz/src/telemetry.rs
src/runtime-tools/win64/onefuzz.ps1

As is, we send all levels of logging from the agent to app-insights, which is too verbose.  This aligns app-insights with log levels. 
On linux, this was previously set to 'info' and not set on windows.  This PR includes setting RUST_LOG to 'info' on windows.

Filter agent app-insights logs based on log::max_level

---

src/api-service/__app__/onefuzzlib/task_event.py

This fixes a build failure from a typing issue where we were sorting an Optional[Datetime], which is not directly sortable.
This was discovered during an update to mypy, which included a new typeshed that supports checks if list.sort arguments are sortable.

Fixes typing error identified by a new mypy release

---

src/deployment/data_migration.py

In pre-1.0.0, notifications mapped notification_id to RowKey and Container to PartitionKey.  In the 1.0.0 release, these got swapped causing pre-1.0.0 upgraded systems to fail.
A migration for pre-1.0.0 keys in the notifications table

add migration to fix notifications from pre-1.0.0 upgrade

---

src/api-service/__app__/onefuzzlib/pools.py

When creating a large scaleset, individual VMs will often be "ready" long before the scaleset as a whole is done. 
Supervisors trying to register before the full scaleset is up will be rejected as the managed identity is only saved once the scaleset is fully setup.
This saves the identity as soon as it's available when polling the scaleset state

Save the managed identity as soon as it's available

---

src/cli/examples/integration-test.py

Allows specifying the endpoint to run the e2e integration tests
Adds --endpoint to integration-test.py
Run the e2e deployment scripts

allow specifying endpoint for test script

---

src/agent/debugger/src/debugger.rs
src/agent/debugger/src/lib.rs
src/agent/debugger/src/target.rs

This change just refactors the Win32 debugger code a bit - no functional changes.
Tested locally to ensure crashes are still reported and breakpoints/single work correctly.

Move Win32 debugger Target to own module

---

src/agent/onefuzz-supervisor/src/config.rs
src/agent/onefuzz-supervisor/src/main.rs

This saves DynamicConfig to disk such that it can be reloaded upon reboot.
This moves the agent to a mode such that 'registration' only happens upon first connection.

save the DynamicConfig for reload upon reboot

---

src/agent/coverage/src/lib.rs
src/agent/debugger/src/debugger.rs
src/agent/input-tester/src/crash_detector.rs

- Enable tracking module paths when collecting coverage
- Expose `Target`, more `dbghelp` functions from `Debugger`

Expand coverage and debugger APIs

---

src/cli/examples/integration-test.py

This updates the integration tests from:
`waiting repro: TEST1:state1,TEST2:state1,TEST3:state2`
to:
`waiting repro: state1:TEST1,TEST2 state2:TEST3`

simplify integration test output for repro tests

---

src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
src/agent/onefuzz-agent/src/tasks/utils.rs
src/agent/onefuzz/src/az_copy.rs

Makes upload failures more verbose and fail fast.
1. Standardizes on a single SyncDir based director monitor.
2. Update said uploader to use `while ... monitor.next()` rather than `monitor.for_each` such that failures can be reported
3. Update azcopy wrapper to include stdout & stderr on failure, as some (but not all) errors in azcopy are printed to stdout.
Run standard integration tests

fail louder when uploads fail

---

src/api-service/__app__/pool/__init__.py
src/api-service/__app__/scaleset/__init__.py
src/cli/onefuzz/api.py

As is, we return the full pool or scaleset model, which isn't needed on delete

on shutdown of scalesets & pools, only return boolresponse

---

src/api-service/__app__/agent_events/__init__.py

Limits stdout/stderr logged as part of the Task.error upon task failure to the last 4k of each.

limit size of error log saved as a Task Error

---

src/deployment/deploy.py

If subprocess.check_output() raises an exception, the handler for TemporaryDirectory() attempts to delete tmpdirname. This causes a permissions error since the terminal's cwd has been changed to tmpdirname. I'm not sure if this happens on Linux but on Windows, another exception is throw along with the error returned by check_output().
This fix removes the need to use os.chdir(). 
I tested this fix using Windows but not Linux.

handle nested exceptions during cleanup on function deploy failures

---

src/agent/onefuzz-supervisor/src/agent.rs
src/agent/onefuzz-supervisor/src/scheduler.rs

This PR updates the supervisor to only emit events when there is a change in state.
1. Standard integration tests will verify it doesn't break the state machine
2. Check app-insights to verify we don't see sequential "Free" or "Busy" events from a given node

only emit events on a change of state

---

src/cli/onefuzz/api.py
src/cli/onefuzz/cli.py

The expanded `reset` command now includes help documentation for each of the arguments.  
With this PR, the help looks like this:
```
$ onefuzz reset --help
usage: onefuzz reset [-h] [-v] [--format {json,raw}] [--query QUERY] [--containers] [--everything] [--jobs] [--notifications] [--pools]
[--repros] [--scalesets] [--tasks] [--yes]
optional arguments:
-h, --help           show this help message and exit
-v, --verbose        increase output verbosity
--format {json,raw}  output format
--query QUERY        JMESPath query string. See http://jmespath.org/ for more information and examples.
--containers         Delete all the containers. (Default: False. Sets value to True)
--everything         Delete all containers, pools and managed scalesets. (Default: False. Sets value to True)
--jobs …
```

address help issues in the expanded reset command

---

src/api-service/__app__/onefuzzlib/azure/vm.py

Fixes an exception due to mismatched formatting arguments

fix format strings in logging for onefuzzlib.azure.vm.get_vm

---

src/api-service/__app__/onefuzzlib/azure/creds.py

Right now, we poll MSI & fetch storage account keys on a high frequency, eventually hitting rate limiting from MSI or Storage account mgmt layer.
This change caches the storage account key & MSI tokens in memory forever, which will necessitate restarting the app upon storage account key rotation.

cache tokens in memory forever

---

src/api-service/__app__/containers/__init__.py
src/api-service/__app__/download/__init__.py
src/api-service/__app__/notifications/__init__.py
src/api-service/__app__/onefuzzlib/azure/containers.py
src/api-service/__app__/onefuzzlib/tasks/config.py

Reduce performance issues relating to `container in list_containers()` as a method of checking of a container exists.
This becomes noticeable once extremely large numbers of containers are created.

reduce how often list_containers is called

---

src/cli/onefuzz/api.py
src/pytypes/onefuzztypes/enums.py

To reduce overload for scaling and for testing I need to delete particular set of container. Adding `container reset` cli argument.
Also, 
- changing `reset --containers` to call `containers reset`
- sorting types in `ContainerType`
Manually tested.

Add Onefuzz.container.reset to the SDK

---

src/agent/onefuzz-agent/src/tasks/config.rs
src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
src/agent/onefuzz/src/telemetry.rs

Adds the crash report & tool name telemetry already approved by CELA and documented in our telemetry guidance here:
https://github.com/microsoft/onefuzz/blob/main/docs/telemetry.md#data-recorded-by-agents

add missing telemetry relating to reports & tools

---

src/ci/build_cli.ps1

I am observed while using `build_cli` if onefuzztypes is updated, installing of `onefuzztypes` is ignored. Therefore uninstalling to avoid spending related to it. 
Observed in PR #198 .
manually tested.

uninstall onefuzztypes and reinstall

---

src/api-service/__app__/onefuzzlib/agent_authorization.py
src/api-service/__app__/onefuzzlib/autoscale.py
src/api-service/__app__/onefuzzlib/azure/queue.py
src/api-service/__app__/onefuzzlib/azure/subnet.py
src/api-service/__app__/onefuzzlib/azure/vm.py
src/api-service/__app__/onefuzzlib/extension.py
src/api-service/__app__/onefuzzlib/notifications/ado.py
src/api-service/__app__/onefuzzlib/pools.py
src/api-service/__app__/onefuzzlib/repro.py
src/api-service/__app__/onefuzzlib/request.py
src/api-service/__app__/onefuzzlib/tasks/config.py
src/cli/onefuzz/debug.py
src/cli/onefuzz/status/top.py
src/cli/onefuzz/template.py

1. overwriting module imports (`func` and `os`)
2. not using lazy-formatting in logging
3. attempting to use lazy-formatting in exceptions
4. invalid format string params (fixes #205 )
5. returning values on funcs declared to return None

address multiple issues found by pylint

---

src/agent/script/win64/libfuzzer-coverage/DumpCounters.js

This PR moves from ignoring AVs to handling them as second chance exceptions.  This allows letting the libfuzzer runtime based exceptions to continue, but still stopping during AVs not handled by libfuzzer.
See [sx, sxd, sxe, sxi, sxn, sxr, sx- (Set Exceptions)](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/sx--sxd--sxe--sxi--sxn--sxr--sx---set-exceptions-#remarks) for more on exception handling.

Use second-chance break on av on libfuzzer coverage extraction

---

src/cli/MANIFEST.in

Adding the examples is needed to work towards making the CICD resources entirely self-contained in the build artifacts

include examples in SDK

---

src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs

If a coverage task is started with a large number of inputs but no new coverage ever hits the task's input queue, the total coverage is never reported.
Run a coverage task with a large number of inputs without a fuzzing task.  Notice that the total coverage is logged to app-insights.

report coverage total after batch processing

---

src/agent/onefuzz-agent/src/tasks/coverage/recorder.rs
src/agent/script/win64/libfuzzer-coverage/DumpCounters.js

Disables sympath used in cdb unless it's explicitly set via target_env.  This significantly improves the runtime performance of sancov extraction.
Ran with `onefuzz-agent.exe debug libfuzzer-coverage`, once with `--target_env _NT_SYMBOL_PATH=c:\symbols` and once without.  Note that without is significantly faster.
* Issue #220 tracks updating `libfuzzer_coverage` to support variable expansion appropriate.
* Issue #221 tracks updating variable expansion to support `{setup_dir}` such that the setup dir can be explicitly set.

disable sympath in libfuzzer_coverage extraction unless it's set via target_env

---

src/api-service/__app__/onefuzzlib/proxy.py
src/api-service/__app__/onefuzzlib/tasks/config.py
src/api-service/__app__/pool/__init__.py
src/api-service/__app__/queue_file_changes/__init__.py

This updates the rest of the python code not yet already touched to use the get_func_storage and get_fuzz_storage helper methods.
Standard integration testing

Always use the get_*_account helper methods

---

src/agent/onefuzz-agent/src/debug/libfuzzer_fuzz.rs
src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
src/agent/onefuzz/src/syncdir.rs
src/api-service/__app__/onefuzzlib/tasks/config.py
src/api-service/__app__/onefuzzlib/tasks/defs.py
src/cli/onefuzz/api.py
src/cli/onefuzz/templates/afl.py
src/cli/onefuzz/templates/libfuzzer.py
src/cli/onefuzz/templates/ossfuzz.py
src/cli/onefuzz/templates/radamsa.py
src/pytypes/onefuzztypes/enums.py
src/pytypes/onefuzztypes/models.py

This PR allows enables a --ensemble_sync_delay, which sets the duration for the ensemble sync duration for fuzzing tasks.  Note, this additionally provides the ability to disable ensemble syncing at large by setting the value to 0.
1. Launch a fuzzing task with `--ensemble_sync_delay` of 5.  SSH into the node running the fuzzing task.  Note azcopy runs every 30 seconds.
2. Launch a fuzzing task with `--ensemble_sync_delay` of 0.  SSH into the node running the fuzzing task.  Note azcopy pull from the inputs never runs.

enable setting ensemble sync duration timer

---

contrib/deploy-onefuzz-via-azure-devops/deploy-onefuzz.yml
contrib/deploy-onefuzz-via-azure-devops/get_latest_version.py

(1)
Updated 'contrib' submodule to allow user to optionally specify OneFuzz version to deploy. 
(2)
Updated 'contrib' submodule to allow user to optionally specify deploy.py arguments, e.g. --export_appinsights.
(3)
Fixed a minor typo in line 23 of deploy-onefuzz.yml for 'gorup' name. 
Updated deploy-onefuzz-via-azure-devops to allow user to specify version
I verified the Pipeline works like it did before I made any changes plus if you specify 'VERSION' then it'll deploy that version of OneFuzz. As well as if DEPLOY_ARGS are provided or not.

Updated deploy-onefuzz-via-azure-devops

---

src/deployment/azuredeploy.json

While scaling to 1000 nodes, azure function starts to hang and needs more instances to be in working condition.
When creating multiple jobs or creating a scaleset with a big size, there is a sudden surge in number of requests. Therefore, waiting for high cpu usage and then auto scaling does do much good. I am scaling rapidly in multiples of 5 and then scaling down slowly to make sure we have required number of instance to work with.
Sorting out the variable names as well because it was hard to find what I was looking for.
Ref. for work is an [azure sample repository](https://github.com/Azure/azure-quickstart-templates/blob/master/monitor-autoscale-webappserviceplan-simplemetricbased/azuredeploy.json) and azure portal.
Tested manually on an existing subscription w/o the feature avail, …

Autoscaling Azure Function

---

src/agent/Cargo.lock
src/ci/agent.sh
src/ci/proxy.sh
src/proxy-manager/Cargo.lock

Address a breaking change introduced in cargo-audit 0.13.1.
For more info, see https://github.com/RustSec/cargo-audit/issues/280

fix breaking change in cargo-audit

---

src/deployment/deploy.py
src/deployment/registration.py

Provide the ability to create a new cli application registration

---

src/agent/onefuzz/src/az_copy.rs

We continue to see issues with azcopy sync failing.  This adds stdout logging to azcopy such that we can debug the issue.

record stdout from azcopy

---

src/api-service/dev-deploy.ps1

Adding version as a param to dev-deploy script
I have to modify `__version__.py` many times and sometimes goes into commit. Adding version in script will give more flexibility for dev working on windows and function app.
Also, I have to delete bunch of `onefuzztypes-*-py3-none-any.whl`. Therefore, using regex now to delete them.
manually tested.

Adding version as a param to dev-deploy script

---

docs/telemetry.md
src/agent/onefuzz-agent/src/debug/generic_crash_report.rs
src/agent/onefuzz-agent/src/debug/libfuzzer_coverage.rs
src/agent/onefuzz-agent/src/debug/libfuzzer_crash_report.rs
src/agent/onefuzz-agent/src/debug/libfuzzer_fuzz.rs
src/agent/onefuzz-agent/src/tasks/config.rs
src/agent/onefuzz-supervisor/src/config.rs
src/agent/onefuzz-supervisor/src/main.rs
src/agent/onefuzz/src/telemetry.rs
src/api-service/__app__/info/__init__.py
src/api-service/__app__/onefuzzlib/azure/containers.py
src/api-service/__app__/onefuzzlib/azure/creds.py
src/api-service/__app__/onefuzzlib/extension.py
src/api-service/__app__/onefuzzlib/reports.py
src/api-service/__app__/onefuzzlib/tasks/config.py
src/api-service/__app__/pool/__init__.py
src/deployment/azuredeploy.json
src/deployment/deploy.py
src/pytypes/onefuzztypes/models.py
src/pytypes/onefuzztypes/responses.py

Adds a randomly generated UUID that is unique to each install that is included in telemetry.
This adds an `instance_id` that is generated at install time, and add it to the supervisor and agent configs to be used if telemetry is enabled.
NOTE: Including a per-install randomly generated UUID as an instance ID was approved during the initial internal privacy review.
Standard integration tests

add instance_id generated at install time

---

src/deployment/deploy.py

Fixes the following exception introduced in #245
```
INFO:deploy:checking if RBAC already exists
INFO:deploy:deploying arm template: azuredeploy.json
INFO:deploy:assigning the user managed identity role
INFO:deploy:creating eventgrid destination queue
INFO:deploy:creating eventgrid subscription
INFO:deploy:uploading tools from tools
INFO:deploy:setting instance_id log export
Traceback (most recent call last):
File "deploy.py", line 842, in <module>
main()
File "deploy.py", line 836, in main
state[1](client)
File "deploy.py", line 483, in add_instance_id
instance_id = uuid.UUID(blob_client.download_blob().readall())
File "/usr/lib/python3.8/uuid.py", line 166, in __init__
hex = hex.replace('urn:', '').replace('uuid:', '')
TypeError: a bytes-like object is required, not 'str'
```

fix reading instance_id on follow-on deploy

---

src/api-service/__app__/onefuzzlib/azure/queue.py

Sets the default TTL for queue message to infinite (rather than 7 days). 
Currently, storage queues are used for managing scheduled tasks.  If a task is not scheduled for 7 days, the entry for the task expires from the queue leaving the task as Scheduled forever.
This PR also aligns the API to between send_message and queue_object.
Standard integration tests

default TTL for queued messages to infinite

---

src/cli/onefuzz/status/cache.py

The `status top` message window displays a truncated UUID for types of UUIDs.   
This PR adds machine_id to that UUIDs that get truncated.

Use a shortened machine_id in status top

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/coverage/Cargo.toml
src/agent/coverage/examples/block_coverage.rs
src/agent/coverage/src/block.rs
src/agent/coverage/src/block/linux.rs
src/agent/coverage/src/block/windows.rs
src/agent/coverage/src/lib.rs
src/agent/debugger/src/debugger.rs

Update the internal `coverage` crate to enable recording approximate block coverage for uninstrumented targets on Windows and Linux. This will let us add a new `generic_coverage` task for targets, with enough context for flexible output formats. We currently support multi-threading on both platforms, but not multi-processing.
We require some amount of symbol support: a local PDB for Windows targets, and an unstripped ELF symbol table for Linux targets.
This PR introduces a redundant type for recording block coverage. Future work will merge this and the existing internal block coverage format.

Add uninstrumented block coverage recording

---

src/api-service/__app__/onefuzzlib/azure/vmss.py

This fixes a log message we currently generate.
From: 
`creating VM countname: 73d20a86-36e0-40bb-907b-f887f4df6ad9 vm_sku: Standard_D2s_v3 vm_count: 5` (...) 
To: 
`creating VM name: 73d20a86-36e0-40bb-907b-f887f4df6ad9 vm_sku: Standard_D2s_v3 vm_count: 5` (...)

fix create_vmss log message

---

src/cli/onefuzz/template.py
src/cli/onefuzz/templates/__init__.py

Once an instance has massively large numbers of jobs, `containers.list()` becomes unacceptably slow.  
This removes `container.list()` in two places.
1. Template helper.  As creating containers is effectively idempotent, it's more efficient to always create the container, rather than check if the container exists and create it otherwise.
2. Template deletion.  As `container.delete()` returns a `BoolResult` of "true if deleted, false if it didn't exist", we can still indicate if the deletion occurred, without the overhead of checking if the container exists prior to deletion.

reduce calls to containers.list()

---

src/api-service/__app__/agent_events/__init__.py

This PR updates the agent event logging to use a json representation, rather than repr, of the event.
By using pydantic's json renderer, we can specify exclude_none, which removes 'error=None' from showing up in the logs.

Render envelope.event as json

---

src/pytypes/onefuzztypes/enums.py

For `onefuzz containers reset`, we filter which containers to delete and only delete based on context.    This specifically allows us to not delete tools containers while removing all of the fuzzing metadata.
This PR adds unique_inputs as a containertype that gets reset, along with all of the other fuzzing metadata containers.

include deleting unique_inputs on containers.reset

---

src/api-service/__app__/agent_registration/__init__.py

As discussed in #241, we should not use 404 status code on agent registration failure.
This change will cause agent registration failure to use the default status code for `not_ok`, which is 400.

Don't use HTTP 404 on agent refresh error

---

src/agent/onefuzz-agent/src/tasks/heartbeat.rs
src/agent/onefuzz-supervisor/src/agent.rs
src/agent/onefuzz-supervisor/src/heartbeat.rs

sends the supervisor heartbeat in the main loop
removed the default machine alien heartbeat from the tasks

Make supervisor heartbeat only fire on main loop progress

---

src/deployment/azuredeploy.json

Though it needs some configuration and extra steps to access the data. Ideally it will be better to not allow public access at all.
Ref: https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal#about-anonymous-public-read-access
At configuration page of storage account
Before:
After:
tested on redeployment. Gave a test run with a fuzzer as well.

prevent users from enabling public access to containers

---

src/api-service/__app__/onefuzzlib/tasks/config.py
src/pytypes/onefuzztypes/models.py

`libfuzzer_fuzz` task uses `target_workers` configuration.
https://github.com/microsoft/onefuzz/blob/87085bc48a7eb24fad3d30d6b935b7ca7de14315/src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs#L64-L67
But, that was not included in the `TaskUnitConfig`, so agents never know the configured value.
Add `target_workers` member to `TaskUnitConfig`.
tested by deploying the fix to my server, and checked number of fuzzer processes in the vms and whether `config.json` is created well in the vms.

Add target_workers to TaskUnitConfig

---

docs/webhook_events.md
src/api-service/__app__/agent_can_schedule/__init__.py
src/api-service/__app__/agent_commands/__init__.py
src/api-service/__app__/agent_events/__init__.py
src/api-service/__app__/agent_registration/__init__.py
src/api-service/__app__/onefuzzlib/agent_authorization.py
src/api-service/__app__/onefuzzlib/tasks/main.py
src/api-service/__app__/onefuzzlib/user_credentials.py
src/api-service/__app__/onefuzzlib/webhooks.py
src/api-service/__app__/tasks/__init__.py
src/pytypes/extra/generate-docs.py
src/pytypes/onefuzztypes/models.py
src/pytypes/onefuzztypes/webhooks.py

This PR makes user information from JWT tokens available as part of a Task.
Included changes:
* Renamed `verify_token` to `call_if_agent`, since this function is specific to agent token verification
* Renames `is_authorized` to `is_agent`, since this function checks if the token is an agent
* Adds support for unmanaged nodes in `is_agent` (see #133 for information) 
* Saves the user information from the JWT token on task create as part of `TaskConfig`
Note, `TaskConfig` is what is provided to notification templates.  This enables Github issues and ADO work items to tie back to the user that created the task.
Note, while `upn` _usually_ means email for AAD user tokens.  If we were going to make use of the email address, we should perform a graph lookup based on the `oid`, but we're not.

Add User Info to created tasks

---

src/cli/onefuzz/api.py

When resetting webhooks was added to `onefuzz reset`, it should not have been setup to reset by default.

Don't reset webhooks by default

---

.github/workflows/ci.yml
src/api-service/__app__/onefuzzlib/azure/vm.py
src/api-service/__app__/onefuzzlib/tasks/main.py
src/ci/disable-py-cache.sh
src/ci/enable-py-cache.sh

The caching library used by OneFuzz does not preserve type signatures.  
This PR includes the following changes:
* Scripts to enable & disable the use of the `memoization` library
* Uses the disable script to enable type checking without the `cached` function wrappers.
* Fixes two issues exposed once the type signatures were exposed.
See https://github.com/lonelyenvoy/python-memoization/issues/16 for more information.

Address typing issues hidden by memoization.caching

---

src/cli/onefuzz/debug.py

Adds debug subcommands to the SDK/CLI that simplify querying Application Insights for libfuzzer telemetry.  
Querying for the latest execs_sec for a job, by job_id fragment.
```
$ onefuzz debug job libfuzzer_execs_sec 88 --limit 1
[
{
"execs_sec": "191035",
"machine_id": "b2dbe720-4fd8-4342-957a-6cb0979d2187",
"timestamp": "2020-11-18T00:08:53.98Z",
"worker_id": "0"
}
]
```
Querying for the latest coverage for a job, by job_id fragment.
```
$ onefuzz debug job libfuzzer_coverage 88 --limit 1
[
{
"covered": "10",
"features": "21",
"rate": "0.47619047619047616",
"timestamp": "2020-11-18T00:09:40.793Z"
}
]
```

Expose coverage/exec_sec for libfuzzer targets via CLI

---

src/runtime-tools/linux/setup.sh
src/runtime-tools/win64/setup.ps1

Support `instance-specific-setup/<OS>/setup` and `instance-specific-setup/setup` scripts.
Fixes #328

Support pre-release instance specific setup script paths

---

src/agent/debugger/src/target.rs

Trivial fix to address an issue with the `current_thread_id` only returning the initial thread id.

Small fix in set_current_thread in Windows debugger

---

src/cli/onefuzz/api.py

Updates the error upon prefix-expansion issues from:
```
ERROR:cli:command failed: name does not expand to a value: linux
```
to:
```
ERROR:cli:command failed: Unable to find pool name based on prefix: linux
```

clarify prefix-expansion errors

---

src/api-service/__app__/onefuzzlib/orm.py
src/api-service/__app__/onefuzzlib/pools.py

If a node is already scheduled to be reimaged/deleted, we should not bother checking if it's outdated.

ignore nodes already scheduled for re-imaging in outdated check

---

src/api-service/__app__/agent_events/__init__.py

This removes `error=None` from showing up in the logs.

render the event model as json

---

src/integration-tests/integration-test.py

Radamsa tasks with targets compiled with ASAN support shouldn't use the debugger.   This PR fixes the radamsa integration tests built with ASAN.

Use disable_check_debugger on asan integration tests

---

src/api-service/__app__/info/__init__.py
src/api-service/__app__/onefuzzlib/azure/creds.py
src/pytypes/onefuzztypes/responses.py

This provides the instance instrumentation key to Info.
This will enable logging to the instance app insights from the SDK.

add the instrumentation key to Info

---

src/agent/onefuzz/src/asan.rs

This differentiates parsing ASAN log parse failures from ASAN logs not existing, fixing the first part of #343.

Fail the task if parsing asan_log files fail

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

Update rust prereqs because `miow 0.2.1` and `miow 0.3.5` were yanked.

update rust prereqs

---

src/agent/onefuzz/data/asan-check-failure-missing-symbolizer.txt
src/agent/onefuzz/data/asan-check-failure.txt
src/agent/onefuzz/src/asan.rs

Handle parsing "CHECK failed" ASAN logs.  Fixes #343

handle asan check failures

---

src/api-service/__app__/job_templates_manage/__init__.py
src/api-service/__app__/job_templates_manage/function.json
src/api-service/__app__/onefuzzlib/job_templates/templates.py
src/cli/onefuzz/job_templates/manage.py
src/pytypes/onefuzztypes/job_templates.py
src/pytypes/onefuzztypes/validators.py

1. Merge 'create' and 'update' to a single 'save' operation.
2. Allow fetching a single template.
This enables the following workflow:
```
$ onefuzz job_templates manage get libfuzzer_linux > template.json
$ <... update template as desired ...>
$ onefuzz job_templates manage save libfuzzer_linux @./template.json
$
```

Simplify job template management workflow

---

src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
src/agent/onefuzz-agent/src/tasks/report/generic.rs
src/agent/onefuzz/data/libfuzzer-scariness-underflow.txt
src/agent/onefuzz/data/libfuzzer-scariness.txt
src/agent/onefuzz/src/asan.rs
src/pytypes/onefuzztypes/models.py

This adds support for ASAN's "scariness" score and description.
The scariness index is exposed by the user providing ASAN_OPTIONS=print_scariness=1 for their target_env during crash reporting.
https://github.com/llvm/llvm-project/blob/master/compiler-rt/lib/asan/asan_scariness_score.h

Add support for ASAN print_scariness

---

src/api-service/__app__/job_templates_manage/__init__.py

The `delete` endpoint did not actually delete job templates.

fix job_templates deletion

---

docs/declarative-templates.md
docs/managing-templates.md

This provides a walk-through example for using declarative templates.

Document managing declarative templates

---

src/ci/agent.sh

This PR temporarily allows the existing `memmap` dependency as identified in #363 and should be removed once an alternative has been updated.

Allow unmaintained memmap

---

docs/managing-templates.md

Add a job_template example that demonstrates customization of the arguments to the job. 
This example demonstrates setting the Area and Iteration paths for Azure Devops work items.

Demonstrate a more complex template management

---

src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs

Moves to using String::from_utf8_lossy to cleanly ignore non-utf8 output from libfuzzers.

handle non-utf8 from libfuzzer stderr

---

.github/workflows/ci.yml
src/ci/disable-py-cache.sh
src/ci/enable-py-cache.sh
src/cli/onefuzz/api.py

Removes `@cached` memoization from the CLI prior to running mypy, similar to #322 provides for the service code
This is needed as the latest version of memoization, v0.3.2, provides support for preserving type signatures, but does not handle memoization of class methods.  (See https://github.com/lonelyenvoy/python-memoization/issues/18)

disable py-cache prior to mypy on cli

---

src/agent/onefuzz-supervisor/src/main.rs
src/agent/onefuzz-supervisor/src/reboot.rs
src/agent/onefuzz-supervisor/src/setup.rs
src/agent/onefuzz-supervisor/src/work.rs
src/integration-tests/integration-test.py

Adds the following:
1. Serializes a workset to disk during setup.
2. Upon deserializing a RebootContext, delete the file from disk (We support rebooting once and only once)
3. Check if a workset exists with a RebootContext
1. If True, continuing processing
2. if False, mark the tasks & node as "Done" with appropriate errors via:
1. send WorkerEvent::Done events for each of the tasks in the work set
2. send StateUpdateEvent::Done for the node

Verify a workset only exists along with a reboot context

---

src/api-service/__app__/onefuzzlib/pools.py

In `Scaleset.cleanup_nodes`, nodes that are no longer part of the scaleset should get deleted.  Without filtering the list, the nodes could get re-saved to the Node table later on.

filter out deleted nodes as to prevent them from being saved later

---

src/cli/onefuzz/debug.py

Adds `onefuzz debug log tail <keyword>`, which enables performing the same component in `onefuzz debug log keyword <keyword>` in a loop.  
Optimizations:
* only returns the N records at a time (default 1000)
* each query only returns records that occur after the latest record received.
* If no results are returned, waits 10s before retrying
* Increases the wait time by 1.5x until the wait time is larger than 60s
Using `--filter` provides the ability to filter each record that comes back via jmespath.
Example uses:
Monitor any log messages (which ignores metrics) for a given job_id GUID
```
onefuzz debug logs tail bf4efdfd-685c-444a-81c5-d911477433ae --filter message
```
Log the job_id and task_id for each new unique report:
```
onefuzz debug logs tail new_unique_report --filter …
```

add 'onefuzz debug log tail'

---

src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
src/agent/onefuzz/src/process.rs

log stdout & stderr lines for supervisor & generator

---

src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs

This fixes an issue running a libfuzzer coverage task and don't have any initial seeds (or there are seeds found by the fuzzer by the time the task starts), it will fail.

Fixes race condition of a libfuzzer coverage without inputs

---

src/api-service/__app__/host.json

This is a work-around until the 'update outdated nodes' process is simplified.
In the large scale testing, I pushed an updated build to an instance with 7 scale-sets and 4.5k nodes.  This resulted in a few hundred thousand updates to Azure Tables.

increase function timeout to 15 minutes

---

src/api-service/__app__/node/__init__.py
src/api-service/__app__/node/function.json

Re-adds the POST method for the `node` endpoint, which got accidentally dropped.

Re-adds POST for node endpoint

---

src/agent/onefuzz-supervisor/src/config.rs
src/agent/onefuzz-supervisor/src/work.rs
src/agent/onefuzz/src/http.rs
src/api-service/__app__/agent_registration/__init__.py
src/api-service/__app__/onefuzzlib/azure/queue.py

The underlying impact is that nodes must re-register on a more frequent basis.
Nodes find out they are out-of-date is during registration and immediately prior to starting a new set of work.  Requiring nodes re-register on a shortened cycle provides more opportunities for nodes to get re-imaged.
Additionally, this addresses an issue handling the SAS URL expiry in a more clean fashion in the supervisor.

Shorten the expiry window for the work queue SAS URLs assigned at node registration

---

src/api-service/__app__/onefuzzlib/tasks/config.py
src/pytypes/onefuzztypes/models.py

Removes the agent task config entry back_channel_address which is unimplemented (and broken).
As is, we generated the following config entry:
`"back_channel_address": "https://https://INSTANCE-NAME.azurewebsites.net/api/back_channel"`

remove unused back_channel_address entry

---

.github/workflows/ci.yml

Bumps upload-artifact and download-artifact, both of which include retry capabilities which have been plaguing our builds.

Bump Github Actions revisions

---

src/agent/Cargo.lock
src/agent/coverage/Cargo.toml
src/agent/coverage/src/block/linux.rs
src/agent/onefuzz/Cargo.toml
src/agent/onefuzz/src/input_tester.rs
src/agent/onefuzz/src/triage.rs

Update `pete` to 0.4, which enables and requires us to use `std::process::Child` for spawning tracees.
Toward #370.

Update Linux tracer version

---

src/deployment/azuredeploy.json

A recent change to the service requires all `service` containers must be pre-created.

create proxy-configs container during install

---

src/integration-tests/integration-test.py

This only launches the repro test cases if you have the os-specific prerequisite debugger installed.

verify local debugger installs before launching repro

---

.github/workflows/ci.yml
src/pytypes/onefuzztypes/primitives.py

Previous releases of `mypy` did not handle subclassing builtins well.  Now that has been addressed in mypy, this removes the workaround.

remove workaround for an issue addressed in latest mypy

---

src/agent/onefuzz-agent/src/local/generic_crash_report.rs
src/agent/onefuzz-agent/src/local/libfuzzer_crash_report.rs
src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
src/agent/onefuzz-agent/src/tasks/report/generic.rs
src/agent/onefuzz-agent/src/tasks/report/libfuzzer_report.rs
src/agent/onefuzz/src/expand.rs
src/agent/onefuzz/src/syncdir.rs

Enables the supervisor tasks to be fully self-contained.
This includes:
1. make `tools` optional
2. making target_* in the config optional
3. add optional unique_reports, reports, and no_repro synced dirs.
4. adding `reports_dir` as an expanded argument, which is an agent-managed local directory.  Files written in `reports_dir` are attempted to be parsed as `crash reports` or `no repro reports`, which are uploaded to the reporting containers as configured.
This does not include:
* Updates to the CLI & Service to enable this feature.

allow supervisor tasks to be fully self-contained fuzzing tasks

---

src/api-service/__app__/onefuzzlib/agent_events.py

Only save the last 4k of stdout and stderr as TaskEvents.
This prevents hitting Azure Tables element size limits.

set max stdout/stderr size

---

src/cli/setup.py
src/pytypes/setup.py

Use the correct field for specifying the license for the onefuzz python pacakges following [setup tools documentation](https://packaging.python.org/guides/distributing-packages-using-setuptools/#license)

use license rather than license_file for python packages

---

src/api-service/__app__/onefuzzlib/pools.py

This helps keep nodes on scalesets that use `latest` OS image SKUs reasonably up-to-date with OS patches without disrupting running fuzzing tasks with patch reboot cycles.
In combination with the already-merged #416, this PR closes #414.

reimage long-lived nodes

---

src/api-service/__app__/onefuzzlib/notifications/main.py
src/pytypes/onefuzztypes/primitives.py

Remove a vestige of the adhoc events used by the previous SingalR integration for container updates.

remove unused Event generation from the pre-2.0.0 SignalR integration

---

docs/webhook_events.md
src/api-service/__app__/onefuzzlib/tasks/config.py
src/api-service/__app__/onefuzzlib/tasks/defs.py
src/cli/onefuzz/api.py
src/cli/onefuzz/status/cache.py
src/pytypes/onefuzztypes/enums.py
src/pytypes/onefuzztypes/models.py

Exposes the functionality added in #454 to the service & CLI.
Fixes #439

expose supervisor tasks that are fully self-contained fuzzing tasks in the service

---

src/deployment/deploy.py

Fix bug when checking if the default cli application exists

---

src/api-service/__app__/onefuzzlib/azure/vmss.py
src/api-service/__app__/onefuzzlib/pools.py
src/api-service/__app__/timer_daily/__init__.py
src/api-service/__app__/timer_workers/__init__.py
src/pytypes/onefuzztypes/models.py

As is, if a scaleset is "failed" for some reason (such as Azure VM allocation failed), the service does not attempt to push updated VM configs, which can cause our time-limited SAS tokens in the VM config to timeout.
This PR makes 2 changes:
1. attempts to perform any update as long as the scaleset isn't in the "Updating" state
2. moves the config update attempts from once per day configured once per day, but runs every 90 seconds until it's successful.

Continually try updating scaleset configs until successful

---

src/api-service/__app__/onefuzzlib/workers/scalesets.py

This addresses an exception if a scaleset is set to have a configuration update after the scaleset deletion has started.
Example exception:
Exception: ResourceExistsError: (OperationNotAllowed) Operation 'Update Virtual Machine Scale Set' is not allowed on Virtual Machine Scale Set 'b242ea12-69e4-4984-90a5-c31b0d0b490a' since it is marked for deletion. For more information on your operations, please refer to https://aka.ms/activitylog.
Additionally, this will only update the configs if the scaleset has `needs_config_update` set.

Do not update scaleset configs of halting scalesets

---

src/api-service/__app__/timer_workers/__init__.py

With autoscaling, it is important that scalesets and nodes are updated
in a consistent order to prevent update thrashing.

update nodes and scalesets in a consistent order

---

src/api-service/__app__/onefuzzlib/azure/creds.py
src/api-service/__app__/onefuzzlib/tasks/config.py
src/api-service/__app__/onefuzzlib/tasks/main.py
src/api-service/__app__/onefuzzlib/workers/nodes.py
src/cli/examples/oss-fuzz-target.py
src/cli/onefuzz/api.py
src/cli/onefuzz/cli.py
src/cli/onefuzz/debug.py
src/cli/onefuzz/status/cache.py
src/cli/onefuzz/templates/__init__.py
src/cli/onefuzz/templates/afl.py
src/cli/onefuzz/templates/libfuzzer.py
src/cli/onefuzz/templates/ossfuzz.py
src/cli/onefuzz/templates/radamsa.py
src/pytypes/onefuzztypes/events.py
src/pytypes/onefuzztypes/models.py
src/pytypes/onefuzztypes/requests.py

In refactoring the autoscaling code, I noticed that the primitive types that provides consistent data validation for Containers, Pool Names, and Regions were not used everywhere.  This PR corrects that issue.
This more broadly uses at-deserialization-time validation, rather than relying on our ORM's identification that `str` is an unchecked and therefore only used as a post-query filter.

use the primitive types in more places

---

src/api-service/__app__/onefuzzlib/workers/nodes.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py

Scalesets can have nodes that never check in (such as broken OS setup scripts).
This will add nodes that Azure knows about but have not checked in such that the `dead node` detection will eventually reimage the node.
NOTE: If node setup takes longer than NODE_EXPIRATION_TIME (1 hour), this will cause the nodes to continuously get reimaged.

add missing scaleset nodes

---

src/api-service/__app__/onefuzzlib/azure/storage.py

As is, this logs a ref to the current function, rather than the list of discovered accounts.

fix logging to show corpus accounts found

---

src/deployment/azuredeploy.json

This removes the unhelpful warning generated by the Azure Functions SignalR integration stating "Unsupported service transport type: . Use default Transient instead."
Ref: https://github.com/Azure/azure-functions-signalrservice-extension/issues/156

set default SignalR transport

---

src/agent/onefuzz-agent/src/local/libfuzzer.rs
src/agent/onefuzz-agent/src/tasks/config.rs
src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs

Currently, the a bad libfuzzer (such as missing a prereq dll) transitions from `setting_up`, to `running`, then to `failure`.
This PR, in combination with #530, will make `--wait_for_running` actually useful in determining if the libfuzzer target is meaningfully launched.

check libfuzzer `-help=1` prior to starting the heartbeat

---

src/cli/onefuzz/templates/__init__.py
src/pytypes/onefuzztypes/enums.py

This fixes the checks from task & job state checking.
Additionally, this PR waits until we've seen at least one heartbeat before saying the task is fully `running`.

Fix wait_for_running for templates

---

docs/webhook_events.md
src/api-service/__app__/onefuzzlib/endpoint_authorization.py
src/api-service/__app__/onefuzzlib/user_credentials.py
src/pytypes/onefuzztypes/models.py

In cases where the Authorization header is not available, check x-ms-token-aad-id-token for the JWT token of the requesting user.
Note: this header is expected per documentation:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/app-service/app-service-authentication-how-to.md#retrieve-tokens-in-app-code

handle tokens from x-ms-token-aad-id-token

---

src/agent/onefuzz-agent/src/tasks/coverage/recorder.rs

As is, when coverage extraction failed due to instrumentation issues generates the error message:
`Error: no coverage files for input: C:\windows\TEMP\.tmpVFqsjw\479d1ab6410822bd7334f03b1fd599842415c8be`
This PR does a few things:
1. Specifies the filename, rather than generated temp directory name
2. Specifies the filename of the fuzzer
3. Specifies that it appears sancov instrumentation is missing
The same input should generate the following error with this PR:
`coverage extraction from c:\onefuzz\path\to\fuzz.exe failed when processing file "479d1ab6410822bd7334f03b1fd599842415c8be".  target appears to be missing sancov instrumentation`

update error message when coverage extraction fails

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

NOTE: This update is primarily driven by [RUSTSEC-2021-0023](https://rustsec.org/advisories/RUSTSEC-2021-0023), which indicates that users of `rand-core` based PRNGs could be seeded incorrectly.

update 3rd-party rust dependencies

---

src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
src/agent/onefuzz/src/expand.rs

expose input_blob fields needed to generate crash reports

---

src/cli/onefuzz/status/cmd.py

Adds `onefuzz status job` and `onefuzz status project` subcommands that give a brief summary of the job.   The former takes a job_id.  The later takes a project, name, and optionally build and iterates over jobs to find the identified jobs.
```
$ onefuzz status job ffe3e2da-283a-408f-a2de-edf1c7435547
job: ffe3e2da-283a-408f-a2de-edf1c7435547
project:test-b2835691 name:linux-trivial-crash-asan build:0
tasks:
a93ad5ab target:fuzz_target_1 state:stopped type:libfuzzer_crash_report
d788700e target:fuzz_target_1 state:stopped type:libfuzzer_coverage
tasks with errors:
a350cb0e type:libfuzzer_fuzz target:fuzz_target_1
error:
node reimaged during task execution
containers:
setup           count:1     name:oft-setup-223f76a2007a5beeabb3d25a24eb77ad
crashes         count:7 …
```

add status job commands

---

src/agent/onefuzz-agent/src/tasks/coverage/recorder.rs

This moves from:
```
"Error: coverage extraction from C:\users\bcaswell\projects\bugs\andrew-coverage-fail\setup\oft-setup-5c77cfe1b181520ab0b33a16286a690a\fuzz.exe failed when processing file "11f6ad8ec52a2984abaafd7c3b516503785c2072".  target appears to be missing sancov instrumentation",
```
To even more explicit:
```
Error: Target appears to be missing sancov instrumentation.  This error can happen due to missing coverage symbols.
target_exe: C:\users\bcaswell\projects\bugs\andrew-coverage-fail\setup\oft-setup-5c77cfe1b181520ab0b33a16286a690a\fuzz.exe
input: "11f6ad8ec52a2984abaafd7c3b516503785c2072"
debugger stdout:
...
[+] disabling sympath
[+] processing fuzz.exe
[+] no tables  fuzz.exe
[+] processing C:\WINDOWS\SYSTEM32\kernel.appcore.dll
[+] no tables …
```

make missing symbols for coverage tasks more explicit

---

src/api-service/__app__/onefuzzlib/azure/vmss.py

Example exception that is now handled:
```
Exception while executing function: Functions.timer_workers 
Result: Failure
Exception: ResourceExistsError: (SkuNotAvailable) The requested size for resource '/subscriptions/GUID/resourceGroups/RESOURCE_GROUP_NAME/providers/Microsoft.Compute/virtualMachineScaleSets/GUID' is currently not available in location 'REGION' zones '' for subscription 'GUID'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.
```
NOTE: This change uses the `repr` of the exception to remove the complexity of searching through nested ODataV4Format errors that make up the exception record.

handle SkuNotAvailable errors when creating VM Scalesets

---

src/api-service/__app__/node/__init__.py
src/api-service/__app__/onefuzzlib/workers/nodes.py

As is, when a user triggers to reimage a node, it waits for the node to confirm the reimage.
This moves the model such that if the user triggers reimaging, the node is notified, but the reimage happens regardless of the node's confirmation.

make user triggered reimaging happen immediately

---

src/cli/onefuzz/templates/__init__.py

Right now, the coverage containers for the same target on different builds & operating systems collide.  This isn't useful, as the methods for instrumenting coverage are different for each OS and each build changes the potential for exposed coverage..

coverage containers should be unique to the project/name/build/platform

---

src/api-service/__app__/onefuzzlib/agent_events.py
src/api-service/__app__/onefuzzlib/orm.py

rather than `..onefuzzlib.module`, just use `.module`

import local relative paths

---

src/api-service/__app__/onefuzzlib/notifications/common.py
src/api-service/__app__/onefuzzlib/notifications/github_issues.py

add details to exceptions generated during report render failures

---

docs/webhook_events.md
src/api-service/__app__/onefuzzlib/events.py
src/api-service/__app__/onefuzzlib/webhooks.py
src/api-service/tests/test_webhook_hmac.py
src/pytypes/extra/generate-docs.py
src/pytypes/onefuzztypes/events.py

add instance information to webhooks

---

src/api-service/__app__/onefuzzlib/jobs.py
src/api-service/__app__/timer_tasks/__init__.py

If a job does not start within 30 days, stop the job and mark all of the tasks as `failed`.

stop jobs that do not start within 30 days

---

src/api-service/__app__/onefuzzlib/workers/nodes.py
src/api-service/__app__/timer_workers/__init__.py

As is, when multiple tasks are running on a single node, if any one of them stops, the node gets reimaged.
This changes the behavior such that when a node with multiple tasks has one task stop, the other tasks will continue.

allow nodes with multiple tasks to continue on task stop

---

src/api-service/__app__/onefuzzlib/azure/containers.py

When users try to create a container immediately after deleting it, Azure will fail saying the deletion is in-progress.
catching ResourceExistsError during create handles this error.

handle error condition when creating a container that is being deleted

---

src/agent/onefuzz-telemetry/src/lib.rs

As of `rustc` 1.50.0, [`AtomicUsize::compare_and_swap()`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html#method.compare_and_swap) is deprecated.
The appropriate migration is described [here](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html#migrating-to-compare_exchange-and-compare_exchange_weak).

Use non-deprecated atomic method

---

src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
src/agent/onefuzz-agent/src/tasks/generic/input_poller.rs
src/agent/onefuzz-agent/src/tasks/generic/input_poller/tests.rs
src/agent/reqwest-retry/src/lib.rs
src/ci/agent.sh

- Update the `onefuzz-agent` unit tests and re-enable in CI
- Disable `reqwest-retry` integration test that depends on a local server

Update `onefuzz-agent` unit tests

---

src/api-service/__app__/onefuzzlib/orm.py

This addresses broken queries used for identifying outdated nodes.

fix bool queries

---

docs/telemetry.md
src/agent/Cargo.lock
src/agent/onefuzz-agent/src/local/common.rs
src/agent/onefuzz-agent/src/managed/cmd.rs
src/agent/onefuzz-agent/src/tasks/config.rs
src/agent/onefuzz-supervisor/src/config.rs
src/agent/onefuzz-supervisor/src/main.rs
src/agent/onefuzz-telemetry/Cargo.toml
src/agent/onefuzz-telemetry/src/lib.rs
src/agent/onefuzz/src/lib.rs
src/proxy-manager/Cargo.lock
src/proxy-manager/src/config.rs

* renames `telemetry_key` to `microsoft_telemetry_key`
* renames `instrumentation_key` to `instance_telemetry_key`
* renames `can_share` to `can_share_with_microsoft`
* renames the `applicationinsights-rs` instances to `internal` and `microsoft` respective of the keys used during construction.
This clarifies the underlying use of Application Insights keys and uses struct tuple to ensure the keys are used correctly via rust's type checker.

Renames application insights keys to be more clear

---

src/agent/onefuzz-supervisor/src/buffer.rs
src/agent/onefuzz-supervisor/src/main.rs
src/agent/onefuzz-supervisor/src/worker.rs
src/agent/onefuzz-supervisor/src/worker/tests.rs

In the supervisor agent, incrementally read from the running worker agent's redirected stderr and stdout, instead of waiting until it exits.
The worker agent's stderr and stdout are piped to the supervisor when tasks are run. The supervisor's `WorkerRunner` does _not_ use `wait_with_output()`, which handles this (at the cost of blocking). Instead, it makes repeated calls to to `try_wait()` on timer-based state transitions, and does not try to read the pipes until the worker exits. But when one of the child's pipes is full, the child can block forever waiting on a `write(2)`, such as in a `log` facade implementation.
This bug has not been caught because we control the child worker agent, and until recently, it mostly only wrote to these streams using `env_logger` at its default log level. …

Actively tail worker stdio from supervisor agent

---

src/deployment/requirements.txt

We don't use `azure-mgmt-web` during deployment.  This removes it from requirements.txt

remove azure-mgmt-web from prereq deployments

---

contrib/deploy-onefuzz-via-azure-devops/Pipfile.lock

Fixes the breaking build due to pylint being out-of-date.
`Pylint 2.7.0 includes a fix for vulnerable regular expressions in 'pyreverse'.`

update python prereqs in ADO contrib tool

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

Updated dependencies, primarily to pull in the latest versions of pin-project-lite as the previous versions were yanked.

update 3rd party rust dependencies

---

src/agent/onefuzz-agent/src/tasks/generic/input_poller.rs

Simplifies the logs from:
`Processing batch-downloaded input Ok(DirEntry(DirEntry("task_crashes_1/input-b4c3482194a6ebd275577ea52255fcea3358f3220c408d3c53b9f32b653e6586.txt")))`
to:
`Processing batch-downloaded input: task_crashes_1/input-b4c3482194a6ebd275577ea52255fcea3358f3220c408d3c53b9f32b653e6586.txt`

simplify batch-processing log

---

src/agent/Cargo.lock
src/agent/reqwest-retry/Cargo.toml
src/agent/reqwest-retry/src/lib.rs

In debugging the connection retry issues, I dug into this more.  
Apparently, some of hyper's connection errors are not mapped to std::io::Error, rendering the existing downcast impl ineffective.
As such, this PR makes the following updates:
1. Any request that fails for what `reqwest` calls a `connection` error is considered transient.
2. Updates the retry notify code to use our `warn` macro such that the events show up in application insights.
3. Updates the unit test to demonstrate that failures by trying to connect to `http://localhost:81/`, which shouldn't be listening on any system.
4. Adds a simple unit test to verify with send_retry_default, connections to https://www.microsoft.com work
Fixes #263

fix agent `retry` on connection level failures

---

src/api-service/__app__/onefuzzlib/tasks/config.py

This prevents querying the blob store for paths such as "./foo" instead of "foo", which fails.

require target_exe to be a canonicalized relative path

---

src/agent/libclusterfuzz/README.md
src/agent/libclusterfuzz/cgmanifest.json

An upcoming PR will include rust code ported from clusterfuzz.  This is intended to enable our component governance process to pick this up such that we can have our legal review prior to the inclusion of the code.

pre-define clusterfuzz as a dependency

---

src/deployment/requirements.txt

Remove ServiceBus dependency, as this isn't used in OneFuzz

remove azure-mgmt-servicebus from deployment dependencies

---

src/ci/agent.sh

This ignores [RUSTSEC-2019-0036](https://rustsec.org/advisories/RUSTSEC-2019-0036), a type confusion bug in  [failure](https://crates.io/crates/failure) (see https://github.com/rust-lang-nursery/failure/issues/336).  
At the moment,  [failure](https://crates.io/crates/failure) is only brought in as a nested dependency of [proc-maps](https://crates.io/crates/proc-maps) and does not implement the pattern required to hit the type confusion bug.  Additionally, the  [failure](https://crates.io/crates/failure) dependency is only used on OSX which we don't support (see https://github.com/rbspy/proc-maps/pull/7).
As such, this security issue does not impact OneFuzz at the moment, but we should work to remove the dependency.  Future updates to third-party dependencies may expose the vulnerability. …

ignore RUSTSEC-2019-0036

---

src/agent/debugger/src/dbghelp.rs
src/agent/debugger/src/debugger.rs
src/agent/debugger/src/stack.rs

The wrong PC was from the context record and incorrectly adjusted by 1 which worked well enough to see the correct function name and line numbers, but was the wrong offset.
The correct PC is passed in a STACKFRAME_EX struct.

Fix incorrect offset in stack reports

---

src/ci/azcopy.sh

aka.ms is having stability issues.  We've seen multiple build failures due to:
```
$ wget -O azcopy.zip https://aka.ms/downloadazcopy-v10-windows
--2021-03-10 19:03:54-- https://aka.ms/downloadazcopy-v10-windows
Resolving aka.ms (aka.ms)... 23.223.13.99
Connecting to aka.ms (aka.ms)|23.223.13.99|:443... connected.
OpenSSL: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
Unable to establish SSL connection.
$
```
This PR should help by making wget automatically retry on failure.  This will try up to 30 times, waiting 5 seconds between each attempt.

automatic retry on wget failure

---

src/agent/coverage/src/code/tests.rs
src/agent/debugger/src/stack.rs
src/agent/input-tester/src/crash_detector.rs
src/agent/input-tester/src/test_result/mod.rs
src/agent/reqwest-retry/src/lib.rs
src/ci/agent.sh

* removed some superfluous types related to stack walking on Windows
* include the function offset even if we have source information
* fixed test build
* run `cargo test --workspace` in CI

Simplify types used in stack walking

---

src/agent/reqwest-retry/src/lib.rs

Thanks primarily due to lookups on `localhost` but also impacted by host-based firewalls silently dropping packets, this test could be racy.
This addresses those issues.

fix racy tests for expected failures in web requests

---

src/agent/Cargo.lock
src/agent/onefuzz/src/libfuzzer.rs

This PR addresses an issue exposed when updating to the latest `regex` version.
Prior to this PR, the latest regex would give the following error:
```
error[E0597]: `re` does not live long enough
--> onefuzz/src/libfuzzer.rs:214:15
|
214 |         match re.captures_iter(&output_text).next() {
|               ^^----------------------------
|               |
|               borrowed value does not live long enough
|               a temporary with access to the borrow is created here ...
...
228 |     }
|     -
|     |
|     `re` dropped here while still borrowed
|     ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `regex::CaptureMatches<'_, '_>`
|
= note: the temporary is part of an expression at the end of a block;
consider forcing …
```

address issues from by latest regex update

---

src/api-service/__app__/onefuzzlib/workers/scalesets.py

If a user manually deletes a scaleset managed by OneFuzz, then `get_vmss_size` returns None.
When this happens, `Scaleset.shutdown` generates an exception from the `logging.info` call on line 573.
This PR handles this edge condition.

handle exception related to manually deleted scalesets

---

src/agent/reqwest-retry/src/lib.rs

Simplify the retry logic to always retry any failed request up to 5 times.  The initial delay is now 5 seconds (plus jitter).
Additionally, upon failure we now indicate how many times we failed as well as the timing for each of the request.

retry any failed request regardless of status

---

src/agent/onefuzz/src/env.rs
src/agent/onefuzz/src/lib.rs
src/agent/onefuzz/src/libfuzzer.rs

This is targeted to only adding the PATH for libFuzzer targets.
We should consider potentially adding `setup_dir` to PATH agent wide in the future, but that could be a breaking change for some environments.

add setup_dir to the PATH for libfuzzer

---

src/agent/onefuzz/src/env.rs
src/agent/onefuzz/src/input_tester.rs
src/agent/onefuzz/src/lib.rs
src/agent/onefuzz/src/libfuzzer.rs

Similar to #680, but for linux
Note: This also adds setup_dir to LD_LIBRARY_PATH and PATH to input tester, which #680 did not include (but should have)

Add 'setup_dir' to LD_LIBRARY_PATH for unix based libfuzzer targets

---

src/agent/coverage/Cargo.toml
src/agent/coverage/examples/block_coverage.rs
src/agent/coverage/src/block/windows.rs
src/agent/coverage/src/code.rs
src/agent/coverage/src/code/tests.rs
src/agent/input-tester/src/crash_detector.rs

- Add coverage filtering to Windows generic coverage recording
- Temporarily disable deserialization of symbol filter rules

Enable coverage module filtering (only) for both platforms

---

src/agent/onefuzz-agent/src/local/cmd.rs
src/agent/onefuzz-agent/src/tasks/stats/common.rs
src/agent/onefuzz-telemetry/src/lib.rs
src/proxy-manager/Cargo.lock
src/proxy-manager/Cargo.toml

Prior to this fix, all logging would show up as:
```
[2021-03-26T19:53:31Z INFO  onefuzz_telemetry] Starting libFuzzer crash report task
```
This moves the actual calls to `log::log!()` to the macros, which puts it in the source file in question.
Now the events look like:
```
[2021-03-26T21:20:14Z INFO  onefuzz_agent::tasks::report::libfuzzer_report] Starting libFuzzer crash report task
```
Most importantly, this allows us to use env_logger's ability to filter on a per module basis in a meaningful fashion.  As an example, this allows:
```
RUST_LOG="info,onefuzz::syncdir=warn,onefuzz_agent::tasks::fuzz::libfuzzer=warn"
```

address telemetry log message locality

---

src/agent/onefuzz/src/syncdir.rs

This does the following:
1. set log verbosity on the guard from temp file vanish to debug
2. only display the filename for syncdir events.  
This means, instead of:
```
[2021-03-27T01:12:08Z INFO  onefuzz::syncdir] new_coverage path:/home/USERNAME/projects/onefuzz/onefuzz/src/agent/onefuzz-agent/00000000-0000-0000-0000-000000000000/ccea6ac6-79be-46ba-bdd9-df1f0e56ec96/inputs_dir/.1a0670e5ab896fcf914af212d80555b6305d3fb5.BE5fc8
```
We see:
```
[2021-03-27T01:12:08Z INFO  onefuzz::syncdir] new_coverage path:1a0670e5ab896fcf914af212d80555b6305d3fb5.BE5fc8
```

cleanup syncdir events

---

src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
src/agent/onefuzz/src/syncdir.rs

Currently hard-coded for libFuzzer, which uses dotfiles for temporary analysis.

optionally ignore dotfiles in syncdir monitors

---

src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
src/agent/onefuzz-agent/src/tasks/generic/input_poller.rs
src/agent/onefuzz-agent/src/tasks/generic/input_poller/tests.rs
src/agent/onefuzz-agent/src/tasks/report/generic.rs
src/agent/onefuzz-agent/src/tasks/report/libfuzzer_report.rs

The polling logs now look like this:
```
[2021-03-27T01:48:57Z INFO  onefuzz_agent::tasks::generic::input_poller] processing libfuzzer-crash-report input: crash-54322de1dee85b932a3b5d850680eabed4fceb63  
```
Where it used to look like this:
```
[2021-03-27T01:48:57Z INFO  onefuzz_agent::tasks::generic::input_poller] processing input: /home/USER/GUID/GUID/.temp/.RANDOMSTRING/filename  
```

add names for poller logging

---

src/agent/coverage/src/block/windows.rs

Enables accessing recorded coverage without using the top-level `record()` function.

Borrow `Recorder` in debug event handler

---

src/cli/onefuzz/api.py

Apparently, different regions can have different disk requirements for the same VM sku.  Until we can include identifying what the VM requirements are on a per-region basis, this should be off by default.

set ephemeral disks off by default

---

src/agent/onefuzz-supervisor/src/config.rs
src/agent/onefuzz/src/auth.rs
src/api-service/__app__/onefuzzlib/extension.py
src/api-service/__app__/pool/__init__.py
src/deployment/azuredeploy.json
src/deployment/deploy.py
src/deployment/registration.py
src/pytypes/onefuzztypes/models.py

The end-to-end changes needed to have onefuzz deployed with multi-tenant authentication.

Added support for multi tenant authentication

---

src/agent/coverage/examples/block_coverage.rs
src/agent/coverage/src/block.rs

Update command block coverage serialization to support a more compact JSON format. See tests for examples.

Use custom serialization for block coverage

---

src/agent/onefuzz-supervisor/src/coordinator.rs
src/agent/onefuzz/src/syncdir.rs
src/agent/onefuzz/src/uploader.rs
src/agent/reqwest-retry/src/lib.rs

This fixes retrying on bad status codes.
Note, this adds support to specify specific error codes as "successful".  This is important for the If-None-Match conditional upload case (blob uploading).  The response we get back is 409 (Conflict).
Previously, we would "fail fast" the 409.  However, what we want is "409 is basically success here" and every other call 409 should be a failure.

fix checking status codes for failure

---

src/agent/onefuzz-agent/src/tasks/config.rs
src/agent/onefuzz-supervisor/src/config.rs
src/api-service/__app__/onefuzzlib/extension.py
src/api-service/__app__/onefuzzlib/proxy.py
src/api-service/__app__/onefuzzlib/tasks/config.py
src/api-service/__app__/pool/__init__.py
src/proxy-manager/src/config.rs
src/pytypes/onefuzztypes/models.py

In #766, the telemetry keys were renamed to reduce confusion.  However, this broke the telemetry keys within the agent due to a known issue using flattened json with aliases (See https://github.com/serde-rs/serde/issues/1976).
This PR removes the aliases and fixes the agent level telemetry & logging.

rename telemetry key names at the service level

---

src/deployment/deploy.py
src/deployment/registration.py

As is, 1f deployments deploy to the current az-cli profile subscription.  It would be useful to be able to deploy to a user specified subscription rather than the current one.

allow deployment to non-default subscriptions

---

src/deployment/azuredeploy.json

This is a quick fix for multi tenant authentication. After doing some more testing, I realized I was missing a parameter in `azuredeploy.json`. So added missing code from previous [PR ](https://github.com/microsoft/onefuzz/pull/563/files). 
I have tested these changes and was successfully able to deploy in both single tenant and multi tenant environments.

Added missing parameter for multi tenant deployment

---

src/pytypes/onefuzztypes/requests.py

This fixes an issue for an older CLI (2.4.0) trying to create a scaleset on a new instance (2.12.0).

set default value for ephemeral disks at the server request parser

---

src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs

Upon failure, OneFuzz reports the stderr as part of the task failure.  In some cases, this could end up being an excessive amount of data kept in memory.  This limits the stderr saved in case of failure to at most the last 1024 lines.

limit the amount of data recorded from libFuzzer's stderr

---

src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs

As is, the execs/sec and iteration counts require significant work from the user to understand how much work their fuzzer has done and how many tests per second they are seeing.  This tries to simplify that data from a given runner's perspective.

combine execs/sec and iteration counts from multiple workers

---

src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs

this makes the local mode significantly easier to manage

don't remove inputs once processed

---

src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
src/agent/onefuzz-agent/src/tasks/coverage/recorder.rs

This PR embeds the coverage debugger scripts in the binaries, which streamlines the redistribution.   Users can specify ONEFUZZ_TOOLS to specify a path to the scripts using existing behaviors.

embed coverage debugger scripts

---

src/api-service/__app__/onefuzzlib/tasks/main.py

In the case a task fails multiple times (such as with multiple VMs), we only record the first failure.

only record the first failure if a task has multiple failures

---

src/api-service/__app__/onefuzzlib/webhooks.py
src/pytypes/onefuzztypes/webhooks.py

Due to BaseEvent denying extra fields (see below), the addition of timestamp to WebhookMessageLog in #796 creates a backwards compatibility issue.
https://github.com/microsoft/onefuzz/blob/e413aec03dcd682c049855b77cf0b0042407ddc1/src/pytypes/onefuzztypes/events.py#L27-L29

remove timestamp from WebhookMessageLog model

---

docs/webhook_events.md
src/pytypes/onefuzztypes/events.py

Allow extra fields enables the use of optional fields as a backwards compatibility layer.
See #804 as to why this is needful.

allow extra fields in Events

---

src/cli/onefuzz/templates/libfuzzer.py

dotnet, as well as the _create_tasks helper still used the old default for requiring crash files on libFuzzer exiting non-zero

disable expect_crash_on_failure by default in more places

---

src/agent/Cargo.lock
src/agent/coverage/Cargo.toml
src/agent/coverage/src/block.rs

- Add `module!` test helper to let us always define tests paths using POSIX-style paths
- Use `serde_json::json!` macro for maintainable definitions of expected test results

Simplify handling of OS-sensitive test cases

---

src/agent/coverage/src/block.rs
src/agent/coverage/src/block/linux.rs
src/agent/coverage/src/block/windows.rs
src/agent/coverage/src/cache.rs
src/agent/coverage/src/disasm.rs

In #765, we introduced an assumption that all module-relative instruction offsets are representable by a `u32`. Move to an explicit `u32` repr for offsets, and add validation to check for overflow at conversion sites.

Use `u32` to represent module offsets

---

src/agent/input-tester/src/crash_detector.rs
src/agent/input-tester/src/lib.rs
src/agent/input-tester/src/tester.rs

Add a `module_cache` field to the `Tester` struct and ctor (which is not used by OneFuzz). This enables coverage collection when using it to test inputs. Add an optional `coverage` field to the `DebuggerResult` in the `input-tester` crate. This lets users retrieve per-input coverage after testing an input.

Add optional coverage to `input-tester` API

---

src/agent/coverage/src/block.rs
src/agent/coverage/src/block/windows.rs

- Weaken argument bounds to `IntoIterator`
- Reduce log level to `debug`

Improve usability of coverage types 

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

This is specifically focused on updating `hyper`, which yanked 0.14.6

update third-party rust libraries

---

src/agent/onefuzz-supervisor/src/agent.rs

In current tokio, time::sleep().elapsed does not update unless the Sleep
is polled.  as such, the execute_pending_commands never fires.  This
replaces the sleep().elapsed with Instant.elapsed().

move to Instant.elapsed() instead of time::Sleep timer

---

src/api-service/__app__/onefuzzlib/workers/nodes.py

In situations when the node should be done, mark it as done without
waiting for the node to respond to the Done command.

when processing node updates, don't wait on the node in cases it should be stopped

---

src/api-service/__app__/onefuzzlib/azure/queue.py

Handle queues getting deleted during peek_queue.  This can happen when
polling the pool for work while the pool is getting shut down.

handle queues vanishing during peek

---

src/api-service/__app__/node/__init__.py
src/api-service/__app__/onefuzzlib/workers/nodes.py
src/pytypes/onefuzztypes/models.py

This exposes the node commands that have yet to be processed by the node.
Example use case:  The SDK can now ask "has this node installed my SSH key"

Add node messages to node get

---

src/agent/coverage/src/block.rs
src/agent/coverage/src/lib.rs
src/agent/coverage/src/report.rs
src/agent/coverage/src/test.rs

- Redefine the coverage report format to be easily extensible
- Introduce a generic `CoverageReport` struct for coverage report serialization
- Implement runtime-recorded block coverage serialization via conversion into the former
Note: we internally maintain strong requirements on the `module` fields that OneFuzz will generate, but we have relaxed the serialization-level types. So, the type-encoded constraints we leverage at runtime (modules are named by `ModulePaths`, which are OS-specific absolute paths with filenames) must be checked when converting from a report to a runtime coverage map.
The slight generalization here supports eventually defining custom coverage report formats like so:
```rust
#[derive(Serialize)]
struct Metadata {
sha256: String,
thread_name: String,
} …
```

Separate report serialization from runtime struct

---

src/agent/coverage/src/lib.rs
src/agent/coverage/src/pdb.rs
src/agent/coverage/src/pe.rs

This does not implement any logic changes, but reorganizes code for easier re-use.

Move PDB functions into own module

---

src/agent/coverage/src/block.rs

Allow consumers to stay consistent with the OneFuzz block coverage report format, but mutate reports if desired.

Make field public for `CoverageReport` consumers

---

src/agent/coverage/src/block/pe_provider.rs
src/agent/coverage/src/lib.rs
src/agent/coverage/src/sancov.rs

- Factor out OS-independent Sancov analysis logic
- Remove some unwraps and unchecked casts
- In the inline access scanner, use a VA for the disassembler PC and explicitly compute offsets

Factor out Sancov analysis

---

src/agent/coverage/src/block/pe_provider.rs
src/agent/coverage/src/lib.rs
src/agent/coverage/src/sancov.rs

Sancov table start delimiters are padded on Windows, but not Linux. Expose this in the `SancovDelimiters` interface and update the PE block provider.
Based on #855, merge after.

Explicitly pad start delimiters on Windows

---

src/api-service/__app__/onefuzzlib/workers/scalesets.py

Handle someone manually deleting scalesets out from under OneFuzz when the scaleset is resizing.
Fixes #857

shutdown missing scalesets during resize

---

src/agent/Cargo.lock

The `cpuid-bool` crate was renamed to `cpufeatures`, and the former marked as unmaintained. See [RUSTSEC-2021-0064](https://rustsec.org/advisories/RUSTSEC-2021-0064).
Update our lockfile and unbreak the build.

Update `sha2` to 0.9.4

---

src/agent/coverage/src/sancov.rs

- Detect Sancov table accesses via static displacements, not just PC-relative
- Explicitly skip instructions with no memory operand
- Skip instructions whose effective address relies on (non-PC) register values

Improve precision of inline table access scanning 

---

src/agent/onefuzz-supervisor/src/coordinator.rs
src/agent/onefuzz-supervisor/src/scheduler.rs
src/api-service/__app__/onefuzzlib/versions.py
src/api-service/__app__/onefuzzlib/workers/nodes.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py
src/api-service/__app__/requirements.txt
src/api-service/mypy.ini
src/api-service/tests/test_version_check.py
src/pytypes/onefuzztypes/models.py

Currently, there are two states that are non-obvious as to what happens next.
1. A free node is "out of date".  Right now, it will stay on the old version until it tries to launch a task, at which point the node will check "can I run this work".  When the node asks "can I run this work", the node is rejected and then moves into the reimage/delete state.
2. A free node is part of a shrinking scaleset.  Right now, it will wait until a task launch similar to the "out of date" node to start the shrinking.
This PR adds sending "no_new_work" command to Nodes which basically allows us to tell free nodes to stop.
NOTE:  The node command infra in the supervisor will fail badly if it receives an unsupported command.  As such, this includes "minimum supported version" support that gate sending the …

Add NoNewWork node command to tell free nodes to stop asking for new work

---

src/agent/Cargo.lock
src/agent/onefuzz-agent/Cargo.toml
src/agent/storage-queue/Cargo.toml

yaque is causing a cargo audit failure. The PR removes the dependency because it is not needed

fix build, remove unused reference to yaque

---

docs/webhook_events.md
src/api-service/__app__/onefuzzlib/autoscale.py
src/api-service/__app__/onefuzzlib/workers/pools.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py
src/api-service/__app__/scaleset/__init__.py
src/pytypes/extra/generate-docs.py
src/pytypes/onefuzztypes/events.py

This moves all scaleset state updates through `Scaleset.set_state` and adds a new event EventScalesetStateUpdated.

add event for scaleset state updates

---

.github/workflows/codeql-analysis.yml

Right now, we're running CodeQL analysis on every PR.  Since the alerts get fed into the `Security` pane in GitHub rather than breaking builds, we don't need to tie this to every build.

only run CodeQL on `main`

---

.github/workflows/ci.yml
src/ci/agent.sh

Bump the key used for caching rust compiles, since GitHub actions has a new version of rust.

bump rust cache key

---

src/api-service/__app__/onefuzzlib/azure/creds.py

In azure-mgmt-resource 17.0.0, the resources.get_by_id().properties is now a string, rather than a dict.
In practice, it's not a json string (uses single quotes rather than double quotes).  This converts the quotes & uses json to decode it.
For example, in practice, the value is: "{'tenantId': 'GUID', 'principalId': 'GUID', 'clientId': 'GUID'}

handle issue from azure-mgmt-resource 17.0.0 upgrade

---

src/agent/Cargo.lock
src/agent/onefuzz-agent/Cargo.toml
src/agent/onefuzz/Cargo.toml
src/agent/reqwest-retry/Cargo.toml
src/agent/storage-queue/Cargo.toml

Now that we've updated our `tokio` version, we can easily remove this redundant async runtime dependency (and its transitive deps).

Remove transitive `async-std` dep

---

src/deployment/deploy.py

Fix issue in client creation from #872

fix deployment using client_id

---

src/cli/onefuzz/api.py

This enables specifying the endpoint configuration for alternate tenants purely on the command line.
Previously, on a single tenant you could use the following:
```
onefuzz --endpoint https://INSTANCE.azurewebsites.net info get
```
For multi-tenant installs, we need to expose more than just endpoint.
This enables:
```
onefuzz --endpoint https://INSTANCE.azurewebsites.net --client_id CLIENT_ID  --authority https://login.microsoftonline.com/common --tenant_domain TENANT_DOMAIN info get
```

Add setup arguments to enable specifying alt tenants on the CLI

---

src/cli/onefuzz/cli.py

As demonstrated in #906, failures in parsing key-value options is not obvious.  This explains the failure in a slightly less obtuse fashion.

explain key=value argument parsing failures

---

src/api-service/__app__/onefuzzlib/azure/vm.py
src/api-service/__app__/onefuzzlib/proxy.py
src/api-service/__app__/requirements.txt

As is, the proxy name gets truncated when turned into the disk name.
This prevents the resource cleanup from completion.

encode proxy name as base58 to allow full deletion of resources

---

src/agent/coverage/src/cache.rs
src/agent/coverage/src/pdb.rs
src/agent/coverage/src/pe.rs
src/agent/debugger/src/dbghelp.rs

- Fix a bug in PDB search where we treated the absence of the PE-specified file as a hard error
- In the return type of `find_pdb_path()`, distinguish between "no file found" and a search error

Fix and improve PDB search

---

src/agent/coverage/src/block/windows.rs

Closes #914.
When recording coverage, don't try to use live process handles as the context for the `dbghelp` symbol handler in the module feature cache. Instead, use the default pseudo-handle for the semantically static PDB search, and the target process handle for any queries about the target and its address space.
[The docs](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-syminitializew) for `SymInitializeW` from `dbghelp` are a bit unclear on the _exact_ constraints (and failure modes) around the `HANDLE` one uses to interact with the symbol handler in all `dbghelp` functions.
The docs for the `HANDLE hProcess` parameter say:
> A handle that identifies the caller. This value should be unique and nonzero, but need not be a process handle. **However, if you do use a …

Only use pseudo-handle for coverage `dbghelp` context

---

src/cli/onefuzz/cli.py

Catch argparse argument type errors and display them in a simplified fashion.
As an example, this is how the output is rendered.
```
❯ onefuzz template libfuzzer basic --target_env  ASAN_OPTIONS=allocator_may_return_null=1 a a a linux
unable to parse arguments: unable to parse value as a key=value pair: 'a'   
❯
```
Note, this builds upon #910.

Catch argparse type errors

---

src/agent/onefuzz-supervisor/src/commands.rs

On Windows, removing permissions that have already been removed fails.  As such, this needs to happen once and only once.  
NOTE: SSH keys are added as node commands, which are processed serially.

only set the SSH key permissions on Windows once

---

src/agent/onefuzz-supervisor/src/failure.rs

When the supervisor fails, we log the error context to a file, which is used to inform tasks as what caused the supervisor to fail.
This update logs more details in the error context sent to the task failures.

save more context in the failure log

---

src/api-service/__app__/onefuzzlib/workers/nodes.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py

This fixes a bug where nodes without a recent heartbeat get deleted, rather that reimaged.

fix deleting nodes with expired heartbeats

---

src/api-service/__app__/onefuzzlib/proxy.py
src/api-service/__app__/timer_proxy/__init__.py

This issue was introduced in 2.18.0.

fix issue deleting proxy from storage tables

---

src/cli/onefuzz/status/cmd.py
src/cli/onefuzz/status/top.py
src/cli/onefuzz/status/top_view.py

When originally prototyping the `status top` functionality, I thought
not having the event log would reduce clutter.  Instead, I *always* end
up quitting and restarting with --show_details whenever I forget to
include it.
As such, this just always enables it

always show message details in `status top`

---

src/agent/coverage/examples/coverage.rs
src/agent/coverage/src/block/linux.rs

- Simplify the Linux block coverage `Recorder` API 
- Add a (mandatory) timeout to recording runs
Closes #923.

Add timeout when recording Linux coverage

---

src/api-service/__app__/onefuzzlib/tasks/main.py
src/api-service/__app__/timer_tasks/__init__.py

mark tasks that are stopped that never started with an error

---

src/api-service/__app__/onefuzzlib/orm.py
src/api-service/__app__/onefuzzlib/secrets.py
src/api-service/tests/test_secrets.py

This fixes an issue related to object id reuse that can occur making the object identification cache fail.  Instead, this simplifies `hide_secrets` to always recurse and use `setattr` to always set the value based on the recursion.
Note, the object id reuse issue was seen in the `events.filter_event_recurse` development and this was the fix for the id reuse there.
Python documentation states:
> id(object):
>     Return the “identity” of an object. This is an integer (or long integer)
>     which is guaranteed to be unique and constant for this object during its
>     lifetime. Two objects with non-overlapping lifetimes may have the same
>     id() value.

prevent object id collision in hide_secrets

---

src/api-service/__app__/onefuzzlib/workers/nodes.py

If we move to shutdown a single node but it's not doing work, it will
wait until it picks up work to shutdown.  This shortcuts that.

send NodeCommandStopIfFree on node shutdown

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

This addresses crossbeam-epoch 0.9.3 being yanked.

update rust dependencies

---

src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
src/agent/onefuzz-agent/src/tasks/config.rs
src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
src/agent/onefuzz-agent/src/tasks/heartbeat.rs
src/agent/onefuzz-agent/src/tasks/merge/generic.rs
src/agent/onefuzz-agent/src/tasks/merge/libfuzzer_merge.rs
src/agent/onefuzz-agent/src/tasks/regression/generic.rs
src/agent/onefuzz-agent/src/tasks/regression/libfuzzer.rs
src/agent/onefuzz-agent/src/tasks/report/generic.rs
src/agent/onefuzz-agent/src/tasks/report/libfuzzer_report.rs
src/agent/onefuzz-supervisor/src/heartbeat.rs
src/agent/onefuzz/src/heartbeat.rs

One of the difficulties in crash repro as task is a race condition where we the client tries to connect before the cdb is running.
This makes it such that we can use the heartbeat to identify if the task has started before connecting in.
NOTE:  In this PR, it's always set to None.  See #830 for it's actual usage.  However, I split out the PR for easier review.

add an optional initial delay for heartbeats

---

src/agent/onefuzz/src/az_copy.rs

In an attempt to understand failures in azcopy, this creates a temp directory and includes the logs from azcopy.
Note, this limits the log level to ERROR, as azcopy is quite verbose in it's logging.

capture azcopy log file

---

src/deployment/deploy.py
src/deployment/registration.py

We create a deploy specific logging context, this makes use of it in the rest of the places it was missing.

use deploy logging context for app creation logs

---

src/api-service/__app__/onefuzzlib/events.py
src/api-service/__app__/requirements.txt
src/api-service/tests/test_userinfo_filter.py
src/cli/onefuzz/status/cache.py
src/cli/onefuzz/status/top.py
src/pytypes/onefuzztypes/events.py
src/pytypes/requirements.txt

We're experiencing a bug where Unions of sub-models are getting downcast, which causes a loss of information.  
As an example, EventScalesetCreated was getting downcast to EventScalesetDeleted.  I have not figured out why, nor can I replicate it locally to minimize the bug send upstream, but I was able to reliably replicate it on the service.
While working through this issue, I noticed that deserialization of SignalR events was frequently wrong, leaving things like tasks as "init" in `status top`.
Both of these issues are Unions of models with a type field, so it's likely these are related.

work around issue with discriminated typed unions

---

src/agent/Cargo.lock
src/agent/reqwest-retry/Cargo.toml
src/agent/reqwest-retry/src/lib.rs

Instead of relying on a third-party service (which is currently down), this uses wiremock to run the server testing locally.

move to wiremock for testing

---

src/agent/onefuzz-agent/src/tasks/coverage/generic.rs

Retry coverage recording

---

src/agent/coverage/src/block/linux.rs
src/agent/coverage/src/block/windows.rs

Add context to coverage tracing errors

---

src/cli/onefuzz/backend.py
src/cli/tests/test_serialize.py

This normalizes the SecretData serialization from the client to address #981.
When serializing objects sent to the service with secrets, we would turn it into a SecretData
We use SecretData to convert this:
`{"auth": {"user": "A", "personal_access_token": "B"}}`
to this:
`"auth": { "secret": { "url": "https://KEYVAULT-URL" }}`
Currently, in the case we have a SecretData we've not yet saved, the serialized form looks like this:
`{"auth": { "secret": {"user": "A", "personal_access_token": "B"}}}`
This PR simplifies the client side serialization to this:
`{"auth": {"user": "A", "personal_access_token": "B"}}`

handle serialization of secrets sent from the CLI

---

src/agent/onefuzz/src/blob/url.rs
src/agent/onefuzz/src/syncdir.rs

Url::from_file_path does not support creating `Url` with a relative
path.  This change converts relative paths to canonicalized absolute
paths based on CWD.

fix SyncedDir.remote_url issue with relative paths

---

src/deployment/azuredeploy.json

Internal policies by some of our teams require log durations to be shorter than our previous defaults of 90 days.  This reduces the log retention duration to 30 days.

reduce log retention duration to 30 days

---

src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs

For rapidly exiting libFuzzer targets, the agent can get into a state where it never has a chance for the handles to get reaped.  This eventually causes an OOM error in the system.
This enforces that within a given worker, at least 5 seconds have occurred between each execution of the target.
Note, we effectively had a sleep before, but the performance improvements in #941 removed the effective sleep.

add cooloff period for rapidly exiting libFuzzer targets

---

src/agent/onefuzz-supervisor/src/coordinator.rs

`send_request` receives a `RequestBuilder` with the bearer token already set.  
In the case the token is expired, the token is refreshed. However, the refreshed token wasn't being used.  This uses the refreshed token.
This PR also moves setting the bearer token to only happen in `send_request`.

use the refreshed token when retrying after auth failure

---

src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
src/cli/onefuzz/debug.py

The debug report created by the command `onefuzz debug  notification job <job id>`  is causing a crash in the regression task 
```
error running task: libfuzzer regression
Caused by:
0: handling crash reports
1: unable to parse crash report: fake-crash-sample.json
2: unable to parse report: task_unique_reports_2/fake-crash-sample.json - "{\"input_url\": null, \"input_blob\": {\"account\": \"fuzz27ee6imdmr5gy\", \"container\": \"oft-crashes-cecbd958a1f257688f9768edaaf6c94d\", \"name\": \"fake-crash-sample\"}, \"executable\": \"fuzz.exe\", \"crash_type\": \"fake crash report\", \"crash_site\": \"fake crash site\", \"call_stack\": [\"#0 fake\", \"#1 call\", \"#2 stack\"], \"call_stack_sha256\": \"0000000000000000000000000000000000000000000000000000000000000000\", \"input_sha256\": …
```

fix debug report

---

src/api-service/__app__/onefuzzlib/azure/vmss.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py

Fixes an issue where Azure is now enforcing unique IDs for reimaging & deletion.
```
Exception: HttpResponseError: (InvalidParameter) InstanceIds may not be repeated.
Code: InvalidParameter
Message: InstanceIds may not be repeated.
Target: instanceIds
```

ensure VM IDs are unique before calling Azure reimage/delete APIs

---

.github/workflows/ci.yml
src/ci/agent.sh

This fixes a race condition from the linux & osx agent builds, that if the osx builds take longer than linux builds, we produce an invalid release.

save the agents in a per-$(uname) directory during build

---

.github/workflows/ci.yml
src/agent/Cargo.lock
src/agent/onefuzz-agent/Cargo.toml
src/agent/onefuzz-supervisor/Cargo.toml
src/agent/onefuzz-telemetry/Cargo.toml
src/agent/onefuzz/Cargo.toml
src/agent/reqwest-retry/Cargo.toml
src/agent/storage-queue/Cargo.toml
src/pytypes/onefuzztypes/models.py

rustls enables us to remove a run-time install dependency on openssl.   This enables the same binary to run on Ubuntu 18.04 and Ubuntu 20.04.
In the long term, we probably want to investigate moving to `musl`.
This moves the agent dependencies from:
```
linux-vdso.so.1 (0x00007ffe8d16f000)
libunwind-ptrace.so.0 => /lib/x86_64-linux-gnu/libunwind-ptrace.so.0 (0x00007f4376fea000)
libunwind-x86_64.so.8 => /lib/x86_64-linux-gnu/libunwind-x86_64.so.8 (0x00007f4376fc8000)
libunwind.so.8 => /lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f4376fab000)
libssl.so.1.0.0 => not found
libcrypto.so.1.0.0 => not found
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4376fa0000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4376f7b000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 …
```

move to using rustls

---

src/api-service/__app__/onefuzzlib/notifications/ado.py
src/api-service/__app__/onefuzzlib/notifications/github_issues.py
src/api-service/__app__/onefuzzlib/notifications/main.py
src/api-service/__app__/queue_file_changes/__init__.py

This PR introduce a new parameter `fail_task_on_transient_error` to the notification function. This parameter  is set to `True` when the maximum number of retry is reached for the queue message. 
This allows us the specify the behavior on failure by throwing an exception when a retry is required or fail the task otherwise.

Allow notifications to be retried when an error occurs

---

src/agent/onefuzz-agent/src/tasks/coverage/generic.rs

Use sync pointers for updating `ModuleCache` off-thread

---

src/api-service/__app__/onefuzzlib/workers/nodes.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py
src/api-service/__app__/onefuzzlib/workers/shrink_queue.py

This pulls forwards the ShrinkQueue changes from the autoscale PR

make ShrinkQueue not scaleset specific

---

src/api-service/__app__/agent_registration/__init__.py
src/api-service/__app__/onefuzzlib/workers/nodes.py
src/api-service/__app__/onefuzzlib/workers/pools.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py

This isn't used at the moment, but pulled forwards from the autoscale
PR.  The functionality replicates the scaleset based shrink-queue, but
at the context of pools.
This is built on top of #1049, which should be merged first.

Pool shrink queue

---

src/api-service/__app__/onefuzzlib/workers/nodes.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py

Fix get_dead_nodes query

---

src/runtime-tools/linux/onefuzz.service

- Increase the delay between service restart from 100ms to 1s
partial fix for #1028

Update onefuzz supervisor service restart behavior

---

src/api-service/__app__/onefuzzlib/extension.py

By setting a unique `force_update_tag` on each update the VMs are forced to use the latest version each time they push an update.
https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_03_01.models.virtualmachinescalesetextension?view=azure-python

force upgrade custom script extensions

---

src/api-service/__app__/onefuzzlib/azure/containers.py
src/api-service/__app__/onefuzzlib/azure/vmss.py
src/api-service/__app__/onefuzzlib/extension.py
src/deployment/azuredeploy.json

The new custom script extension configs are not always pulled during reimage.  As such, VMs that outlive the SAS duration may not reimage correctly.
This moves to using a role assignment created at deployment for the scalesets to give read access to the `config` blob storage using the managed identity, rather than using SAS URLs.
https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-linux#property-managedidentity
Short-life VMs (proxies & repros) continue to use the existing SAS mechanism.

use managed identity reader access for scaleset configs

---

src/agent/Cargo.lock
src/agent/onefuzz-supervisor/Cargo.toml
src/agent/onefuzz-supervisor/src/logpanic.rs
src/agent/onefuzz-supervisor/src/main.rs
src/agent/onefuzz-supervisor/src/panic.rs

While investigating #1042, I found a gap in logs that is indicative of the supervisor panicking.  
This PR adds a panic handler that reuses the existing 'failure log' mechanism to record the panic and backtrace.  The failure log mechanism enables recording runtime errors to a file, which is sent to the service on restart.

attempt to log panic stack trace to the supervisor failure log

---

.github/workflows/ci.yml
src/cli/onefuzz/templates/libfuzzer.py
src/integration-tests/integration-test.py

Users specifying `--target_options` will get an invalid crash report options, as `libfuzzer_crash_report` doesn't require `{input}`.

fix issue specifying target_options for libfuzzer targets

---

src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
src/agent/onefuzz-agent/src/tasks/coverage/generic.rs
src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs

When we have a analysis task with a large number of initial inputs, it may take an excessively long time before results show up in the analysis container.
This PR makes it such that we sync the analysis container after every 10 inputs.

sync batch processed results after every 10 inputs

---

src/agent/onefuzz-agent/src/local/common.rs
src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
src/agent/onefuzz/src/monitor.rs
src/agent/onefuzz/src/syncdir.rs

The manual implementation of `Stream` for `DirectoryMonitor` misused the `Waker` provided by `poll_next()`. In practice, this resulted in telling the executor to poll the stream again _immediately_ after any non-terminal `try_recv()`. The end result was equivalent to calling `try_recv()` in a tight loop. This pegged agent CPU usage as soon as we started monitoring directories for new files.
Now, we take a much simpler approach. The private `into_async()` shim function spawns a thread that blocks on new (synchronous) `Receiver` messages, and then immediately sends them to an unbounded async `Receiver`. All subsequent API surface can thus be effortlessly async.
`DirectoryMonitor` now exports a public `next_file()` async method, which is equivalent in practice to implementing `Stream`. We …

Remove `Stream` impl for `DirectoryMonitor`

---

src/api-service/__app__/onefuzzlib/notifications/ado.py

Add more information to the logs of transient error

---

src/agent/input-tester/src/tester.rs
src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
src/agent/onefuzz/src/asan.rs
src/agent/onefuzz/src/expand.rs
src/agent/onefuzz/src/input_tester.rs

This PR primarily addresses parsing non-UTF8 data from the application under test exposed by the inclusion of #1087.
Additionally, this PR does the following:
* Adds context to the generator tasks related to testing applications (helpful for finding this bug)
* Moves from `OsStr.to_str`, which is fallible in the case of non-utf8 values, to `to_string_lossy` in the potential callstacks of the generator.  This is primarily in filenames and can occur with misbehaving generators or applications.

address non-utf8 errors in testing

---

src/agent/Cargo.lock
src/agent/onefuzz-agent/Cargo.toml
src/agent/onefuzz-agent/src/local/cmd.rs

As is, we use static strings for sub-command names.  Moving to an enum means we can rely on the compiler to verify we've implemented everything correctly for the subcommands.

use enum for local commands

---

src/agent/onefuzz/src/asan.rs

We format the ASAN log, truncate it, but don't actually use the truncated version.
This change logs the asan_text as intended.

include asan_text in error

---

src/api-service/__app__/notifications/__init__.py
src/api-service/__app__/onefuzzlib/job_templates/templates.py
src/api-service/__app__/onefuzzlib/notifications/main.py
src/cli/onefuzz/api.py
src/cli/onefuzz/template.py
src/cli/onefuzz/templates/__init__.py
src/pytypes/onefuzztypes/requests.py

This PR adds two features:
1. On creating notifications for containers that already have notification configs, this replaces the existing notifications by default
2. Instead of returning all containers, then iterating over all containers, enable searching the notifications by container name

Replace notifications by default

---

src/integration-tests/integration-test.py

This relates to retry issues and isn't something that the integration tests should fail on.

ignore table exists errors from integration testing at the functions layer

---

src/api-service/__app__/onefuzzlib/workers/pools.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py

Currently, if a pool or scaleset is set to `shutdown`, it cannot be set to `halt`.
While moving from `halt` to `shutdown` would cause issues, moving from `shutdown` to `halt` is fine.

allow pools & scalesets set to `shutdown` to `halt`

---

src/api-service/__app__/onefuzzlib/tasks/config.py

using config.vm depricated prior to 1.0.0

tasks must use pools not VMs

---

src/api-service/__app__/onefuzzlib/tasks/config.py
src/api-service/__app__/onefuzzlib/tasks/defs.py
src/pytypes/onefuzztypes/enums.py

require {input} in target_env or target_options for generator and coverage tasks

---

src/api-service/__app__/onefuzzlib/workers/nodes.py
src/api-service/__app__/onefuzzlib/workers/pools.py

This makes sure debug_keep_node is reset and the rest of the reimage processing occurs regardless of reimage_requested and delete_requested being set.
Without this, nodes that are marked `debug_keep_node` do not get reimaged/deleted.

process all expired nodes rather than those not already marked for deletion

---

src/agent/onefuzz/src/az_copy.rs

When running tasks with large numbers of machines, on VMs with large numbers of cores, with large numbers of files, we rapidly hit Azure Storage performance caps.
azcopy sets the concurrency rate to 32*NUM_CORES.  On a job with hundreds of VMs, this well exceeds the requests-per-second cap of storage accounts.
Ref: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize#increase-the-number-of-concurrent-requests

limit the azcopy concurrency

---

.github/workflows/ci.yml
src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

This is primarily done to address crossbeam-deque 0.8.0 being yanked.

update 3rd-party rust prereqs

---

src/api-service/__app__/containers/__init__.py
src/api-service/__app__/onefuzzlib/azure/containers.py
src/api-service/__app__/onefuzzlib/extension.py
src/api-service/__app__/onefuzzlib/tasks/config.py
src/api-service/__app__/onefuzzlib/tasks/scheduler.py

This removes overloading the `list` built-in.

don't overload `list` builtin

---

src/api-service/__app__/requirements.txt
src/cli/requirements.txt

This primarily meant to enable addressing a warning for caching functions without arguments.
https://github.com/lonelyenvoy/python-memoization/releases/tag/v0.4.0

update memoization to 0.4.0

---

src/cli/onefuzz/backend.py

Service level errors respond with a json dictionary of the format: `{code: int, errors: List[str]}`.
For 1f purposes, we should never retry on service level errors.

don't retry on service-level errors

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/srcview/Cargo.toml
src/agent/srcview/README.md
src/agent/srcview/TODO.md
src/agent/srcview/examples/dump_cobertura.rs
src/agent/srcview/examples/dump_modoff.rs
src/agent/srcview/examples/dump_paths.rs
src/agent/srcview/examples/dump_srcloc.rs
src/agent/srcview/res/example.txt
src/agent/srcview/src/lib.rs
src/agent/srcview/src/modoff.rs
src/agent/srcview/src/pdbcache.rs
src/agent/srcview/src/report.rs
src/agent/srcview/src/srcline.rs
src/agent/srcview/src/srcview.rs
src/agent/srcview/tests/modoff.rs
src/agent/srcview/tests/srcview.rs

`srcview` is a crate which ingests debug info (currently only PDB) and execution traces and then generates source/line based coverage report which can be visualized elsewhere (ADO, VSCode). Currently the only supported report format is Cobertura. The intent is that fuzzer authors can use these reports to identify gaps in their coverage and address them, as well as track the fuzzers efficacy over time.
The crate is reasonably documented -- `cargo doc --open` is probably the best current source of info.
This PR includes all the standalone srcview code, documentation, and tests. It does _not_ include any integration work with the rest of the 1f repo.
In terms of specific integration work I'm aware of:
- We will  need to expose the allow and denylist regex's to the user via fuzzer job …

add srcview crate

---

src/deployment/registration.py

As is, the app registration retry function isn't clear that it's sleeping before trying again.
This attempts to clarify that we'll be trying again after a delay.

clarify the retry logging in registration creation

---

src/cli/onefuzz/cli.py
src/cli/onefuzz/status/cmd.py

The command `onefuzz status pool pool-name` now provides something akin to:
```
❯ onefuzz status pool default
{
"node_state": {
"free": 5,
"busy": 1
},
"tasks": {
"312c725b-a3ca-4718-97b0-793b9a5ca27a": 1
}
}
```

add command to give basic information on a pool

---

src/deployment/registration.py

Handles the case when an application registration is deleted but is still referenced as a preauthorized application in the instance registration. 
This adds a logic to remove any invalid application id form the request to authorize applications.
closes #1171
How to test:
1 - create multiple registration `python registration.py create_cli_registration <instance_namm> subscription_id  --registration_name <name>`
2- delete some of the application registration  in the azure portal
3- create another registration with step 1
Tested
[x] 0 deleted app
[x]1 deleted app
Could not test with >1 app because i had redeployed my environment and the issue does not repro in my new  instance application registration.

retry when preauthorized application are invalid

---

src/deployment/deployment-role.json

With the recent move to deploy using ARM for storage queues, the permission Microsoft.Storage/storageAccounts/queueServices/queues/write needs to be included in the custom deployment role.

Add storage queue write to example deployment role

---

src/agent/onefuzz/src/expand.rs

The template expansion machinery allows `Mapping` placeholders which use a partial callback to provide an expansion value on demand. Add fallibility to the callback signature, which lets us avoid distinguish between callback errors and absent values. Update existing `Mapping` callbacks to return errors in some places where we currently map them to `None`.

Use fallible callbacks for `Mapping` placeholders

---

src/agent/onefuzz/src/auth.rs
src/cli/onefuzz/backend.py
src/deployment/azuredeploy.json
src/deployment/deploy.py

Updating Application ID URI in AppRegistration to a URI accepted by Azure. Moving URI from `https://` to `api://`.
Updating all the code that requires Application ID URI to use a new format.
Run integration test, more tests will be done by @chkeita

Move to using `api://` for AAD Application "identifier uris"

---

src/cli/mypy.ini

azure-storage-blob 12.9.0 includes invalid type signatures.  This change
should be backed out once upstream addresses the type signature issue.
ref: https://github.com/Azure/azure-sdk-for-python/issues/20771

temporarily ignore type errors from azure-storage-blob

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

This updates 3rd-party rust components, primarily to work around the new RUSTSEC identified issue in nanorand.
Ref: https://rustsec.org/advisories/RUSTSEC-2021-0114

update 3rd-party rust components

---

docs/containers.md

Source used to calculate names:
https://github.com/microsoft/onefuzz/blob/7da4352e275835a18d097de544adc1166fd18f9f/src/cli/onefuzz/api.py#L1611-L1642

fix container documentation to align with how coverage also maps to build & platform now

---

src/cli/requirements.txt

1.14.0 provides in-memory http-level cache, which improves handling of
invalid responses

update msal to 1.14.0

---

src/utils/check-pr/check-pr.py

I added `--test_args` to work around the Windows libfuzzer integration tests failing, which enables this workflow to only run the linux integration tests.
`check-pr.py --pr 1268 --test_args --os_list linux`
However, I had not tested without --test_args, since all of the integration tests I was running included passing some argument.
There was a bug that if users didn't provide a value for --test_args, it would generate an exception.
This addresses that bug.

fix running check-pr without test arguments

---

src/cli/onefuzz/api.py

Increase default level of feedback/confirmation in destructive commands #1264

---

.github/workflows/ci.yml
src/deployment/.flake8
src/deployment/deploy.py
src/utils/check-pr/check-pr.py

All of the rest of the python codebases within the repo use flake8 as
part of the lint process.  This aligns the deployment code with the
practice.

use flake8 on deployment

---

src/deployment/azuredeploy.json

Updated `azuredeploy.json` ARM template to deploy newer version of app insights
Run `deploy.py` script to deploy fresh instance of OneFuzz or deploy on existing deployment to upgrade App Insights. Deploying on existing OneFuzz instance preserved app insights data.

Migrate AppInsights Azure resources from classic to work book based

---

docs/AADEntitites.md
docs/comms-channels.md
docs/getting-started.md
docs/managed-identities.md
docs/notifications.md
docs/notifications/teams.md
docs/screencasts/README.md
docs/ssh-config.md
docs/telemetry.md

The project named is properly styled "OneFuzz". Update existing documentation to use this consistently.

Use consistent case for project name in docs

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/onefuzz/Cargo.toml

Temporarily depend on patched `pete`, `ctrlc` crates so we only use the latest `nix`.
We can depend on upstream `ctrlc` after https://github.com/Detegr/rust-ctrlc/pull/81 is merged and/or released.
Replaces #1303.

Update `nix`, patch dependents

---

contrib/onefuzz-job-github-actions/README.md
contrib/onefuzz-job-github-actions/github-pipeline.yml

Our example for deploying jobs from GitHub Actions should work on Windows with minimal modification. Rather than create two almost-identical examples, add comments that clarify concepts and identify what would need to change.
Closes #1305.

Document GitHub integration example to support Windows usage

---

src/deployment/registration.py

Fix a bug in `create_application_registration` when assigning the approle, the value was hardcoded to `ManagedNode`.
Closes #1292 
validation:
- create a new cli registration `python registration.py create_cli_registration <instance> <subscription>`
- in azure the azure portal : Azure Active Directory >> Enterprise Application >>  <registration_name> > Permissions 
verify that the CliClient is assigned

App role assignment not respected when creating a new cli app registration

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/coverage/Cargo.toml
src/agent/onefuzz/Cargo.toml

Update to latest version. Not picked up by Dependabot due to patching.

Update `pete` to 0.8.0

---

src/utils/check-pr/README.md

- Describe what permissions to grant the GitHub API `PAT`
- Document required env vars
- Recommend the use of `virtualenv` and `direnv`
- Note that `-h` can be used for more usage info

Add more setup info to `check-pr` docs

---

src/utils/check-pr/check-pr.py

This change adds a username to the resource group name created by the check-pr utility. This makes it easy to identify who's resources these are. 
A small change to the check-pr.py script.
Ran the script on both wsl2 and powershell to verify it works on both windows and linux printing out the created resource group name. 
Ran the script on wsl2 to verify the resource group name is created correctly. 
Run the script and look for the resource group name.

Add a username to the resource group name created by check-pr utility.

---

.github/workflows/ci.yml

can be reverted once https://github.com/raimon49/pip-licenses/issues/113 is fixed
Pin pip version
Run OneFuzz CLI in github CI pipeline

Work around for newly-upgraded pip breaking pip-licenses

---

src/api-service/__app__/onefuzzlib/tasks/config.py
src/api-service/tests/test_task_config.py

Our validation of `target_exe` blob names spuriously failed when the target was in a nested (virtual) directory. Fix validation to support this case, and check additional Azure blob storage naming criteria. Also, add unit tests.
Closes #1362.
A bug-witnessing `target_exe` value is `bin/fuzz.exe`. This should be accepted.
But consider:
```
>>> import ntpath, posixpath
>>> target_exe = 'bin/fuzz.exe'
>>> posixpath.relpath(target_exe)
'bin/fuzz.exe'
>>> ntpath.relpath(target_exe)
'bin\\fuzz.exe'
```
Our validation required that _each_ `relpath()` invocation above is equivalent to the identity function. But the output of the last `relpath()` call differs from the input.
The last test case ~~ensures~~ [1] that the CLI normalizes relativized paths as POSIX-style, which is consistent with the …

Fix validation of `target_exe` blob name

---

src/deployment/registration.py

This fix an issue when `add_preauthorized_app` tries to remove an invalid application id.
The regex used did not correctly capture the object_id
To validate:
- create a cli registration ` python .\registration.py create_cli_registration <instance> <subscription>`
- in azure portal > Azure Active Directory > App registration > (select the application created) > Delete the application
- create a second cli registration
The creation should be successful with at least one warning with the message `Property PreAuthorizedApplication references applications <application id> that cannot be found.`

Fix error regex when removing invalid application in add_preauthorized_app

---

src/api-service/__app__/onefuzzlib/request_access.py
src/api-service/tests/test_request_access.py
src/pytypes/onefuzztypes/models.py

This PR introduce a new class to store and retrieve rules associated with an api endpoint.
This code will be used as part of the work to enable access control at the api level(#1074 )

Adding a class to store and retrieve rules associated with an api

---

.github/workflows/ci.yml

Update the version of the azure function version to 3.8. This is currently the [highest version](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=azurecli-linux%2Capplication-level#python-version) supported.
And is necessary to use the [protocol feature](https://www.python.org/dev/peps/pep-0544/) used in #1074
run check-pr

Bump python version of the function app to 3.8

---

CHANGELOG.md

We didn't explicitly flag or document the nature of the breaking change in 3.0.0. Update the changelog for consistency.

Flag, describe previous breaking change

---

src/agent/Cargo.lock
src/agent/onefuzz-supervisor/Cargo.toml
src/agent/onefuzz-supervisor/src/worker.rs
src/integration-tests/integration-test.py

This is a fix for #1411. The error was caused by the handling of the stop message. The task seems to log an error after the being killed by the supervisor. These errors are cause the integration test to fail.
the fix is to suspend the child process before killing it so that no error messages gets forwarded to appinsight
How to test:
run check-pr.py

suspend process before killing it

---

src/api-service/__app__/onefuzzlib/notifications/teams.py

This pull request is to address issue #1260. The existing code currently produces invalid Markdown which causes rendering issues in the Teams notifications. A picture of the rendering issue is included within the issue report. This code change will convert the output into a valid Markdown code block which properly renders in Microsoft Teams.
The _code_block_ function should include a newline after the first three back ticks in order to properly start the code block section. Without the newline, the existing code produces three back ticks followed immediately by the data. In Markdown, a word adjacent to the initial three back ticks is assumed to be a language value for the purposes of syntax highlighting. Therefore, the Markdown parser will ignore the invalid data and produces an empty …

Add newline to correct Markdown format

---

src/api-service/__app__/onefuzzlib/azure/image.py

The documentation for using custom images while fuzzing states that Compute Gallery images are supported. However, the existing code for handling custom images does not properly address Compute Gallery resource IDs. The code only handles references to Azure Images. This pull request adds support for Compute Gallery resource IDs as discussed in issue #1443 .  In addition, it corrects an error within the existing code where an attempt to retrieve a "name" parameter is performed on the image "os_type". The "os_type" is a string and does not have a "name" parameter.  This pull request removes the invalid "name" reference and converts the string using ".lower()" similar to the default code path.
This pull request includes a check to determine whether the resource ID refers to a "galleries" …

Add Compute Gallery images support

---

src/agent/Cargo.lock

#1482 Bump futures from 0.3.17 to 0.3.18 in /src/agent
#1479 Bump futures-util from 0.3.17 to 0.3.18 in /src/agent
#1475 Bump futures from 0.3.17 to 0.3.18 in /src/proxy-manager

Combined futures dependabot changes from PR's:

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

Bump serde_json from 1.0 68 to 1.0.72 in /src/proxy-manager
Bump serde_json from 1.0.68 to 1.0.72 in /src/agent
This PR combines individual dependabot PR's:
#1481 
#1483 

Bump serde_json from 1.0.68 to 1.0.72 

---

src/agent/Cargo.lock
src/deployment/deploy.py

I introduced a bug when I implemented the new function for assigning user access. If a user tried upgrading an instance with an SP, then deployment would fail when this function was called due to lack of permissions.
Changes to deploy.py assign_user_access()
check-pr run. 
Deploy with a service principal.

[Bug Fix] Adding Check for SP During User Role Assignment.

---

src/agent/Cargo.lock

Reverting PR #1492 , which combines dependabot changes to futures crates. This revert downgrades futures crates' versions to 0.3.17.
This reverts commit 9ee0e8d6c8e26cbfbefbf2644f6473269f7f63c3.
Reverting PR #1492 , which combines dependabot changes to futures crates. This revert downgrades futures crates' versions to 0.3.17 to remove issues from changes made to FuturesUnordered in futures crates in version 0.3.18.

Downgrade futures crates to 0.3.17 with revert

---

.github/workflows/ci.yml
src/api-service/requirements-dev.txt
src/cli/requirements-lint.txt
src/pytypes/requirements-lint.txt
src/utils/add-corpus-storage-accounts/requirements-lint.txt
src/utils/check-pr/requirements-lint.txt

With latest release of mypy it broke the build.
See following github items for details:
https://github.com/samuelcolvin/pydantic/issues/3528
https://github.com/python/mypy/issues/6617#issuecomment-892438903
https://github.com/samuelcolvin/pydantic/pull/3175#issuecomment-914897604

pin mypy to 0.910

---

src/agent/coverage/src/debuginfo.rs

Remove the currently-unused `DebugInfo.session` field to ease `async` usage.
The removed field has type [`ObjectDebugSession`](https://docs.rs/symbolic/latest/symbolic/debuginfo/enum.ObjectDebugSession.html), which is not `Send`. This is problematic in an `async` context. We could work around it, and probably even craft a `Send` wrapper type (which would require judicious use of `unsafe`). However, in our coverage task, we don't actually use debug sessions at all. In the future, we can still easily get them on-demand from `Object` values (which we do cache). So, just remove the cached session field until we actually need it.

Don't cache debuginfo sessions

---

src/agent/coverage/src/debuginfo.rs

On Windows, when we search for PDB debuginfo for PEs, use our existing `dbghelp`-based mechanism, which uses the symbol search path.
Also, if we don't find out, try to use the PE, instead of failing immediately. If it lacks debuginfo (it usually will), we'll now return `None` instead of failing, which is our intended semantics.
Tested locally using the `src-cov` example against a binary. I tested 4 cases:
1. No PDB available at all
2. PE-described absolute-path PDB in original compilation directory, no other copies
3. PDB in same dir as PDB (only)
4. PDB in non-PE dir, included in `_NT_SYMBOL_PATH`
As expected, the PDB is not found in (1), and is found in (2) - (4). Not-committed debug logging verified that the resolved PDB was the expected one in each case. When found, source coverage is …

Use symbol path when searching for PDBs for source coverage

---

src/api-service/__app__/onefuzzlib/extension.py

We are required to enable autoconfig for AzSecPack deployments. These changes included the addition of the relevant property. 
Changes to the AzSecPack extensions in extension.py
check-pr.py
manual deployments and tests.

Adding AutoConfig Properties to AzSecPack Extensions

---

src/cli/onefuzz/azure_identity_credential_adapter.py
src/cli/onefuzz/cred_wrapper.py
src/cli/onefuzz/debug.py
src/cli/requirements.txt
src/deployment/deploy.py
src/deployment/deploylib/data_migration.py
src/deployment/deploylib/set_admins.py
src/deployment/requirements.txt
src/utils/add-corpus-storage-accounts/add-corpus-storage-account.py
src/utils/add-corpus-storage-accounts/requirements.txt
src/utils/check-pr/requirements.txt

Had to include `cred_wrapper.py` see app-insights Python package does not handle newer authentication APIs. see [azure sdk authentication docs](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-hosted-applications)

bump azure-cli and azure-cli-core to 2.31.0

---

docs/webhook_events.md
src/api-service/__app__/onefuzzlib/azure/vm.py
src/api-service/__app__/onefuzzlib/azure/vmss.py
src/api-service/__app__/onefuzzlib/extension.py
src/api-service/__app__/onefuzzlib/proxy.py
src/api-service/__app__/onefuzzlib/repro.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py
src/api-service/__app__/scaleset/__init__.py
src/pytypes/onefuzztypes/models.py

For our prod instance to run the most up-to-date version of AzSecPack, we need to be able to add tags to the VMSS and VMs running in an instance. I've added two new instance_config fields that allow instance operators to specify vmss and vm tags. 
Changes to: 
- vm.py
- vmss.py
- models.py
Running check-pr and manual tests that include new instance_config tags.

Adding new InstanceConfig value for VMSS & VM tags

---

src/agent/Cargo.lock
src/agent/input-tester/Cargo.toml
src/agent/onefuzz/Cargo.toml
src/agent/stacktrace-parser/Cargo.toml

Fixes cargo audit warning on sha2 0.10.0

Upgrade to sha2 0.10.1

---

src/agent/onefuzz-agent/src/tasks/coverage/generic.rs

In the coverage task, write a new `source-coverage.json` file to the `coverage` container, next to the existing `coverage.json`.
Consumers that subscribe to updates of this blob storage container will now need to make sure they check which blob was updated.
Closes #1378, #1380.

Emit source-line coverage reports in `coverage` task

---

src/agent/onefuzz-agent/src/tasks/coverage/generic.rs

Outputs coverage file as Cobertura XML format.
Continues work of outputting improved source coverage as file(s) alongside block coverage file. This work completes the integration of having a third file be outputted to the coverage container, this file being in Cobertura xml format. It calls the function that converts source coverage data to Cobertura format and outputs it as a file. This file will be able to be used as input in ReportGenerator tool.
A cobertura-coverage.txt file should be created in coverage container in Cobertura XML format with same data as source-coverage.json file.

Integrate Cobertura format and output as file in coverage container

---

src/agent/Cargo.lock
src/agent/onefuzz/Cargo.toml
src/agent/onefuzz/examples/test-input.rs

Add a new example binary ( `test-input`) to the `onefuzz` crate. This exercises the same code used in the `generic_generator` and `crash_report` tasks. It is useful for local validation of expected behavior of a target exe against an input.
This binary is not built by default, and does not need to be. It can be built locally from the `src/agent/onefuzz` directory via:
```
cargo build --examples
```
```
./test-input -h
```
```
onefuzz 0.1.0
USAGE:
test-input [FLAGS] [OPTIONS] --exe <exe> --input <input> --setup-dir <setup-dir>
FLAGS:
--check-asan-log
--check-asan-stderr
-h, --help                 Prints help information
--no-check-debugger
-V, --version              Prints version information
OPTIONS:
-e, --exe <exe>
-i, --input <input>
-o, --options <options>...
-s, --setup-dir …
```

Add `test-input` example

---

src/api-service/__app__/node/__init__.py
src/pytypes/onefuzztypes/models.py

The tuple type of Node.tasks is causing the following error when the field is deserialized 
```
WARNING:root:unable to normalize type f<class 'tuple'>
WARNING:root:unable to normalize type f<class 'tuple'>
WARNING:root:unable to normalize type f<class 'tuple'>
Traceback (most recent call last):
File "C:\temp\onefuzz\venv\Scripts\onefuzz-script.py", line 11, in <module>
load_entry_point('onefuzz', 'console_scripts', 'onefuzz')()
File "c:\work\onefuzz\src\cli\onefuzz\__main__.py", line 16, in main
return execute_api(Onefuzz(), [Endpoint, Command], __version__)
File "c:\work\onefuzz\src\cli\onefuzz\cli.py", line 591, in execute_api
output(result, args.format, expression)
File "c:\work\onefuzz\src\cli\onefuzz\cli.py", line 532, in output
result = json.dumps(result, indent=4, sort_keys=True) …
```

fix node serialization

---

src/integration-tests/integration-test.py
src/utils/check-pr/check-pr.py

Allow authority to be specified in check-pr.
This fixes the following error:
```
ERROR:integration:testing failed: Exception("error: invalid_request\n'AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: 26e81640-56cf-4300-bb04-7e19085dce00\r\nCorrelation ID: 456be707-73f0-4f0c-939d-98ef6bafa9e6\r\nTimestamp: 2022-02-02 21:13:06Z'")
ERROR:integration:traceback: Traceback (most recent call last):
ERROR:integration:traceback:   File "integration-test-artifacts/integration-test.py", line 1071, in test
ERROR:integration:traceback:     raise error
ERROR:integration:traceback:   File "integration-test-artifacts/integration-test.py", line 1057, in test
ERROR:integration:traceback:     self.cleanup( …
```

Allow authority to be specified in check-pr

---

.github/workflows/ci.yml

When `windows-latest` changes over to `windows-2019`, it will break the `build-integration-tests-windows` CI task.
Set the build image to a fixed version. When we update to `windows-2022`, we'll want to do so explicitly, and it will require updating the generated PowerShell script, which assumes certain Visual Studio versions and paths.

Used fixed Windows image for integration test build

---

src/api-service/__app__/onefuzzlib/azure/auto_scale.py
src/api-service/__app__/onefuzzlib/azure/log_analytics.py
src/api-service/__app__/onefuzzlib/azure/monitor.py
src/api-service/__app__/onefuzzlib/azure/queue.py
src/api-service/__app__/onefuzzlib/extension.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py
src/api-service/__app__/requirements.txt
src/deployment/azuredeploy.json

This PR creates an auto scale resource for scalesets that uses the pool work queue as the tirgger metric.
* These changes only affect new scalesets, existing scalesets will not be modified
* Scalesets that already have an auto scale resource associated with them will not be modified
* The autoscaling resource is disabled meaning scaleset behavior won't change
* In the interest of keeping this reviewable, hooking up scaling event diagnostics will be a follow up PR
1. Create a new scaleset
2. Find your new scaleset n azure portal
3. Under "Scaling", select the "JSON" tab
4. Verify there is 1 object under `.properties.profiles`
5. Verify `.properties.enabled == false`

Create autoscale resources for scaleset

---

src/agent/onefuzz/src/libfuzzer.rs

Force `-runs=1` when invoking in repro mode

---

src/agent/onefuzz-supervisor/src/setup.rs

Add a setup script-specific timeout of 59 minutes. This is just shorter than the service-side `NODE_EXPIRATION_TIME` which otherwise garbage collects nodes whose setup scripts are stuck or taking too long.
Ideally, the timeout would be user-configurable within some range. As-is, we'd only ever want to increase it, and doing so would require dynamically updating the service-side limit (which we'd probably want to revert to something short, after the setup script is done.
With this change, the high-level cause of the timeout is clear, instead of the closest error being something indirect, like "node reimaged during task execution".
Tested by creating a Linux `libfuzzer basic` job with a `setup.sh` that invokes `yes >/dev/null`. All task VMs got stuck in `setting_up`, then failed with an …

Add timeout to setup scripts

---

src/deployment/deploy.py

Remove use of deprecated `warn()` method on logger object.
Stops this warning on deployment:
```
/Users/anthonyshaw/projects/deploy.py:179: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn("unable to use built-in azcopy, using system install")
```

Remove use of deprecated `warn()` method on logger object

---

src/api-service/__app__/onefuzzlib/workers/scalesets.py
src/deployment/azuredeploy.json

Onefuzz Deployment role is not available in every tenant. We need to find a 'portable' role with the permissions we need to add auto-scale resources.

Remove dependency on onefuzz deployment role to unblock

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/dynamic-library/Cargo.toml
src/agent/dynamic-library/src/bin/dynamic-library.rs
src/agent/dynamic-library/src/lib.rs
src/agent/dynamic-library/src/windows.rs

Add a CLI tool and library code to debug missing dynamic library errors on Windows.
The implementation manually edits the registry [global flags for an image file](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags-overview) to temporarily enable [loader snaps](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/show-loader-snaps), runs the target under our custom debugger to collect the debug output strings, then parses them for informative loading errors. It does not depend on the presence of `gflags.exe`.
This detects both dynamic linking (and thus process startup) errors, as well as dynamic loading (`LoadLibrary`) errors. It can report multiple missing dynamically-linked libraries.
Towards #1706.

Add crate to debug missing dynamic libraries on Windows

---

src/agent/dynamic-library/src/bin/dynamic-library.rs
src/agent/dynamic-library/src/lib.rs
src/agent/dynamic-library/src/linux.rs
src/agent/dynamic-library/src/linux/ld_debug_output_missing.txt
src/agent/dynamic-library/src/linux/ld_debug_output_none_missing.txt
src/agent/dynamic-library/src/linux/ldd_output_missing_0.txt
src/agent/dynamic-library/src/linux/ldd_output_missing_1.txt
src/agent/dynamic-library/src/linux/ldd_output_missing_2.txt
src/agent/dynamic-library/src/linux/tests.rs
src/agent/dynamic-library/src/windows.rs

Add support for detecting for missing dynamic libraries on Linux, and extend the existing CLI tool.
This uses the `ldd` tool and the `LD_DEBUG` environment variable to enable `ld.so` debug logging. We could replace the use of `ldd` with `LD_TRACE_LOADED_OBJECTS` and target invocation, but I think the presence of `ldd` is a safe assumption.
Integration tested with the `linux-libfuzzer-dlopen` and `linux-libfuzzer-linked-library` example binaries. Verified that the CLI tool works as expected with 0, 1, or many missing shared libraries, both when linking at process startup or loading at runtime.

Add Linux dynamic library checks using `ldd`/`LD_DEBUG`

---

src/api-service/__app__/onefuzzlib/azure/auto_scale.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py
src/api-service/__app__/scaleset/__init__.py
src/cli/onefuzz/api.py
src/pytypes/onefuzztypes/models.py
src/pytypes/onefuzztypes/requests.py

This change introduces a few options related to auto scaling when creating a new scale set.
* The following options are added to `onefuzz scalesets create`
```
--min_instances MIN_INSTANCES
(default: 1)
--scale_out_amount SCALE_OUT_AMOUNT
(default: 1)
--scale_out_cooldown SCALE_OUT_COOLDOWN
(default: 10)
--scale_in_amount SCALE_IN_AMOUNT
(default: 1)
--scale_in_cooldown SCALE_IN_COOLDOWN
(default: 15)
```
* Added a new table `AutoScale`
* **Newly created auto scale resources are enabled by default**. This means after this PR is merged any newly created scale sets will have auto scale enabled by default
* Create a new scale set from cli by doing `onefuzz scalesets create test 3`
* Verify the scaleset is …

Adding auto scale via cli

---

src/ApiService/ApiService/ApiService.csproj
src/ApiService/ApiService/Program.cs
src/ApiService/ApiService/QueueNodeHearbeat.cs
src/ApiService/ApiService/model.cs
src/ApiService/ApiService/onefuzzlib/Nodes.cs
src/ApiService/ApiService/onefuzzlib/orm/CaseConverter.cs
src/ApiService/ApiService/onefuzzlib/orm/CustomConverterFactory.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs
src/ApiService/ApiService/onefuzzlib/orm/StorageProvider.cs
src/ApiService/ApiService/packages.lock.json
src/ApiService/Tests/OrmTest.cs

Add support for etag and timestamp
Introducing EntityBase

Starting migration of QueueNodeHearbeat

---

src/ApiService/Tests/OrmTest.cs
src/ApiService/Tests/Tests.csproj

re enable Nullable on the test project

---

src/ApiService/ApiService/Log.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/Program.cs
src/ApiService/ApiService/onefuzzlib/Events.cs
src/ApiService/ApiService/onefuzzlib/Queue.cs
src/ApiService/ApiService/onefuzzlib/Storage.cs
src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs

- Addin more injected types
- Fixing an issue with the log tracer where the same keys was added multiple time to the tags
- Removing UserInfo when writing events
- other bug fixes

Finishing implementation of SendEvent

---

src/agent/debugger/src/lib.rs
src/agent/win-util/src/lib.rs

Fixes the build in the face of a new clippy lint.
Proper follow-up captured in #1793.

Allow some safe functions with `HANDLE` arguments

---

src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs
src/ApiService/Tests/OrmTest.cs

Handles at least URI (and probably bunch of other cases)

handle more serialization/deserialization cases

---

src/agent/coverage/src/block/pe_provider.rs

When scanning for inline accesses to a SanCov table, if we hit a procedure-local disassembly error, only stop inline access search within that procedure. Log a warning, but continue scanning generally.
Closes #1795.

Continue inline access search on local error

---

src/agent/onefuzz/src/sanitizer.rs

- Add `LlvmSymbolizer` wrapper around validated paths to external `llvm-symbolizer` exes
- Pivot sanitizer environment variable generation on `LlvmSymbolizer`
- Set external symbolizer path in `TSAN_OPTIONS`
Closes #1770.

Set TSan options based on external symbolizer

---

src/agent/Cargo.lock
src/agent/onefuzz-agent/src/local/common.rs
src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
src/agent/onefuzz/Cargo.toml
src/agent/onefuzz/examples/dir-monitor.rs
src/agent/onefuzz/src/monitor.rs
src/agent/onefuzz/src/monitor/tests.rs
src/agent/onefuzz/src/syncdir.rs

Update `notify` to its latest stable preview release `5.0.0-pre.14`.
The latest `notify` release on `crates.io` is `4.0.17`. The 4.x series receives very occasional backports (the last one was a year ago), but it is not actively developed, and a `cargo audit` run uncovers many issues that are unlikely to be addressed. This upgrade lets us avoid problematic transitive dependencies, and align our direct dependency on `notify` to its actively-maintained major version.
By upgrading to the most-stable 5.x preview version, we also get to use the new `Watcher` API. This accepts any implementer of the new `EventHandler` trait, which includes closures. This lets us directly send (fallible) watcher events via the synchronous `UnboundedSender::send()` method, instead of having to shim the sync …

Upgrade to latest stable `notify` preview

---

src/agent/onefuzz-agent/src/local/common.rs
src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
src/agent/onefuzz/examples/dir-monitor.rs
src/agent/onefuzz/src/monitor.rs
src/agent/onefuzz/src/monitor/tests.rs
src/agent/onefuzz/src/syncdir.rs

Use a simpler and less error-prone API for `DirectoryMonitor`.
- Make `new()` ctor async, set watch on construction
- Remove `start()`, validate that target path is a directory in `new()`
Closes #1864.

Switch to misuse-resistant smart constructor

---

.github/workflows/ci.yml

Update build action triggers to only build on either PR creation/reopen/push, or manual build triggering.
- Remove the `push` trigger for the "Build" action
- Add the `workflow_dispatch` trigger to the "Build" action, to [enable pre-PR manual workflow triggers](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#configuring-a-workflow-to-run-manually)
Closes #1871.

Don't trigger build on every push, enable manual trigger

---

.github/workflows/ci.yml

#1872 disabled triggering the "Build" action on pushes to the `main` branch, which we should preserve. Explicitly enable this.

Build on pushes to `main`

---

src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/Program.cs
src/ApiService/ApiService/QueueNodeHearbeat.cs
src/ApiService/ApiService/onefuzzlib/InstanceConfig.cs
src/ApiService/ApiService/onefuzzlib/JobOperations.cs
src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs
src/ApiService/ApiService/onefuzzlib/OnefuzzContext.cs
src/ApiService/ApiService/onefuzzlib/PoolOperations.cs
src/ApiService/ApiService/onefuzzlib/ProxyForwardOperations.cs
src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs
src/ApiService/ApiService/onefuzzlib/ReproOperations.cs
src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs
src/ApiService/ApiService/onefuzzlib/TaskOperations.cs
src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs
src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs

- Creating a OnefuzzContext object that contains most of our dependencies
- update some classes to use this object instead of direct dependencies

Introducing OnefuzzContext to prevent circular references

---

src/Dockerfile

use microsoft verified image rather than public one as a potential mitigation for supply chain attack

fix where we get base docker image from

---

CONTRIBUTING.md
contrib/deploy-onefuzz-via-azure-devops/deploy-onefuzz.yml
docs/getting-started.md
src/ApiService/ApiService/az-local.settings.json
src/deployment/deploy.py
src/utils/check-pr/README.md

- Making dotnet deployment the default, so python and dotnet functions will both be uploaded during an Azure deployment.
- Updating all 'function-core-tools' (Azure Functions CLI) references to V4 to match what's now required for deployment.
Updated:
CONTRIBUTING.md
src/deployment/deploy.py
src/deployment/ApiService/ApiService/az-local.settings.json
contrib/deploy-onefuzz-via-azure-devops/deploy-onefuzz.yml
src/ApiService/ApiService/az-local.settings.json
src/utils/check-pr/README.md
docs/getting-started.md

updating deploy.py to push dotnet by default

---

src/ApiService/ApiService/OneFuzzTypes/Enums.cs
src/ApiService/ApiService/TestHooks/NodeOperationsTestHooks.cs
src/ApiService/ApiService/onefuzzlib/orm/CustomConverterFactory.cs
src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs
src/ApiService/Tests/OrmTest.cs

Added a new Attribute to specify that an Enum should be serialized by value
closes #1894

Add the ability to serialize enums values

---

.github/workflows/ci.yml

A new version came out today and is causing the formatting break in the build release.
We decided to pin the release the version number.

pinning the version of dotnet to 6.0.202

---

src/agent/Cargo.lock

Fixes the build due to `0.10.x` being yanked for `x < 2`.
Related upstream PR: https://github.com/RustCrypto/traits/issues/979

Update patch version of `digest:0.10` dep

---

.github/workflows/ci.yml

When we tag a commit, it's useful to be able to get the build artifacts for our release process. 
#1929

When a tag is created, trigger a build.

---

src/agent/onefuzz/examples/dir-monitor.rs
src/agent/onefuzz/src/monitor.rs
src/agent/onefuzz/src/monitor/tests.rs

Allow the DirectoryMonitor to skip reporting directories. The default behavior is to continue reporting them so we don't change the behavior unexpectedly.
Tested with the `dir-monitor` example.

Allow ignoring directories

---

src/agent/dynamic-library/src/bin/dynamic-library.rs
src/agent/dynamic-library/src/linux.rs

On Linux, when calling `find_missing()`, include `LD_LIBRARY_PATH` if and only if the invoked `Command` explicitly sets some value for that variable. This ensures consistent search results, no matter the process environment of the calling context.
Closes #1827.
- Shared lib in `{setup_dir}` (passes no matter what, because we default to `LD_LIBRARY_PATH={setup_dir}`)
- Shared lib in `{setup_dir}/lib`, no `target_env` (fails)
- Shared lib in `{setup-dir}/lib`, with `--target_env LD_LIBRARY_PATH={setup_dir}/lib` (passes)

Include `LD_LIBRARY_PATH` iff set by command

---

docs/webhook_events.md
src/pytypes/onefuzztypes/models.py

This PR makes the following fields of the report optional
- tool_name
- tool_version
- onefuzz_version

Hotpatch to 5.4.0 to fix the report deserialization issue

---

src/agent/onefuzz-agent/data/fake-crash-report-old.json
src/agent/onefuzz-agent/src/tasks/report/crash_report.rs

Make onefuzz_version, tool_name, and tool_version optional

Allow old reports to be parsed

---

src/cli/onefuzz/api.py

The old `libfuzzer_coverage` task dumps binary sancov tables. Its output is not usable on its own. This task has been superseded by the generic `coverage` task (which produces actual modoffset and source line coverage).
Add a CLI warning if it is used, in preparation for removing it.
Manually tested by creating a `libfuzzer_coverage` task using the CLI.
Towards #1290.

Deprecate `libfuzzer_coverage` task

---

src/cli/onefuzz/backend.py
src/cli/onefuzz/cli.py
src/cli/onefuzz/ssh.py

Remove the vestigial and confusing `nsv` prefix from the backend logger.

Use consistent logger names

---

docs/how-to/coverage-filtering.md

Note that this feature is released and clarify current scope.

Update coverage filtering docs

---

src/agent/Cargo.lock
src/agent/onefuzz-agent/Cargo.toml

Fixes #1027.
Confirmed with `ldd` that there was, but is no longer, a dependency on `libssl.so`.

Remove transitive OpenSSL dependency

---

src/agent/dynamic-library/src/windows.rs

We ensured that the key exists for the target, but not the leaf `GlobalFlag` _value_. We tried to retrieve an existing value and update just [`FLG_SHOW_LDR_SNAPS`](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/show-loader-snaps), but somehow missed the base case in manual testing.
Fixes #1826.
- Zero-initialize `GlobalFlag` registry values as needed
- Update an internal error type for easier debugging
Manually tested by creating jobs using `windows-libfuzzer-linked-library` and `windows-libfuzzer-load-library` tasks, but with one DLL dependency removed from the setup dir. Both failed as expected with the descriptive error:
> `Error: fuzzer does not respond to '-help=1'. missing shared libraries: bad.dll.`

Ensure `GlobalFlag` reg value is initialized for target

---

src/deployment/azuredeploy.bicep
src/deployment/bicep-templates/function-settings-disabled-apps.bicep
src/deployment/bicep-templates/function-settings.bicep
src/deployment/deploy.py

This adds app settings for all dotnet and python functions to automatically disable (AzureWebJobs.$FUNCTION.Disabled=1) all dotnet functions and enable all python functions in their corresponding function apps
To enable dotnet functions at deployment time, deploy.py was updated with an argument '--enable_dotnet' that accepts a space separated list of <del>dotnet</del> python functions to disable while enabling the dotnet function of the same name (except pascal cased names for dotnet vs python snake cased names)
example: 
```bash
./deploy.py --enable_dotnet tasks webhooks pool
```
This would enable the Tasks, Webhooks, and Pool functions in dotnet and turn these off in python
src/deployment/bicep-templates/function-settings-disabled-apps.bicep
src/deployment/azuredeploy.bicep …

adding function app settings bicep template and updating deploy.py 

---

src/agent/Cargo.lock
src/agent/onefuzz-agent/Cargo.toml
src/agent/onefuzz-agent/src/local/tui.rs
src/agent/onefuzz-agent/src/tasks/task_logger.rs
src/agent/onefuzz-telemetry/Cargo.toml
src/agent/onefuzz-telemetry/src/lib.rs

Adds timestamp to agent tracing log output.
* Rename `LogEvent` -> `LoggingEvent`
* Create `LogTrace` and `LogEvent` structs to organize necessary logging info https://github.com/microsoft/onefuzz/pull/1972/files#diff-52c53d4179505ba0dd3f46e2707afeb66f5208e6138b52159fd48134af41a73fR340-R356
* All agent logs now prepend the UTC timestamp
* Test to validate the behavior
Ran check-pr, checked the blob logs and the AI logs.

Add timestamp to agent log

---

contrib/deploy-onefuzz-via-azure-devops/.pylintrc

Remove R0201 as it is breaking the build due to:
```
.pylintrc:1:0: E0012: Bad option value for --disable. Don't recognize message R0201. (bad-option-value)
```
No code currently violates this lint.
See if build is successful now.

Update .pylintrc to fix build error

---

.github/workflows/ci.yml
src/ApiService/.config/dotnet-tools.json

Collect .NET coverage during build and display it in GitHub Summary.
Add the `reportgenerator` tool, run it after tests.
Run workflow and make sure it works.
See example coverage output here: https://github.com/microsoft/onefuzz/actions/runs/2458088617

Collect .NET coverage info

---

docs/getting-started.md

`deploy.py` must be chmodded as it doesn't have the right permissions when unzipped.

Update Getting Started instructions

---

.github/workflows/sync-issue-to azure-devops-work-item.yml

This workflow will sync github issues in this repository with work items in ADO giving us one place to manage our priorities. 
This won't affect the project code/src in anyway.

Add workflow to sync gh issues with ado work items.

---

README.md

Small change to link to somewhere useful instead of the SVG image.

Link build status shield to Github Actions page

---

.github/workflows/ci.yml
src/ci/agent.sh

Attempt to speed up CI builds:
1. Disable incremental builds when using `sccache` (incremental can't be cached)
2. Set `--locked` on all invocations of cargo
<table>
<thead>
<tr>
<th>Before</th>
<th>After (old cache)</th>
<th>After (new cache)</th>
<th>Latest on branch</th>
</tr>
</thead>
<tbody>
<tr>
<td>
```
+ sccache --show-stats
Compile requests                    767
Compile requests executed           588
Cache hits                           31
Cache hits (C/C++)                   31
Cache misses                        557
Cache misses (Rust)                 557
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors …
```

Attempt to improve sccacheability

---

.devcontainer/devcontainer.json

Enable Roslyn analyzers and `.editorconfig` support by default in devcontainer.

Devcontainer: Set some default Omnisharp options

---

src/agent/Cargo.lock
src/agent/onefuzz-agent/Cargo.toml
src/agent/onefuzz-agent/src/coordinator.rs
src/agent/onefuzz-agent/src/debug.rs
src/agent/onefuzz-agent/src/main.rs

Mostly a maintenance update (dependabot was trying to do this and failing), but it does have a small improvement in that the `debug node_event state_update` help:
```console
$ target/debug/onefuzz-agent debug node_event state_update --help
onefuzz-agent-debug-node_event-state_update 0.1.0
USAGE:
onefuzz-agent debug node_event state_update <state>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
ARGS:
<state>    
```
Now displays the applicable enum values:
```console
$ target/debug/onefuzz-agent debug node_event state_update --help
onefuzz-agent-debug-node_event-state_update 
USAGE:
onefuzz-agent debug node_event state_update <STATE>
ARGS:
<STATE>    [possible values: init, free, setting-up, rebooting, ready, busy, done]
OPTIONS:
-h, --help …
```

Update `onefuzz-agent` to clap 3

---

.devcontainer/Dockerfile

This will give (e.g.) git branch name completion, among many other things.

Add bash-completion to devcontainer image

---

src/ApiService/ApiService/OneFuzzTypes/ReturnTypes.cs

Add `MemberNotNullWhen` attributes to the various `Result` types.
This makes it easier to use these types since checking `IsOk` will tell the compiler that the `OkV` is non-null.

Add null analysis attributes to result types

---

src/ApiService/.editorconfig

Set up a naming rule in `.editorconfig` for private fields to start with an underscore. This ensures that OmniSharp will generate the desired names by default.

Editorconfig underscores rule

---

.github/workflows/ci.yml
src/ApiService/ApiService/ApiService.csproj
src/ApiService/ApiService/Info.cs
src/ApiService/ApiService/OneFuzzTypes/Responses.cs
src/ApiService/ApiService/Program.cs
src/ApiService/ApiService/ServiceConfiguration.cs
src/ApiService/ApiService/onefuzzlib/Containers.cs
src/ApiService/ApiService/onefuzzlib/EndpointAuthorization.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs
src/ApiService/Tests/Fakes/TestContext.cs
src/ApiService/Tests/Fakes/TestCreds.cs
src/ApiService/Tests/Fakes/TestEndpointAuthorization.cs
src/ApiService/Tests/Fakes/TestHttpRequestData.cs
src/ApiService/Tests/Fakes/TestServiceConfiguration.cs
src/ApiService/Tests/Functions/AgentEventsTests.cs
src/ApiService/Tests/Functions/InfoTests.cs
src/ApiService/Tests/Functions/_FunctionTestBase.cs
src/ApiService/Tests/Integration/AzureStorage.cs
src/ApiService/Tests/Integration/AzuriteStorage.cs

Adds implementation of the `info` function. 
Added support for blobs in the function integration test stuff.
Simplified usage of integration test classes by removing the account name parameter.
* ~~Requires documentation to be updated~~
* ~~I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx~~

Implement `info` Function in C#

---

src/ApiService/ApiService/Node.cs
src/ApiService/ApiService/OneFuzzTypes/Events.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/OneFuzzTypes/Requests.cs
src/ApiService/ApiService/OneFuzzTypes/Responses.cs
src/ApiService/ApiService/OneFuzzTypes/ReturnTypes.cs
src/ApiService/ApiService/OneFuzzTypes/Validated.cs
src/ApiService/ApiService/TestHooks/NodeOperationsTestHooks.cs
src/ApiService/ApiService/TestHooks/PoolOperationsTestHooks.cs
src/ApiService/ApiService/UserCredentials.cs
src/ApiService/ApiService/onefuzzlib/EndpointAuthorization.cs
src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/NsgOperations.cs
src/ApiService/ApiService/onefuzzlib/PoolOperations.cs
src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs
src/ApiService/ApiService/onefuzzlib/Scheduler.cs
src/ApiService/ApiService/onefuzzlib/VmssOperations.cs
src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs
src/ApiService/ApiService/onefuzzlib/orm/Queries.cs
src/ApiService/Tests/Fakes/TestContext.cs
src/ApiService/Tests/Fakes/TestEndpointAuthorization.cs
src/ApiService/Tests/Fakes/TestServiceConfiguration.cs
src/ApiService/Tests/Fakes/TestUserCredentials.cs
src/ApiService/Tests/Functions/AgentEventsTests.cs
src/ApiService/Tests/Functions/InfoTests.cs
src/ApiService/Tests/Functions/NodeTests.cs
src/ApiService/Tests/Functions/_FunctionTestBase.cs
src/ApiService/Tests/OrmModelsTest.cs
src/ApiService/Tests/OrmTest.cs
src/ApiService/Tests/ValidatedStringTests.cs

1. Ports the `node` function from Python to C#.
2. Adds a missing authentication check.
3. Add validated string type `PoolName` for consistency with Python version.
* ~~Requires documentation to be updated~~
* ~~I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx~~

Implement the `node` C# function

---

src/agent/Cargo.lock
src/agent/onefuzz-telemetry/Cargo.toml
src/agent/onefuzz-telemetry/src/lib.rs

#2033 appears to be breaking agent since we are getting nested tokio runtimes. Revert it!

Revert #2033

---

src/ApiService/ApiService/onefuzzlib/ReproOperations.cs
src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs
src/ApiService/Tests/StatefulOrmTests.cs

`StatefulOrm` performs checks in the static constructor. Make sure that all these checks pass.
Currently `ReproOperations` and `ScalesetOperations` do not pass:
```
State transition method 'Stopping' in 'ReproOperations' does not have the correct signature.
Expected 'System.Threading.Tasks.Task`1[Microsoft.OneFuzz.Service.Repro] Invoke(Microsoft.OneFuzz.Service.Repro)' 
actual 'System.Threading.Tasks.Task Stopping(Microsoft.OneFuzz.Service.Repro)' 
```
```
State transition method 'Halt' in 'ScalesetOperations' does not have the correct signature.
Expected 'System.Threading.Tasks.Task`1[Microsoft.OneFuzz.Service.Scaleset] Invoke(Microsoft.OneFuzz.Service.Scaleset)'
actual 'System.Threading.Tasks.Task Halt(Microsoft.OneFuzz.Service.Scaleset)' 
```

Add test for StatefulOrm static constructor

---

src/ApiService/Directory.Build.props

Treat all warnings as errors, so that local development matches the CI build.

Treat warnings as errors

---

src/agent/onefuzz/src/monitor.rs

This PR addresses the racing condition where a file could be discovered by the file monitor but disappear before the it reads its metadata.

Fix Racing condition in monitor.rs

---

src/api-service/__app__/download/__init__.py
src/api-service/__app__/onefuzzlib/azure/containers.py

Fixes an issue where the job logs sas token could expire before the job was scheduled

Make the log sas url last as long as the job duration

---

.github/workflows/ci.yml

Some CI builds are getting spurious failures trying to clone the radamsa repository.
We don't need to build this every time so cache the built artifacts.

Cache radamsa builds in CI

---

src/ApiService/ApiService/onefuzzlib/Containers.cs

Make the log sas url last as long as the job duration
porting the code change introduced in #2116 to the C# code

Porting divergent code introduced in #2116

---

src/ApiService/ApiService/Program.cs

Make HostBuilder Async

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Using `3.8` for the Python devcontainer feature version means it builds from source every time the devcontainer is rebuilt, which is very slow. Using `os-provided` will give us a recent enough version (3.10).
Also install `python-is-python3` so that the bare `python` command points to Python 3 (our scripts seem to expect this).

Use 'os-provided' Python for devcontainer

---

.github/workflows/ci.yml
src/agent/LibFuzzerDotnetLoader/LibFuzzerDotnetLoader.csproj
src/agent/LibFuzzerDotnetLoader/Program.cs
src/ci/dotnet-fuzzing-tools.ps1
src/ci/dotnet-fuzzing-tools.sh

To support .NET fuzzing, we want an end-user API that requires as little tool expertise as possible, but is effective and coverage-driven. These preliminary changes to the build are not yet used, but will be shortly by upcoming tasks. The new tools are:
- SharpFuzz's CLI tool for instrumenting user-submitted assemblies with coverage feedback. This does not appear to publishable as a self-contained executable at the moment. This is a CLI that simply accepts a path to an uninstrumented assembly. Its presence is not required to use `libfuzzer-dotnet`/`LibFuzzerDotnetLoader`, but will be applied to user assemblies in a setup stage.
- `libfuzzer-dotnet` (for both Linux and Windows), to enable using LibFuzzer with SharpFuzz instrumentation. This is actually a specially-parameterized native …

Import `LibFuzzerDotnetLoader`, build .NET fuzzing tools

---

.github/workflows/ci.yml

The agent does not actually run on `macos` as a lot of the functionality is stubbed out.

Disable `macos` build for agent

---

src/agent/coverage/examples/coverage.rs
src/agent/coverage/examples/elf_sancov_tables.rs
src/agent/coverage/examples/pdb_sancov_tables.rs
src/agent/coverage/examples/src-cov.rs
src/agent/dynamic-library/src/bin/dynamic-library.rs
src/agent/onefuzz-agent/src/worker.rs
src/agent/onefuzz-task/src/managed/cmd.rs
src/agent/onefuzz/examples/memory.rs
src/agent/onefuzz/src/input_tester.rs
src/agent/onefuzz/src/libfuzzer.rs
src/agent/onefuzz/src/machine_id.rs
src/agent/onefuzz/src/memory.rs
src/agent/onefuzz/src/monitor.rs

Remove stubbed support for macOS builds

---

src/ApiService/ApiService/ApiService.csproj
src/ApiService/ApiService/OneFuzzTypes/Events.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/Program.cs
src/ApiService/ApiService/TestHooks.cs
src/ApiService/ApiService/TimerProxy.cs
src/ApiService/ApiService/onefuzzlib/Containers.cs
src/ApiService/ApiService/onefuzzlib/Network.cs
src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs
src/ApiService/Tests/OrmModelsTest.cs
src/ApiService/Tests/OrmTest.cs

- fixed behavior of Container.SaveBlob (file was not being overwritten)
- added support for default value in the entity converter
- fix scaleset size data type
- added initialization of Subnet
- renamed TestHook Info to _Info to prevent clashing of name function name
- added target framework to ApiServiceProject to help local debugging

Fix execution of TimerProxy

---

src/ApiService/ApiService/onefuzzlib/JobOperations.cs
src/ApiService/ApiService/onefuzzlib/TaskOperations.cs

The state filter from the original python code was omitted when porting this logic

Include state filter when searching for expired jobs and tasks

---

src/agent/LibFuzzerDotnetLoader/LibFuzzerDotnetLoader.csproj
src/agent/LibFuzzerDotnetLoader/Program.cs

- Add logging
- Catch terminal exceptions and log as errors before re-throwing
- Nest some exceptions
- Warn when falling back to non-zero cost delegate for legacy compat
Closes #2129.

Add logging to `LibFuzzerDotnetLoader`

---

src/agent/debugger/src/breakpoint.rs
src/agent/win-util/src/pipe_handle.rs
src/agent/win-util/src/process.rs

Closes #1595. Leaving one instance of `allow(clippy::uninit_vec)` in `pipe_handle.rs` as it is more difficult to remove. (Maybe there's  another crate we could use for pipes?)
To satisfy clippy, instead of creating the vec and then resizing it straight away (exposing uninitialized data), write into the `spare_capacity_mut()` (which is `&mut [MaybeUninit<_>]`) and then resize it afterwards.

Remove some allow(clippy::uninit_vec)

---

src/deployment/azuredeploy.bicep
src/deployment/bicep-templates/autoscale-settings.bicep
src/deployment/bicep-templates/operational-insights.bicep
src/deployment/bicep-templates/server-farms.bicep

The scaleset policy was set too low so we are updating it. Additionally, we are enabling the autoscaling diagnostic settings. 

Update Function Scaling Policy and Diagnostic Settings.

---

.github/workflows/ci.yml
src/ci/rust-prereqs.sh

By default we get whatever Rust version is installed in the Github Actions image. Pin it to latest Rust so it doesn't change unless we want it to.

Pin Rust to 1.62

---

src/pytypes/onefuzztypes/models.py
src/pytypes/onefuzztypes/requests.py

`check-pr` failed during setup with:
```
1 validation error for AutoScale min ensure this value is greater than or equal to 1
```
Possibly due to #2112; needed a server-side change to match.

Allow autoscale with a minimum of 0

---

src/api-service/__app__/onefuzzlib/workers/nodes.py

Python service would crash (`KeyError`) if `ONEFUZZ_ALLOW_OUTDATED_AGENT` was not set.

Use .get instead of lookup on `os.environ`

---

src/ApiService/ApiService/AgentCanSchedule.cs
src/ApiService/ApiService/AgentEvents.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/OneFuzzTypes/Requests.cs
src/ApiService/ApiService/ServiceConfiguration.cs
src/ApiService/ApiService/TestHooks/NodeOperationsTestHooks.cs
src/ApiService/ApiService/onefuzzlib/Creds.cs
src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/Scheduler.cs
src/ApiService/ApiService/onefuzzlib/ShrinkQueue.cs
src/ApiService/ApiService/onefuzzlib/VmssOperations.cs
src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs
src/ApiService/IntegrationTests/Fakes/TestServiceConfiguration.cs
src/ApiService/Tests/RequestsTests.cs
src/api-service/__app__/agent_registration/__init__.py
src/api-service/__app__/onefuzzlib/azure/creds.py
src/api-service/__app__/onefuzzlib/extension.py
src/api-service/__app__/pool/__init__.py
src/deployment/deploy.py

Enable the .NET functions for the agent by sending the agent the URI for the `-net` service.
Also fix some things causing failures when using the .NET functions (`CouldShrinkScaleset` was not implemented).
Improve error handling around table serialization/deserialization, fix an issue with int64/long mismatch between Python & C# code.
----
For `check-pr` testing:
1. There's a new parameter `enable_dotnet` which maps directly to the `--enable_dotnet` switch on `deploy.py`.
2. If you put `agent` there, all the `agent_*` functions will be enabled for .NET and disabled for Python.
3. If `agent_can_schedule` is disabled on the Python side, it will automatically tell the agent to use the .NET functions.
So to test the .NET agent functions, do a `check-pr` run with `enable_dotnet` set to `agent` …

Enable .NET functions in `check-pr` for Agent-specific functions

---

src/integration-tests/integration-test.py

This will allow testing client-facing .NET Functions during integration tests (`check-pr`).

Add support for dotnet_endpoint/dotnet_functions to integration-test.py

---

src/ApiService/ApiService/onefuzzlib/JobOperations.cs

The state transition Init was missing from the port of JobOperations

Add missing job state transition

---

src/ApiService/ApiService/Functions/NodeAddSshKey.cs
src/ApiService/ApiService/OneFuzzTypes/Requests.cs
src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/TaskOperations.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs

migrate add_node_ssh_key

---

src/deployment/deploy.py

This will allow the service to be backward compatible with older version of the agent and the cli when pushing new C# function to prod

Keep both  C# and  python http functions active when deploying

---

src/agent/onefuzz-task/src/local/libfuzzer.rs
src/agent/onefuzz-task/src/local/libfuzzer_fuzz.rs
src/agent/onefuzz-task/src/tasks/config.rs
src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer.rs
src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer/common.rs
src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer/generic.rs

Abstract the existing `libfuzzer_fuzz` task implementation. This is done in a way that will support introducing variant `libfuzzer_fuzz` task types that have extra config and do special process setup for certain kinds of LibFuzzer targets (i.e. `libfuzzer-dotnet`). 
Without changing task behavior, use the abstracted API to express the _existing_ task via the `GenericLibFuzzer`, which has no special additional config.

Factor out generic libfuzzer task

---

src/ApiService/ApiService/Program.cs
src/ApiService/ApiService/onefuzzlib/Extension.cs
src/ApiService/ApiService/onefuzzlib/ImageOperations.cs
src/ApiService/ApiService/onefuzzlib/OnefuzzContext.cs
src/ApiService/ApiService/onefuzzlib/Reports.cs
src/ApiService/ApiService/onefuzzlib/VmExtensionWrapper.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs
src/ApiService/IntegrationTests/Fakes/TestContext.cs

Related to migrating `timer_repro`.
Highlights of changes:
* Added `ImageOperations` which is used for working with VM images.
* Made generic wrapper type over `VirtualMachineScaleSetExtensionData` and `VirtualMachineExtensionData`. We use the same extensions (and same extension properties) for both and since I can't add a shared interface between the types ( and instead of duplicating the extension configuration functions), I created `VMExtensionWrapper`.
* Fixed some bugs in the existing extensions functions (ex: making sure our types are serialized as Azure expects, a couple of missing `await`s)

Add extensions functionality for C# refactor

---

src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer/common.rs
src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer/generic.rs
src/agent/onefuzz-task/src/tasks/merge/libfuzzer_merge.rs
src/agent/onefuzz-task/src/tasks/report/libfuzzer_report.rs
src/agent/onefuzz/src/libfuzzer.rs

Modify the `LibFuzzer` struct to own its environment and option data. This enables passing copies of locally-mutated env/options structs in implementers of `LibFuzzerType::from_config()`. No functional changes.

Remove lifetime param from `LibFuzzer`

---

src/agent/onefuzz-task/src/tasks/config.rs
src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer.rs
src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer/common.rs
src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer/dotnet.rs
src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer/generic.rs

Add a new `libfuzzer_dotnet_fuzz` task to the agent.
This task has a config which is an extension to the `libfuzzer_fuzz` with 3 extra parameters: `target_assembly`, `target_class`, and `target_method`. At runtime, it uses the new `LibFuzzerType::extra_setup()` hook to to instrument the `target_assembly` for coverage feedback using SharpFuzz, and generates `libfuzzer-dotnet`-based fuzzer invocations of `LibFuzzer`. These use `LibFuzzerDotnetLoader` as the `--target_path` arg for `libfuzzer-dotnet`, and sets the env vars that tell `LibFuzzerDotnetLoader` what to fuzz.

Add `libfuzzer_dotnet_fuzz` task to agent

---

src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs

During the original refactor, I'd left out a function call that properly queues webhook events. Updating to fix. 
Manual validation: 
- Deploying an instance
- Enabling csharp timerTasks
- creating a webhook for job_created, job_stopped, task_failed
- deployed a job
- confirmed webhooks were sent for above events

Fix Queue Issue for WebhookOperations.

---

src/api-service/__app__/onefuzzlib/azure/auto_scale.py
src/api-service/__app__/onefuzzlib/azure/vmss.py
src/api-service/__app__/onefuzzlib/workers/scalesets.py
src/deployment/azuredeploy.bicep

Auto scale can prevent scalesets from shutting down by continuing to spin up nodes even though the scale set is in shutdown state.
* [*] Tests added/passed
When a scale set enters the shutdown state, onefuzz will do the following:
* Replace all existing auto scale rules with a single scale in rule that will always evaluate to `True` and will scale in 1 node at a time
* If no existing auto scale resources are configured for the scaleset, skip it
Since we remove all scale out rules, new nodes will never be created regardless of whether there continues to be work in the pool's queue (effectively isolating the scale set from the pool).
Since the scale set is in shutdown state, nodes can no longer be assigned work. Nodes that are not assigned …

Adjust auto scale to scale down nodes on shutdown

---

src/ApiService/ApiService/Log.cs
src/ApiService/ApiService/Program.cs

This should fix our OOM Exceptions caused by initializing telemetry for every function invocation.
* Makes the log sinks singletons
* `LogTracer` remains scoped since it has "single threaded only" functions (`ReplaceCorrelationId`, `AddTags`)
1. Run .net functions locally
2. Validate telemetry is showing up in App Insights in a dev instance.

Make log sinks a singleton

---

src/ApiService/ApiService/OneFuzzTypes/Events.cs
src/ApiService/Tests/EventsTests.cs

Added a new attribute to associate  the enum to the event class

Convert the remaining events to the C#

---

src/api-service/__app__/onefuzzlib/workers/scalesets.py

Because timer_workers runs every minute, it errors out when it checks for an autoscale profile for a scaleset that's still in init, i.e. it hasn't created a scaling profile yet. 
With this change, sync will only happen when the scaleset is running. 

Fixing Scaleset State Check.

---

src/ApiService/ApiService/onefuzzlib/VmExtensionWrapper.cs

`Settings` and `ProtectedSettings` are required properties of VM Extensions but not all of our extension configurations need to set additional settings. In those cases, it's OK to create an empty dictionary.
* Don't throw if `Settings`/`ProtectedSettings` is not set
* Provide a default instead
* TODO: Validate in check-pr

Provide a default for vm extension settings

---

src/ci/agent.sh
src/ci/proxy.sh

The `ansi_term` crate is unmaintained, as described by the INFO-level advisory [RUSTSEC-2021-0139](https://rustsec.org/advisories/RUSTSEC-2021-0139.html).
Allow continued use of it for now, and ignore the advisory when invoking `cargo audit`.

Ignore info advisory about unmaintained `ansi_term` crate

---

src/cli/onefuzz/templates/__init__.py

`JobHelper.check_current_job()` currently always reports a successful status because it compares state enums with string literals, which will never succeed (confusingly).
In addition, by default `self.onefuzz.tasks.list` will only list active tasks (excluding ones that are in a shutting down state).
This simply removes string literal comparisons in favor of lists returned by the state object itself.
Unsure - I don't know if there's any commands that can easily be ran to check this functionality.
This should be a simple enough code review.

Properly compare job/task state enums in `JobHelper.check_current_job()`

---

src/ApiService/ApiService/onefuzzlib/Queue.cs

`CreateIfNotExistsAsync` is documented as returning `null` if the queue already exists:
```csharp
// Returns:
//     If the queue does not already exist, a Azure.Response describing the newly created
//     queue. If the queue already exists, null.
```
To be investigated: why did we not hit this earlier? Why did null reference checking not trigger here?

Fix NullReferenceException in CreateQueue

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/ci.yml

Addresses two things with the devcontainer:
- We want Rust 1.63, since we are pinned to that version now. I couldn't get this version to work with the devcontainer "features" so install it using rustup instead.
- The `dotnet` install was in a broken state due to a mix of Canonical/MS packages (see [here](https://github.com/dotnet/sdk/issues/27129)). The `dotnet6` package is included with Ubuntu now, so install it directly using `apt` instead of via the feature which fetched it from the MS package repository.

Devcontainer updates

---

src/ApiService/ApiService/Functions/Jobs.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/onefuzzlib/Config.cs
src/ApiService/ApiService/onefuzzlib/Scheduler.cs
src/api-service/__app__/jobs/__init__.py

- logging a warning in C# instead of an exception just like the [original code ](https://github.com/chkeita/onefuzz/blob/b2399c45710b52160b994e429fe3393a292da8be/src/api-service/__app__/onefuzzlib/tasks/config.py#L289)
- Fix the logic of creation of jobs. Only save once to avoid the job being picked up by the scheduler before it is ready

Only save the job once when creating it

---

src/api-service/__app__/onefuzzlib/azure/creds.py
src/deployment/azuredeploy.bicep
src/deployment/bicep-templates/function-settings.bicep
src/deployment/deploy.py

Add an explicit `USE_DOTNET_AGENT_FUNCTIONS` setting to Python service, instead of relying on whether or not functions are enabled/disabled.
We now run the Python & C# functions side-by-side so this wasn’t taking effect.

Add `--use_dotnet_agent_functions` to `deploy.py` and Python service

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

ARG needs to be after the FROM or it isn't "visible" later on.
Also, the `rust-analyzer` extension has a new ID.

Devcontainer Dockerfile fixes

---

src/ApiService/ApiService/Functions/Scaleset.cs
src/ApiService/ApiService/Functions/TimerProxy.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/onefuzzlib/Auth.cs
src/ApiService/ApiService/onefuzzlib/Extension.cs
src/ApiService/ApiService/onefuzzlib/IpOperations.cs
src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs
src/ApiService/ApiService/onefuzzlib/ReproOperations.cs
src/ApiService/ApiService/onefuzzlib/VmOperations.cs
src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs
src/integration-tests/integration-test.py

porting the proxy state machine

---

src/ApiService/ApiService/Functions/Info.cs
src/ApiService/ApiService/ServiceConfiguration.cs
src/ApiService/ApiService/onefuzzlib/ReproOperations.cs

.NET code was not getting the correct version from `ServiceConfiguration.OneFuzzVersion` as that expected to read it from the config. It should be read from the assembly attributes instead, but I still allow it to be overridden here.

Fix ServiceConfiguration.OneFuzzVersion

---

src/ApiService/ApiService/ApiService.csproj
src/ApiService/ApiService/Log.cs
src/ApiService/ApiService/Program.cs
src/ApiService/ApiService/packages.lock.json
src/ApiService/IntegrationTests/packages.lock.json
src/ApiService/Tests/packages.lock.json

At the moment we do not have this enabled, but it will be useful to diagnose issues with our use of Azure Storage.

Enable AppInsights dependency tracking

---

src/ApiService/ApiService/Functions/Proxy.cs
src/ApiService/ApiService/onefuzzlib/IpOperations.cs
src/ApiService/ApiService/onefuzzlib/ProxyForwardOperations.cs
src/ApiService/FunctionalTests/1f-api/ApiBase.cs
src/ApiService/FunctionalTests/1f-api/Error.cs
src/ApiService/FunctionalTests/1f-api/Node.cs
src/ApiService/FunctionalTests/1f-api/Pool.cs
src/ApiService/FunctionalTests/1f-api/Proxy.cs
src/ApiService/FunctionalTests/1f-api/Scaleset.cs
src/ApiService/FunctionalTests/TestNode.cs
src/ApiService/FunctionalTests/TestPool.cs
src/ApiService/FunctionalTests/TestProxy.cs
src/ApiService/FunctionalTests/TestScaleset.cs

More tests and bug fixes in C# port

Functional tests

---

src/ApiService/ApiService/onefuzzlib/Creds.cs

This is not implemented and not needed. It may result in exceptions being thrown on teardown.

Remove IDisposable from Creds

---

src/agent/coverage/examples/src-cov.rs

Enable convenient local generation of Cobertura XML reports using the `src-cov` example binary from the `coverage` crate.
Progress logging is now written to stdout. Adding the `-x`/`--cobertura-xml` flag will result in emitting an Cobertura XML report to stdout. Otherwise, simple hit/miss line coverage is reported.
Note that this currently only reports src coverage associated with basic block entrypoints, and not every source line that is implicitly executed when a block is entered.

Add Cobertura XML output to `src-cov` example binary

---

src/ApiService/ApiService/Functions/Tasks.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/OneFuzzTypes/Responses.cs

`Nodes` and `Events` are not really part of the `Task` model but only used in responses to search requests. Remove them and make a separate response type.

Remove some response-only properties from the Task model

---

src/deployment/azuredeploy.bicep
src/deployment/bicep-templates/function-settings.bicep
src/deployment/deploy.py

add flag to enable memory and cpu profilers

---

src/deployment/bicep-templates/function.bicep

We want the .NET code running as 64-bit. This shouldn't affect the Python code.

Use 64-bit worker for function

---

src/cli/onefuzz/templates/libfuzzer.py

Fixes #2348.
Code duplicated & modified from line 112.
Both the generic and dotnet coverage tasks [iterate over all `readonly_inputs` that they are supplied](https://github.com/microsoft/onefuzz/blob/bd4dfdc592391e0d02eea8ae2b300252baade3ab/src/agent/onefuzz-task/src/tasks/coverage/generic.rs#L98-L115), so this should be sufficient.

Fix: Coverage task should have access to `readonly_inputs` containers

---

src/ApiService/ApiService/onefuzzlib/VmssOperations.cs

For spot instances:
* `EvictionPolicy` was `Delete` in Python, `Deallocate` in C#
* `BillingMaxPrice` was `-1.0` in Python, `1.0` in C#
At top level:
* `DoNotRunExtensionsOnOverprovisionedVms` was `true` in Python, `false` in C# (however, at the moment we disable overprovisioning)
Reformatted code to make it similar to Python and easier to compare.

Fix: Inconsistencies in VMSS creation between C#/Python

---

src/cli/onefuzz/api.py
src/cli/onefuzz/debug.py

Fixes #2354.
Adds the command `onefuzz debug task download_files <task_id> <output>`.

Add debug command to download a task’s containers

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

`venv` needed to be installed for Python. Also ensure `direnv` is installed to the `vscode` user's profile.

Devcontainer: ensure venv is installed

---

src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs
src/ApiService/ApiService/onefuzzlib/ProxyForwardOperations.cs
src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs
src/ApiService/ApiService/onefuzzlib/VmssOperations.cs

Fixes a problem introduced by #2357, since [only specific types are permitted in `TableClient.CreateQueryFilter`](https://github.com/Azure/azure-sdk-for-net/blob/da47271b8faabc1b61d419b9d0741061154c0482/sdk/tables/Azure.Data.Tables/src/TableOdataFilter.cs#L29-L82).

Fix custom type interpolation in queries

---

.github/workflows/ci.yml
src/ci/agent.sh
src/ci/proxy.sh
src/ci/rust-prereqs.sh

Use a 1ES hosted pool with more powerful machines to do the build for Rust agents.

Use self-hosted runner for Rust agent builds

---

src/ApiService/ApiService/Functions/Scaleset.cs
src/ApiService/ApiService/OneFuzzTypes/Responses.cs
src/ApiService/IntegrationTests/Fakes/TestContext.cs
src/ApiService/IntegrationTests/Fakes/TestVmssOperations.cs
src/ApiService/IntegrationTests/ScalesetTests.cs

The `Auth` property is not meant to be returned upon Create/`POST`. Fix this, and make it easier to specify when `Auth` should be included or not.

Fix Scaleset response Auth inclusion

---

src/ApiService/ApiService/onefuzzlib/TaskOperations.cs
src/ApiService/IntegrationTests/TasksTests.cs

If passed a Job ID and an empty list of states, this would attempt to perform a query like `'(PartitionKey eq '7092e29e-e254-4103-b5fd-4a5dade02365') and ()'`, which is invalid. 
Fix by treating empty lists and null lists of states the same.

Fix TaskOperations.SearchStates

---

src/ApiService/ApiService/onefuzzlib/TaskOperations.cs

This was checking if the task depends on itself, and not the given task.

Fix MarkDependantsFailed

---

src/ApiService/ApiService/onefuzzlib/JobOperations.cs
src/ApiService/ApiService/onefuzzlib/Scheduler.cs
src/ApiService/ApiService/onefuzzlib/TaskOperations.cs

Two fixes to scheduling code:
- `GetPool` was not correct for the VM case (this code is possibly legacy and not used any more)
- `BuildWorkUnit` could fetch the same pool multiple times and then fail due to `BucketConfig` mismatch (on `TimeStamp`)
- add a cache to the loop so that we only fetch each pool once

Two fixes to C# scheduling

---

.github/workflows/ci.yml

Ubuntu agents are back in a working state.

Restore self-hosted configuration

---

.devcontainer/install-dependencies.sh
.github/workflows/ci.yml
.gitignore
src/ci/agent.sh
src/ci/rust-prereqs.sh

Use Codecov to show coverage reports, so we get highlighted versions of the files where it is easy to see missing coverage.
- Setup Rust coverage using [`cargo-llvm-cov`](https://github.com/taiki-e/cargo-llvm-cov).
- Add the `ci/agent.sh` build script to the agent artifact cache key, since it wasn't there before.
- Don't run Rust tests in `--release` mode (have been meaning to change this so doing it at the same time).
There is some subtlety about putting the coverage result into the cached agent artifact, so that when we reuse the agent artifact we can still upload the coverage information for it to Codecov. Without this it would look like the coverage had dropped.

Codecov setup for C# & Rust code

---

src/ApiService/ApiService/Functions/TimerProxy.cs
src/ApiService/ApiService/Functions/TimerRetention.cs
src/ApiService/ApiService/UserCredentials.cs
src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs
src/ApiService/ApiService/onefuzzlib/VmOperations.cs
src/ApiService/ApiService/onefuzzlib/orm/Queries.cs
src/ApiService/FunctionalTests/1f-api/ApiBase.cs

- fix queries in timer retention
- do not discard proxy record after proxy state is processed, since that record needs to persist

fix some bugs

---

src/ApiService/ApiService/Functions/AgentEvents.cs
src/ApiService/ApiService/Functions/Node.cs
src/ApiService/ApiService/Functions/ReproVmss.cs
src/ApiService/ApiService/Functions/Scaleset.cs
src/ApiService/ApiService/onefuzzlib/Auth.cs
src/ApiService/ApiService/onefuzzlib/Extension.cs
src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs
src/ApiService/ApiService/onefuzzlib/ReproOperations.cs
src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs
src/ApiService/Tests/AuthTests.cs

Windows and Linux C# check-pr started to pass

fix linux repro extensions

---

.github/workflows/ci.yml

This should be per-workflow, and it is not by default.

Github Actions: Adjust concurrency spec

---

src/ApiService/ApiService/Functions/TimerRetention.cs
src/ApiService/ApiService/onefuzzlib/PoolOperations.cs
src/ApiService/ApiService/onefuzzlib/Queue.cs
src/ApiService/ApiService/onefuzzlib/ShrinkQueue.cs

cleanup queues for non-existent pools and non-existent tasks

---

src/api-service/__app__/onefuzzlib/notifications/ado.py
src/api-service/__app__/onefuzzlib/notifications/common.py
src/api-service/__app__/onefuzzlib/notifications/github_issues.py
src/api-service/__app__/onefuzzlib/notifications/main.py
src/api-service/__app__/onefuzzlib/notifications/teams.py

Closes #2422, today if we fail to process a notification queue message more than 5 times, the message ends up in a poison queue. But, we also fail the task associated with that notification and we don't want that behavior.
* Renames `fail_task` to `log_failed_notifications`
* `log_failed_notifications` no longer fails the task
* `log_failed_notifications` includes the notification id in the error message for better debugging
* `teams` webhook failure also includes the notification id
* On the 5th failed attempt to process a `queue_file_changes` message, we call `log_failed_notifications` before moving the message to the poison queue
Related but not included in this PR: #2436

Do not fail task on notification failure

---

src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs
src/ApiService/Tests/OrmTest.cs

The existing code was looking for the `PartitionKey` and `RowKey` attribute on the properties instead of the constructor parameter
Closes #2408

Fix logic to retrieve partitionKey and rowKey

---

.github/workflows/ci.yml

Seeing some intermittent failures during `download-artifact`. Update the action to see if this helps.

Update `download-artifact` Github action

---

src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs

When `isNew` was passed, then the creation should fail if there is a `Node` that already exists. Instead, the existing `Node` was being overwritten.

Fix: Node state getting reset to `init`

---

src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs
src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs
src/ApiService/ApiService/onefuzzlib/notifications/GithubIssues.cs
src/ApiService/ApiService/onefuzzlib/notifications/NotificationsBase.cs
src/ApiService/ApiService/onefuzzlib/notifications/Teams.cs

Ports #2435 to C# and makes ADO notifications work. Makes progress towards #1754 
1. Submit a new job
2. Create a new ADO template based on the reports container for the job you just created
3. Check that work items are being created

Can create ado notifications

---

src/ApiService/ApiService/onefuzzlib/PoolOperations.cs
src/ApiService/ApiService/onefuzzlib/ShrinkQueue.cs

`ScalesetOperations.SearchByPool` and `NodeOperations.SearchByPoolName` will never return `null`. Instead, fetch the results into lists and check if they are empty or not.

C#: Correct pool transitions

---

src/ApiService/ApiService/OneFuzzTypes/Validated.cs
src/ApiService/Tests/ValidatedStringTests.cs

We are going to want _some_ restrictions on pool names in future, but for now we are disabling validation to prevent breaking any existing users with non-conforming pool names.

Disable PoolName validation

---

src/cli/onefuzz/backend.py
src/cli/onefuzz/cli.py

In our integration test run we are seeing some connection-reset errors which causes the CLI operation to fail.
To fix this:
1. Set TCP-KeepAlive to keep Azure load balancer connections alive longer than the default timeout (4 minutes).
2. Treat ConnectionResetError as retryable.

CLI: Retry on connection reset

---

src/ApiService/ApiService/Functions/TimerWorkers.cs

During `TimerWorkers` if updating one entity fails and throws an exception we will abandon the whole update. Instead log the error and continue to attempt to process the remaining entities. This will allow us to make progress even if one entity is stuck.

Allow worker loops to continue after errors

---

src/ApiService/ApiService/Functions/AgentCanSchedule.cs
src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/VmssOperations.cs

This is a potentially expensive operation as we need to fetch every VM in the Scaleset to find the VMID we are looking for.
This should be safe to cache "forever" since the mapping will not change.
It seems like we should be storing the `InstanceID` instead of (as well as?) the VMID, but that is hard to change at the moment. Perhaps after C# port is completed.

Cache VMSS VM InstanceID lookups

---

src/agent/Cargo.lock
src/agent/onefuzz-agent/Cargo.toml
src/agent/onefuzz-task/Cargo.toml

Enable the `backtrace` feature of `anyhow`, our dynamic catch-all error library. This lets us include backtraces (on `stable` rustc) in our `?`-propagated errors (as long as `RUST_BACKTRACE` is set, which we do in `runtime-tools`).
Example error without the `backtrace` feature:
```
Error: loading path: i-dont-exist.txt
Caused by:
The system cannot find the file specified. (os error 2)
error: process didn't exit successfully: `target\debug\anyhow-backtrace-example.exe i-dont-exist.txt` (exit code: 1)
```
With:
```
Error: loading path: i-dont-exist.txt
Caused by:
The system cannot find the file specified. (os error 2)
Stack backtrace:
0: std::backtrace::Backtrace::create
at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library\std\src\backtrace.rs:333
1: std::backtrace::Backtrace::capture …
```

Enable backtraces for agent errors

---

.github/workflows/ci.yml

Attempting to fix the failure we see occasionally, like [here](https://github.com/microsoft/onefuzz/actions/runs/3184845545/jobs/5193798358).
The problem seems to be that we have multiple jobs uploading into the same named artifact; if we only wait for one of those jobs to finish then the artifact is not fully complete and we get 404s for different parts of the artifact occasionally when trying to download it. Potentially there is some kind of race where the artifact is marked as containing a file but doesn't actually have the file data yet.

Attempt to fix `integration-tests-linux` failure

---

docs/how-to/fuzzing-dotnet-with-libfuzzer.md

Closes #2457.
The `linux-x64` target is inappropriate for Ubuntu 18.04, which is our current default OS.

Update documentation to specify appropriate RID

---

src/cli/requirements.txt

Component Governance warns about CVE-2020-25658, so update `rsa` to a higher version.

Python: Upgrade `rsa` dependency

---

src/agent/onefuzz/src/az_copy.rs

Changing the log level to INFO [(the default value)](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure#change-the-default-log-level) To get more information about the azcopy failure

Change the verbosity of the azcopy logs

---

src/agent/Cargo.lock
src/agent/onefuzz-task/Cargo.toml
src/agent/onefuzz-task/src/tasks/task_logger.rs

Update the `azure_*` packages that Dependabot is trying to upgrade.

Update Rust azure_* dependencies

---

src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs
src/ApiService/ApiService/onefuzzlib/ReproOperations.cs
src/ApiService/ApiService/onefuzzlib/VmOperations.cs

Fetching the `InstanceView` data for a VM is considered a “high-cost” operation by VMSS and contributes to throttling. In most cases we do not need this data, so split the `GetVm` method into two versions, one that fetches the `InstanceView` data and one that doesn’t.
We only need `InstanceView` data during VM provisioning failures, to see what went wrong.

Only fetch VM InstanceView data when required

---

src/agent/onefuzz/src/uploader.rs

This fix is related to the az_copy issue. The files in the crash container are being constantly rewritten even if they are not supposed to. 
This PR changes the method for detecting duplicates by setting the `"If-None-Match` header to `*` as per the [documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url#request-headers)

Update the logic for checking if a blob exist before uploading

---

src/agent/Cargo.lock
src/agent/srcview/Cargo.toml
src/agent/srcview/src/srcview.rs

Adds a way to ensure the existence of a PDB in the SrcView cache without re-parsing. This is helpful when continuously adding new coverage of a module with a PDB that has already been inserted into the SrcView.
Adds try_insert function to the SrcView struct of the srcview crate so that a user can ensure a PDB associated with the given module name has been parsed without re-parsing the PDB.

Add SrcView::try_insert function

---

src/ApiService/ApiService/onefuzzlib/notifications/GithubIssues.cs

Github doesn't like the `/` in the header.

Fix github client header value

---

src/agent/libclusterfuzz/cgmanifest.json

This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …

Add `$schema` to `cgmanifest.json`

---

src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/VmssOperations.cs

Even if the caller doesn't care about the result of the scaling protection change, log when we fail to make the update to make it easier to trace in prod.

Improve scaling protection logging

---

src/ApiService/ApiService/onefuzzlib/NodeMessageOperations.cs
src/ApiService/ApiService/onefuzzlib/Utils.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs

Introduce a DeleteAll operation to speedup the deletion of multiple entities.
The new method is able to delete 13404 Nodemessges in 4s

Add deleteAll to the orm

---

src/agent/coverage/src/block/linux.rs

Closes #2520.
After investigation the underlying cause here is that the process is getting killed due to timeout, but we don't report the timeout or produce an error. Modify the coverage code so that it fails if timeout is hit.
Do we want to be able to support a partial coverage instead?

Produce an error if coverage recording failed due to timeout

---

src/agent/onefuzz/src/az_copy.rs

The current code assumes that only one log file is produced by azcopy. But since [10.9.0](https://github.com/Azure/azure-storage-azcopy/blob/main/ChangeLog.md#version-1090) a scanning log file has been introduced.
This PR ignores the scanning log file.

Ignoring the scanning log file when reporting an issue with azcopy

---

src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs
src/ApiService/ApiService/onefuzzlib/VmssOperations.cs

Handle nulls better in scaleset shutdown

---

src/deployment/bicep-templates/function-settings.bicep

fix onefuzz address
This config value is used to generate the `input_url` in the report. The `existing` code was generating a value pointing to the temporary `-net` address.

fix onefuzz address

---

src/agent/coverage/src/region.rs

Avoid spamming telemetry with common symbol analysis events that are typically not errors.
Closes #2558.

Lower log level on region overlap

---

src/agent/coverage/examples/src-cov.rs
src/agent/onefuzz-task/src/tasks/coverage/dotnet.rs
src/agent/onefuzz-task/src/tasks/coverage/generic.rs

As of #2529 we now fail if the coverage recording times out. The default timeout (5s) does not appear to be long enough for even simple tasks to run, so extend it to 120s.

Extend default coverage timeout to 120s

---

src/cli/onefuzz/backend.py

Save the onefuzz config in the virtual environment folder. This simplifies the scenarios of connecting to multiple environments.

Use the vitual env folder to store the config if it exists

---

src/integration-tests/integration-test.py

This currently causes the coverage task to time out, ensure that the `runs` parameter is only passed to the fuzzing task and not the coverage task.

Update the libfuzzer-with-options test to use fuzzing_target_options

---

src/ApiService/ApiService/Functions/ReproVmss.cs
src/ApiService/ApiService/Log.cs
src/ApiService/ApiService/onefuzzlib/AutoScale.cs
src/ApiService/ApiService/onefuzzlib/ConfigOperations.cs
src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/ReproOperations.cs
src/ApiService/ApiService/onefuzzlib/VmssOperations.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs
src/ApiService/IntegrationTests/TestLogTracer.cs

If we delete a Repro and it is already missing, this shouldn't be considered an error.
Also update the Insert/Update/Delete/Replace methods to return an `HttpStatusCode` instead of a raw `int`.

Don't log an error if we delete a Repro and it is already missing

---

src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs

Webhooks are being successfully sent but onefuzz is interpreting them as failures. This PR improves logging when there's a failure and also accepts a wider variety of HTTP codes as successful.
* Accept all HTTP codes 200-299 as success
* Log request details on unsuccessful requests to improve debuggability
* NOTE: Exceptions are already handled and logged in a parent function

Improve webhook logging and accept more HTTP success codes

---

src/ApiService/ApiService/Functions/AgentRegistration.cs
src/ApiService/ApiService/OneFuzzTypes/Requests.cs

Use records to unpack the request parameters in AgentRegistration.
related to #2482

Use records to unpack the request parameters in AgentRegistration

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/onefuzz-telemetry/Cargo.toml
src/proxy-manager/Cargo.lock
src/proxy-manager/Cargo.toml

v0.2.3 has the fix for the `chrono` dependency incorporated.

Update to released version of appinsights-rs

---

src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs
src/ApiService/ApiService/onefuzzlib/VmssOperations.cs
src/ApiService/IntegrationTests/Fakes/TestVmssOperations.cs

1. `ListVmss` was invoking `GetVirtualMachineScaleSetAsync` and then `GetVirtualMachineScaleSetVms`; instead we can get the VMSS resource directly and invoke `GetVirtualMachineScaleSetVms` on it.
2. I also removed some unneeded invocations of `AsAsyncEnumerable` which might be turning async enumerables into sync enumerables.
3. Do the same `HasData` check in the instance ID lookup that we were already doing in `ListVmss`.
After this change (#3) we no longer do any `GET`s against individual VMSS VMs during the `check-pr` run:

Reduce number of ARM calls in ListVmss

---

.github/workflows/ci.yml

Node.js 12 actions are deprecated, as well as `::set-output` 
- Update `actions/checkout` to v3
- Update `actions/upload-artifact` to v3
- Update `actions/setup-python` to v4
- Update `actions/cache` to v3
- `set-output` on stdout is deprecated, update to `$GITHOUT_OUTPUT` method
- Change from `actions-rs/toolchain` (unsupported) to `dtolnay/rust-toolchain`
The only warning remaining after this is the one about Ubuntu 18.04.

Fix Github actions warnings

---

src/cli/onefuzz/backend.py

create the config_path folder if it does not exist

---

src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs

We want to discard nodes as soon as they're done completing their assigned tasks. This is different from the current behavior where we try to re-use nodes by reimaging them. Originally, this discard process was accomplished by removing scale-in protection and letting auto scale take care of everything. The issue with that approach is that scale-in actions only happen when the work queue for the pool is empty so letting auto scale delete the nodes won't work for a system under load.
This PR changes our approach to deleting nodes right away instead of reimaging or waiting for scale-in actions. The behavior continues to be behind the "NodeDisposalStrategies" env var until we decide to enable it by default.

Delete nodes on decommission instead of just releasing scale in protection

---

contrib/deploy-onefuzz-via-azure-devops/tox.ini

Unbreak the build until `wheel >=0.38.0` is published to PyPI.
Context: https://github.com/microsoft/onefuzz/pull/2593#issuecomment-1299331019

Temporarily disable `pipenv check` call

---

contrib/deploy-onefuzz-via-azure-devops/tox.ini

Still run `pipenv check`, but ignore the known (non-actionable) `wheel` issue.
Context: https://github.com/microsoft/onefuzz/pull/2593#issuecomment-1299331019

Only ignore known `wheel` issue

---

src/ApiService/ApiService/Functions/Notifications.cs
src/api-service/__app__/notifications/__init__.py

Read the notification request  parmeters from the body of the request instead of the uri
related to #2589

Fix the notification get request

---

src/ApiService/ApiService/ApiService.csproj
src/ApiService/ApiService/Log.cs
src/ApiService/ApiService/Program.cs
src/ApiService/ApiService/packages.lock.json
src/ApiService/IntegrationTests/packages.lock.json
src/ApiService/Tests/packages.lock.json

Switch to using the package provided by Azure Functions to set up Application Insights.
Using the provided setup method `AddApplicationInsightsTelemetry` will configure the dependency collector by default as well as set up some other things that we haven’t done manually, including application version, which would be very useful.
This also means that `operation_Id` is populated more consistently which permits joining `traces` or `dependencies` on the `requests` table.
This also means that the end-to-end data in AI is now correct, so the chart works:

Improve AppInsights setup

---

src/ApiService/ApiService/onefuzzlib/Containers.cs

The C# version of this function throws an exception if it finds duplicate containers; in the Python code the last one wins. Update the C# code to match the Python code.
Closes #2580.

Fix: Handle duplicate containers across accounts

---

src/ApiService/ApiService/Functions/Negotiate.cs

Fixes #2572. 
For some reason, the well-typed `SignalRConnectionInfoInput` object does not contain an access-token. The string version does.

Fixing `status top` bug

---

src/agent/Cargo.lock

0.2.1 has been [yanked](https://github.com/RustCrypto/utils/pull/802).

Bump cpufeatures to 0.2.5

---

src/cli/onefuzz/api.py

Add the option to wait indefinitely for the connection to the debug server
closes #2528

Adding an optional retry_limit to onefuzz debug connect

---

src/agent/Cargo.lock
src/agent/coverage/Cargo.toml
src/agent/coverage/src/cobertura.rs
src/agent/onefuzz-task/Cargo.toml
src/agent/srcview/Cargo.toml
src/agent/storage-queue/Cargo.toml

Per Rust security advisory [RUSTSEC-2022-0048](https://rustsec.org/advisories/RUSTSEC-2022-0048.html), update from `xml-rs`, which is unmaintained, to `quick-xml`. (We are already using `quick-xml` as of #2515.)
We still consume `xml-rs` through the `azure_*` dependencies so we cannot yet disable the suppression in `agent.sh`.
Also update tests to match, which closes #1774.

Maintenance: switch to quick-xml

---

src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs

This is already optional on the Rust side (see: [microsoft_telemetry_key](https://github.com/microsoft/onefuzz/blob/5c5dfd3b23e421eaa0e2eb79aa6860f2aa49f811/src/proxy-manager/src/config.rs#L49)). Make it optional on the C# side as well.

Make Proxy TelemetryKey optional

---

src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs

We’re currently posting comments on a workitem about reopening it even if we didn't actually reopen it. 
Update to only add the comment if we changed the workitem state.

Only add "re-opened" comment if bug was reopened

---

src/cli/onefuzz/backend.py
src/cli/requirements.txt
src/deployment/deploy.py
src/deployment/deploylib/registration.py

Update CLI to attempt broker or browser-based authentication first; if you `Ctrl-C` to cancel it, you can fall back to device code login.
Also updated the MSAL dependency to latest version and pass `allow_broker=True` which will allow the use of Web Account Manager (WAM), if it is available.
Using browser auth requires the `http://localhost` redirect URI, and using the broker requires a special custom URI including the app ID (see code).

Use broker or browser login instead of device flow

---

src/ApiService/ApiService/onefuzzlib/notifications/NotificationsBase.cs

[_targetUrl in NotificationsBase.cs](https://github.com/microsoft/onefuzz/blob/main/src/ApiService/ApiService/onefuzzlib/notifications/NotificationsBase.cs#L33) incorrectly uses the target exe's absolute path in the URL. This changes the URL to only use the filename.

Target URL notification template parameter fix

---

src/cli/onefuzz/status/raw.py
src/cli/onefuzz/status/signalr.py

The `Response` object must have the JSON loaded via `json()` (`backend.request` was updated but this callsite was missed).
Also, import the `Onefuzz` type so that this is type-checked to avoid the same problem in future.

Fix SignalR client code not reading responses correctly

---

contrib/webhook-teams-service/webhook/__init__.py

This PR fixes a simple logic error in the notification hook, which caused it to return an error response if the Teams endpoint succeeded.
In addition, this changes the code to return proper HTTP error codes if the script fails.

Fix a logic bug in the notification hook

---

src/ApiService/ApiService/Functions/Pool.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/UserCredentials.cs
src/ApiService/ApiService/onefuzzlib/EndpointAuthorization.cs
src/ApiService/ApiService/onefuzzlib/Extension.cs
src/ApiService/ApiService/onefuzzlib/PoolOperations.cs
src/agent/onefuzz-agent/src/config.rs
src/agent/onefuzz-agent/src/main.rs
src/agent/onefuzz/src/auth.rs
src/cli/onefuzz/api.py
src/proxy-manager/src/proxy.rs
src/pytypes/onefuzztypes/models.py

- fix the token request in the client
- adding a managed field to the agentConfig
- fix typo in the appId claim type
- fix typo in the UnmanagedNode claim value
- fix query PoolOperation.GetByClientId

Bug fixes related to the unmanaged nodes

---

src/agent/Cargo.lock
src/agent/onefuzz-task/Cargo.toml
src/agent/onefuzz-task/src/tasks/task_logger.rs

Bump the crates which dependabot is trying to bump.
Remove invocations of `into_future` as `.await` now automatically uses the [`IntoFuture` trait](https://doc.rust-lang.org/std/future/trait.IntoFuture.html) as of 1.64.

Bump azure_* crates

---

.devcontainer/devcontainer.json

Set some more devcontainer VS Code settings by default:
- set desired Python formatter & linters
- set format-on-save by default
- add `proxy-manager` to default Rust projects

More default devcontainer settings (format on save, Python linters)

---

src/deployment/deploy.py

The deployment script was using the application name as the resource group when updating the pp settings
#2644

Fix invocation of functionapp in the deployment script

---

src/ApiService/ApiService/onefuzzlib/Extension.cs
src/agent/onefuzz-task/src/tasks/report/dotnet/common.rs
src/agent/onefuzz-task/src/tasks/report/dotnet/generic.rs
src/api-service/__app__/onefuzzlib/extension.py
src/deny.toml
src/runtime-tools/linux/setup.sh
src/runtime-tools/win64/onefuzz.ps1
src/runtime-tools/win64/setup.ps1

~~Based upon `check-pr` results we still need .NET 6 in order to run the existing SharpFuzz binary; modify install scripts to install multiple supported versions.~~
The minidump file being generated did not have enough information for SOS to correctly locate the exception object. Switch to “full” minidumps instead.
- Fix a small bug with coverage reporting task ID as job ID.
- I had thought we needed .NET 6 installed as well to run SharpFuzz, but now I'm not so sure. In any case, installing both versions will not hurt (and may help users).

Fixing .NET crash report no-repro

---

.devcontainer/devcontainer.json
.github/workflows/ci.yml

Run `az bicep build` via the `azure/CLI` Github Action, which will fail if the Bicep files are malformed.
Also, add the YAML extension to `devcontainer.json`; it reformatted the `CI.yml` file as a once-off change. ([Set whitespace to ignore during review](https://github.com/microsoft/onefuzz/pull/2658/files?diff=split&w=1).)

Check Bicep files during CI

---

src/ApiService/ApiService/Functions/AgentCanSchedule.cs
src/ApiService/ApiService/OneFuzzTypes/Responses.cs
src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/agent/onefuzz-agent/src/agent.rs
src/agent/onefuzz-agent/src/coordinator.rs
src/agent/onefuzz-agent/src/coordinator/double.rs
src/deny.toml

Updated the response given by the server when denying work to a node. 
We now include a reason field to containing an explanation

Include a reason when telling a node it is not allowed to schedule work

---

src/agent/.cargo/config
src/agent/.cargo/config.toml

Enabling some native code features which are SDL requirements. (Specifically, the requirement "Executable binary files must be hardened to leverage available platform security mitigations".)
I attempted to use BinSkim to enforce the requirements but it has trouble with Rust binaries at present.

Enable MSVC security features

---

src/runtime-tools/win64/onefuzz.ps1

`LLVM_SYMBOLIZER_PATH` is being used to set the `ASAN_SYMBOLIZER_PATH`, but on Windows this is not working correctly; the ASAN output includes:
WARNING: Failed to use and restart external symbolizer!
After experimentation it appears that this path must be absolute.

`LLVM_SYMBOLIZER_PATH` must be absolute on Windows

---

src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs
src/ApiService/ApiService/onefuzzlib/ReproOperations.cs

This is a regression from Python to C# version: the C# code was not checking the result of the AddExtensions function, so would transition Repro VMs or Proxy VMs into Running state potentially before they are ready to be used.
This could cause test failures or confusing errors when running `create_and_connect`.

Check extensions status before transitioning to Running

---

src/cli/onefuzz/backend.py

While running tests we sometimes see token acquisition fail due to "Connection reset by peer". This should be retried by default.

CLI: Retry on connection errors while acquiring token

---

src/ApiService/.config/dotnet-tools.json

This was needed to generate Markdown-based code coverage reports which we don't use any more.

Remove reportgenerator

---

src/ci/dotnet-fuzzing-tools.sh
src/runtime-tools/linux/setup.sh
src/runtime-tools/win64/onefuzz.ps1

While I was investigating `llvm-symbolizer` issues, I found that we are installing LLVM-10 by default.
Now that we are using the Ubuntu 20.04 image as the default, use the latest LLVM version available for that release. (In addition, v12 is also available on 22.04, whereas v10 is not.)

Update LLVM from v10 to v12

---

src/agent/Cargo.lock
src/agent/input-tester/Cargo.toml
src/agent/input-tester/src/crash_detector.rs
src/agent/input-tester/src/lib.rs
src/agent/input-tester/src/tester.rs
src/agent/onefuzz/src/input_tester.rs

Remove unused coverage recorder from `input-tester`

---

src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs
src/ApiService/ApiService/onefuzzlib/VmssOperations.cs
src/ApiService/IntegrationTests/Fakes/TestVmssOperations.cs

Updated the ScalesetOperations.GetNodes to return a non-nullable dictionary

Fix NullRef exception when getting a scaleset that does not exist

---

src/agent/coverage/src/binary.rs
src/agent/onefuzz-file-format/src/coverage/binary/v1.rs
src/agent/onefuzz-file-format/tests/files/binary-coverage.v0.json
src/agent/onefuzz-file-format/tests/files/binary-coverage.v1.json
src/agent/onefuzz-file-format/tests/integration.rs

Add a `blocks` subkey to the binary block coverage JSON schema, and test conversions. This will make it easier to add new per-module metadata in the future, if needed.
**Old:**
```json
{
"/setup/main.exe": {
"1": 0,
"12c": 1,
"1388": 0
},
"/setup/lib/some.dll": {
"7b": 0,
"1c8": 10
}
}
```
**New:**
```json
{
"/setup/main.exe": {
"blocks": {
"1": 0,
"12c": 1,
"1388": 0
}
},
"/setup/lib/some.dll": {
"blocks": {
"7b": 0,
"1c8": 10
}
}
}
```

Add key for block coverage, tests

---

src/agent/coverage/examples/coverage.rs
src/agent/coverage/src/lib.rs
src/agent/coverage/src/record.rs
src/agent/coverage/src/record/linux.rs
src/agent/coverage/src/record/linux/debugger.rs
src/agent/coverage/src/record/windows.rs

- Add an OS-generic `CoverageRecorder` builder for recording coverage from common parameters
- Capture the output of the target child process when recording coverage
- Enable `Loader` reuse for when coverage is recorded many times for the same target

Capture target output, allow `Loader` reuse

---

src/agent/onefuzz-agent/src/agent.rs
src/agent/onefuzz-agent/src/agent/tests.rs
src/agent/onefuzz-agent/src/commands.rs
src/agent/onefuzz-agent/src/config.rs
src/agent/onefuzz-agent/src/coordinator.rs
src/agent/onefuzz-agent/src/coordinator/double.rs
src/agent/onefuzz-agent/src/debug.rs
src/agent/onefuzz-agent/src/main.rs
src/agent/onefuzz-agent/src/reboot.rs
src/agent/onefuzz-agent/src/reboot/double.rs
src/agent/onefuzz-agent/src/scheduler.rs
src/agent/onefuzz-agent/src/setup.rs
src/agent/onefuzz-agent/src/setup/double.rs
src/agent/onefuzz-agent/src/work.rs
src/agent/onefuzz-agent/src/worker.rs
src/agent/onefuzz-agent/src/worker/double.rs
src/agent/onefuzz-agent/src/worker/tests.rs

Removing the shared mutable state (&mut self) from the agent state machine. The intent is to make the code easier to reason with.

Reduce mutation in the agent state machine

---

src/agent/onefuzz-file-format/src/coverage/binary.rs
src/agent/onefuzz-file-format/src/coverage/source.rs
src/agent/onefuzz-file-format/tests/binary.rs
src/agent/onefuzz-file-format/tests/files/binary-coverage.v1.json
src/agent/onefuzz-file-format/tests/files/source-coverage.v1.json
src/agent/onefuzz-file-format/tests/source.rs

- Use semver strings for coverage file versioning
- Use adjacent tagging for coverage file formats (`{ "version": "...", "coverage": { ... } }`)
- Add compat `deserialize()` functions to handle unversioned `v0`/0.1 files

Add deserialization compat functions

---

src/agent/coverage/src/timer.rs

Remove a stray unwrap. There's no reason to panic the thread, since the timeout and worker function are inherently racy.

Ignore benign recv hangup in timer

---

src/agent/coverage/src/record.rs
src/agent/coverage/src/record/linux/debugger.rs

We can't actually always observe a recorded process exit using `Child::wait()`, so the `ExitStatus` of our `Output` needs to be optional. Create a less-presumptuous `Output` type of our own that lets us express these situations, and can be constructed in a platform-appropriate way.

Use a custom `Output` type when recording coverage

---

src/agent/Cargo.lock
src/agent/coverage/Cargo.toml
src/agent/coverage/src/binary.rs
src/agent/coverage/src/binary/tests.rs
src/agent/coverage/src/record/linux.rs
src/agent/coverage/src/record/windows.rs

Enable merging binary coverage measurements, combining offset counts via saturating addition or integer maximum.

Add binary coverage merging

---

src/agent/onefuzz-file-format/src/coverage/binary.rs
src/agent/onefuzz-file-format/src/coverage/source.rs
src/agent/onefuzz-file-format/src/coverage/source/v1.rs

Add additional coverage conversions from in-memory structures directly into JSON-serializable formats. Note that we can now convert directly from coverage data into the JSON container enum (via conversion into the latest versioned format).

Add more into-JSON coverage conversions

---

src/agent/Cargo.lock
src/agent/onefuzz-agent/Cargo.toml
src/agent/onefuzz-task/Cargo.toml
src/agent/onefuzz-telemetry/Cargo.toml
src/agent/onefuzz/Cargo.toml
src/agent/reqwest-retry/Cargo.toml
src/agent/storage-queue/Cargo.toml

Bumps [tokio](https://github.com/tokio-rs/tokio) from 1.16.0 to 1.24.1.
Also bumps dependent [mio](https://github.com/tokio-rs/mio) from 0.8.2 to 0.8.5

Bump Tokio from 1.16.0 to 1.24.1 in /src/agent

---

src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs

The existing logic was stopping the processing of a new file when no notification is configured on the container.
This prevented task from receiving new file notification

Fix notification logic

---

src/agent/coverage/src/allowlist.rs
src/agent/coverage/src/allowlist/tests.rs

Enable extending allowlists. We will use this feature in the task executor to add a baseline denylist that will avoid errors that occur on ASan interceptor initialization in the presence of software breakpoints.
For #2741.

Support allowlist extension

---

src/ApiService/ApiService/onefuzzlib/Reports.cs
src/ApiService/Tests/ReportTests.cs

Another fix to the regression parsing

---

docs/getting-started.md

The `--container_type` argument is not named

Fix command in docs

---

src/agent/coverage/src/allowlist.rs
src/agent/coverage/src/allowlist/tests.rs

Use `regex::escape()` to comprehensively treat rule expressions as regex literals. Then convert an escaped asterisk to a regex wildcard, and anchor.

Fully escape allowlist rules

---

src/agent/coverage/src/binary.rs

Before this change, we only applied source allowlists to a function's entry offset. However, inlined blocks could come from other functions, including some that would be filtered out by deny rules. As a result, the allowlist could incompletely exclude coverage recording for such inlinees.
Instead, apply the source allowlist to each block entrypoint. This assumes that all instructions within a basic block come from the same function. The result is that block-level expansion and source-line mapping correctly inherits allowlist rule application at the binary level.

Apply allowlist to all blocks within a function

---

src/agent/Cargo.lock
src/agent/onefuzz-task/src/tasks/coverage/dotnet.rs
src/agent/onefuzz-task/src/tasks/coverage/generic.rs
src/agent/onefuzz/Cargo.toml
src/agent/onefuzz/src/expand.rs

- Recursively expand Paths before canonicalization; fixes #2387
- Detect and error on infinitely-expanding variables (due to self-reference or mutual recursion); this fixes an existing problem with list expansion as well
- Detect and report references to unknown replacements (e.g. typoes)
- Detect and report references to _known_ replacements which are not available
---
There is a behavioural change here which is that values which were previously unknown such as `{x}` were unexpanded; from now on these will be errors. It's possible that something somewhere is relying on this.

Fixes & improvements to `Expand` behaviour

---

src/ci/agent.sh
src/ci/check-dependencies.sh

Closes #1966. Check the list of dynamic dependencies of the agent binaries to ensure we don't accidentally take a dependency on some new or unknown library.

Check agent binary dependencies in CI

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

Fixing build failure, see: https://rustsec.org/advisories/RUSTSEC-2023-0005

Update tokio to fix RUSTSEC-2023-0005

---

src/cli/onefuzz/templates/libfuzzer.py

fix default value of analyzer_exe

---

docs/webhook_events.md
src/cli/onefuzz/api.py
src/cli/onefuzz/debug.py
src/cli/onefuzz/status/cmd.py
src/cli/onefuzz/status/top.py
src/cli/onefuzz/template.py
src/pytypes/onefuzztypes/models.py
src/pytypes/onefuzztypes/requests.py
src/pytypes/onefuzztypes/responses.py

Adds a cli command `onefuzz debug notification template`. You pass a template string and it will attempt to render it for you via scriban.
Help text:
```
$ onefuzz debug notification template -h
usage: onefuzz debug notification template [-h] [-v] [--format {json,raw}] [--query QUERY] [--context TemplateRenderContext] template
positional arguments:
template
options:
-h, --help            show this help message and exit
-v, --verbose         increase output verbosity
--format {json,raw}   output format
--query QUERY         JMESPath query string. See http://jmespath.org/ for more information and examples.
--context TemplateRenderContext
JSON for TemplateRenderContext. use @file to read from a file
```
Closes #2501 
* Adds the new template subcommand
* Adds some new C# …

Validate scriban from cli

---

src/cli/onefuzz/templates/libfuzzer.py

Add readonly_inputs to dotnet & dotnet_dll templates

---

docs/deprecated/declarative-templates.md
docs/deprecated/managing-templates.md
src/cli/onefuzz/api.py

The job template feature was not ported to the new C# version of the service. This PR is deprecating it until we decide to port it

Deprecating the job template feature

---

src/cli/onefuzz/api.py
src/pytypes/onefuzztypes/requests.py
src/pytypes/onefuzztypes/responses.py

Closes #2810. This adds the ability to run `onefuzz notifications migrate_jinja_to_scriban`
* New CLI command for jinja to scriban migration endpoint
* New request/response types needed for the endpoint
Target a dev deployment and run with and without `--dry_run` argument.

Interact with migrations via cli

---

src/agent/coverage/examples/coverage.rs

Enable the use of a function allow/denylist when testing locally.

Add function allowlist to coverage example

---

src/agent/debugger/Cargo.toml

The `coverage` crate does not build on its own unless the `namedpipeapi` feature from `winapi` is enabled.
In the larger OneFuzz workspace, this feature is enabled for `winapi` elsewhere, which is why the build generally is not broken.
A note: `winapi` hasn't had a commit since November 2021.

Fix coverage example build

---

src/agent/coverage/src/record/windows.rs
src/agent/debuggable-module/src/debuginfo.rs

For each loaded module, defer setting coverage breakpoints until exit from certain known initialization functions (when present). Crucially, this lets us avoid breaking Address Sanitizer interceptor initialization, which will otherwise divergently fail execution by [raising its own debug break exception](https://github.com/llvm/llvm-project/blob/llvmorg-14.0.6/compiler-rt/lib/interception/interception_win.cpp#L655-L660).
With this PR, neither OneFuzz itself nor locally-debugging end users will need to use an allowlist to exclude ASan-intercepted functions from coverage recording.
This PR also fixes a bug in breakpoint setting, which would would prevent setting breakpoints whose offset collided with any other breakpoint's offset (_ignoring_ base module). This would manifest in false …

Defer coverage breakpoints

---

src/deployment/bicep-templates/feature-flags.bicep

The scriban migration cli trigger wasn't shipped in 6.4. If EnableScriban is enabled at deployment time, we would need to run the migration **before** the deployment.
This way, we can run the migration after deploying 7.0, and then flip the feature flag afterwards.

Sets `EnableScriban` to false by default at deployment time

---

src/cli/onefuzz/templates/libfuzzer.py

Add `--notification_config` support for dotnet templates

---

src/ApiService/ApiService/Functions/AgentCommands.cs
src/ApiService/ApiService/Functions/Scaleset.cs
src/ApiService/ApiService/OneFuzzTypes/ReturnTypes.cs
src/ApiService/ApiService/onefuzzlib/ReproOperations.cs
src/ApiService/IntegrationTests/ScalesetTests.cs

Closes #2805.
Also change the Result types so that this kind of mistake would be statically detected by the compiler (no other instances of the problem found at the moment, but did fix some other code to comply with static analysis changes).

Fix error reporting for creating a Scaleset under a missing Pool

---

.github/fabricbot.json

The default fabricbot needs triage label was different from what we use.

Update "Needs Triage" label to the one we use.

---

src/ApiService/ApiService/onefuzzlib/VmOperations.cs

Closes #2804.
---
Old failure message:
```
failed to launch extension
```
New failure message:
```
failed to launch extension(s): Errors for extension 'CustomScriptExtension':
:Error: ProvisioningState/failed/3 (Provisioning failed) - Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (400) Bad Request.
```

Report extension errors

---

src/agent/coverage/examples/coverage.rs

Add a new `--input-dir`/`-d` argument to the coverage recording example exe. When provided, the exe will record the combined coverage of every file found in `input_dir`, substituting the file path for the special marker `@@`. When not provided, the target command will be executed exactly as-is (the previous behavior).

Accept optional dir of coverage test inputs

---

docs/telemetry.md
src/agent/Cargo.lock
src/agent/onefuzz-telemetry/Cargo.toml
src/agent/onefuzz-telemetry/src/lib.rs

Remove Z3 telemetry

---

src/proxy-manager/Cargo.lock
src/proxy-manager/Cargo.toml
src/proxy-manager/src/config.rs
src/proxy-manager/src/main.rs
src/proxy-manager/src/proxy.rs

Bump `clap` in proxy to 4.0

---

src/ApiService/ApiService/Functions/AgentEvents.cs

Update the error truncating logic to retrieve the last messages.
This makes it easier to identify the cause of the failure of a task

Update the error truncating logic to retrieve the last messages

---

src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/onefuzzlib/Config.cs
src/ApiService/ApiService/onefuzzlib/Defs.cs

A 'missing field' error affecting libfuzzer was previously addressed in #1739. This fix addressed #1672. 
This PR ports the fix to the C# code. 

Port 'missing field' error fix to C#

---

src/ApiService/ApiService/onefuzzlib/Reports.cs

Add additional filter condition to catch `source-coverage.json` files. 

Add additional filter check for reports and regressions

---

.github/workflows/ci.yml
src/ApiService/ApiService/onefuzzlib/Config.cs
src/ci/get-version.sh

Fix condition when generating the task config

Fix condition when generating the task config

---

src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/cli/requirements.txt
src/deployment/requirements.txt
src/utils/add-corpus-storage-accounts/requirements.txt
src/utils/check-pr/requirements.txt

removing dependency on cryptography==3.3.2
closes #2932

fix CVE-2023-0286

---

src/agent/Cargo.lock
src/agent/cobertura/Cargo.toml
src/agent/onefuzz-file-format/Cargo.toml
src/agent/onefuzz-task/Cargo.toml
src/agent/srcview/Cargo.toml
src/agent/storage-queue/Cargo.toml
src/agent/storage-queue/src/azure_queue.rs
src/agent/storage-queue/src/local_queue.rs
src/deny.toml
src/proxy-manager/Cargo.lock

Update the Azure crates and switch from `serde-xml-rs` to `quick-xml`, which removes a warning suppression from `deny.toml`.

Remove xml-rs dependency

---

src/agent/Cargo.lock
src/agent/onefuzz-task/Cargo.toml
src/agent/onefuzz/Cargo.toml
src/proxy-manager/Cargo.lock

Upgrade version of tempfile
remove_dir_all was imported by tempfile. The new version removed that dependency
closes #2930

Fix WS-2023-0045

---

src/runtime-tools/win64/onefuzz.ps1

The latest VC redistributables [support VS2015 through VS2022](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022), so we only need to install one version.

Install v17 redistributables

---

src/cli/onefuzz/templates/libfuzzer.py

Update the libfuzzer templates to add option to specify a known crash container.
This is useful when the user wants to include some known crashes to the job submission.

Add option to specify a  known crash container

---

src/deployment/bicep-templates/event-grid.bicep
src/deployment/deploy.py
src/utils/add-corpus-storage-accounts/add-corpus-storage-account.py

The EventGrid subscription name is invalid according to the published schema. Rename it, and add a deployment step to delete any old instances of this subscription.

Rename EventGrid subscription

---

src/ApiService/ApiService/onefuzzlib/notifications/NotificationsBase.cs
src/ApiService/IntegrationTests/JinjaToScribanMigrationTests.cs
src/agent/onefuzz-task/src/tasks/report/dotnet/generic.rs
src/agent/onefuzz/src/input_tester.rs
src/agent/stacktrace-parser/src/lib.rs

Closes #841. 
If all we have is a call stack, use the top of the "minimized stack" as the crash site, not the top of the full stack.
This only happens if we don't have ASAN logs available for the crash.

Use minimized stack for crash site if no ASAN logs available

---

.github/dependabot.yml

Allow Dependabot to send PRs for .NET version upgrades.

.NET configuration for Dependabot

---

.github/dependabot.yml
src/ApiService/ApiService/ApiService.csproj
src/ApiService/ApiService/onefuzzlib/ConfigOperations.cs
src/ApiService/ApiService/onefuzzlib/Creds.cs
src/ApiService/ApiService/onefuzzlib/LogAnalytics.cs
src/ApiService/ApiService/onefuzzlib/Storage.cs
src/ApiService/ApiService/onefuzzlib/VmssOperations.cs
src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs
src/ApiService/ApiService/packages.lock.json
src/ApiService/FunctionalTests/FunctionalTests.csproj
src/ApiService/FunctionalTests/TestPool.cs
src/ApiService/FunctionalTests/TestProxy.cs
src/ApiService/FunctionalTests/TestScaleset.cs
src/ApiService/FunctionalTests/packages.lock.json
src/ApiService/IntegrationTests/packages.lock.json
src/ApiService/Tests/packages.lock.json

The existing versions of these libraries have dependencies on packages with known vulnerabilities.
Updating the ADO packages fixes the following:
- `Newtonsoft.Json` (High) https://github.com/advisories/GHSA-5crp-9r3c-p9vr
- `System.Data.SqlClient` (Moderate) https://github.com/advisories/GHSA-8g2p-5pqh-5jmc
- `System.Drawing.Common` (Critical) https://github.com/advisories/GHSA-rxg9-xrhp-64gj
Updating the Identity packages fixes the following:
- `System.Security.Cryptography.Xml` (Moderate) https://github.com/advisories/GHSA-2m65-m22p-9wjw
Updating the System.Text.RegularExpressions package fixed:
- `System.Text.RegularExpressions` (High) https://github.com/advisories/GHSA-cmhx-cq75-c4mj
Updating the System.Net.Http package (in test project) fixed:
- `System.Net.Http` (High) …

Update .NET libraries which have security problems in transitive dependencies

---

src/ApiService/ApiService/onefuzzlib/Defs.cs

Fixes #2955.
Confirmed that [the Python version had `unique_inputs` here](https://github.com/microsoft/onefuzz/blob/d79e6d9864f0911b8709c52bf21b957a2ba98a48/src/api-service/__app__/onefuzzlib/tasks/defs.py#L343-L352) so this is a bug introduced during the port.

UniqueReports should be UniqueInputs in LibFuzzer merge task

---

.github/workflows/ci.yml
global.json

Rather than specifying this in `ci.yml`, specify it in the `global.json` file. This allows us to share the version amongst several workflows (and ADO pipelines) without needing to synchronize them.

Use global.json to specify .NET version

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock
src/utils/telemetry-stats/Cargo.lock

In Component Governance we have a bunch of crates which are consumed twice under different versions in the `agent` and `proxy-manager` components. Try to unify some of these to reduce the overall dependency count (and potentially help with build times).

Unify some crate versions

---

src/ApiService/IntegrationTests/IntegrationTests.csproj
src/ApiService/IntegrationTests/packages.lock.json

Noticed this in Component Governance: We are using multiple versions of xunit in the C# projects; bump IntegrationTests so we are only using one.

Use one version of xunit

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

Addressing CVE-2022-31394/https://github.com/advisories/GHSA-x477-xp89-wc9r

Bump Hyper to 0.14.25

---

src/ApiService/ApiService/Functions/AgentCommands.cs
src/ApiService/ApiService/Functions/Node.cs
src/ApiService/ApiService/onefuzzlib/NodeMessageOperations.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs
src/ApiService/IntegrationTests/AgentCommandsTests.cs

Closes #2964 
* Added support for maxPerPage in ORM
* Rename `GetMessage` to `GetMessages` in `NodeMessageOperations`
* Created a new `GetMessage` that only queries one message from the DB using the new maxPerPage
* Add a test
Added a test + checkpr

Add maxPerPage to ORM

---

.github/workflows/ci.yml
src/agent/Cargo.lock
src/agent/coverage/examples/coverage.rs
src/agent/onefuzz-agent/src/agent.rs
src/agent/onefuzz-agent/src/agent/tests.rs
src/ci/agent.sh
src/ci/rust-prereqs.sh

The coverage code is not currently exercised by any test.
* Add a test to the `coverage` example so that it can run in PR builds.
* Specify `--all-targets` so that example tests are run.
* Install and use [`nextest`](https://nexte.st/) instead of the standard test runner.
* This will parallelize test runs across binaries so the overall test run is faster.
* Make sleep duration of agent configurable and reduce it in the test run so that it doesn't wait for 30 seconds.

Add basic test for `coverage` example and library

---

src/agent/coverage/examples/cobertura.rs
src/agent/coverage/src/cobertura.rs
src/agent/coverage/src/source.rs

Closes #2824. ReportGenerator (apparently) does not use this information, but I noticed that it was missing when using PyCobertura to generate a report.

Include coverage percentage in Cobertura reports

---

src/agent/debuggable-module/src/windows.rs

On Windows, label symbols (see [here](https://docs.rs/pdb/latest/pdb/struct.LabelSymbol.html), [here](https://github.com/microsoft/microsoft-pdb/blob/0fe89a942f9a0f8e061213313e438884f4c9b876/include/cvinfo.h#L2859)) are used to extend the initial set of basic block entrypoint offsets, augmenting function entrypoints. We expect these labels to describe instruction locations, and never procedure-local data or tables.
In practice, this doesn't always hold. We may be able to re-enable this feature in the future, but we'll need a reliable procedure for identifying true code labels (dereferencing to an x86 instruction is insufficient), so disable this hinting for now.

Don't consume `S_LABEL` symbols from PDBs

---

src/agent/debuggable-module/src/loader.rs

Noticed this while looking at the coverage code.
As of: https://github.com/Manishearth/elsa/pull/37

Tiny PR: elsa::sync::FrozenMap now implements Default

---

src/cli/onefuzz/templates/libfuzzer.py

Because `--check_fuzzer_help` is a positive flag (defaults to `True`), there is no way to change it to `False`, because specifying it on the command line sets it to `True`. Change the flag to a negative one instead, named `--no_check_fuzzer_help`.

Change `--check_fuzzer_help` to `--no_check_fuzzer_help`

---

src/ci/check-dependencies.sh

This should make the script more robust against spurious changes like the failure here: https://github.com/microsoft/onefuzz/actions/runs/4802499456/jobs/8546032320?pr=3056

Make dependencies check lowercase module names

---

src/agent/onefuzz-task/src/tasks/task_logger.rs
src/agent/onefuzz-telemetry/src/lib.rs

Tweaking some of the parameter in the `task_logger` to alleviate the issue #3065
- Increase the size of the broadcast queue from 100 to 5000
- Increase the number of messages consumed by the task_logger from 100 to 10000
- decrease the period between logging from 1 min to 20s
- decrease the polling interval from 5s to 3s
closes #3065

Tweaking some of the parameter for the logging

---

src/agent/onefuzz-agent/src/validations.rs
src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer/common.rs
src/agent/onefuzz/src/libfuzzer.rs

Closes #2862 by brute force.
We’ve seen cases where it takes some time for an executable with a KnownDlls override to actually work after the node is restarted; thus, we now allow verification to take some time (currently up to a minute) to validate that a libfuzzer-based fuzzer actually works.

Allow libfuzzer verification to retry

---

src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs
src/ApiService/ApiService/onefuzzlib/notifications/GithubIssues.cs

Closes #3040 
Includes exception information when validation for a notification config fails.

Include exception information

---

src/agent/onefuzz/src/az_copy.rs

Closes #3071 
Fix the typo in the azcopy parameter name and set the default value to true. 

Fix typo in parameter name and set default value to true.

---

src/ApiService/ApiService/onefuzzlib/Events.cs
src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs
src/ApiService/IntegrationTests/EventsTests.cs

Our user info serializer fails when reading. We know though, that reading from the events container (which is controlled by onefuzz and only written to by onefuzz_ is safe. So this PR adds a special case when deserializing events from the events container.
Added integration test that specifically exercises the failing code path.

Deserialize user info when pulling from blob

---

src/ApiService/ApiService/Functions/AgentEvents.cs
src/agent/onefuzz-agent/build.rs
src/agent/onefuzz-task/build.rs
src/proxy-manager/build.rs

This PR updates the onefuzz agent version to generate a version that matches the service side. The version format was changed in #2925
closes #3092

Match the agent version to the server

---

src/ApiService/ApiService/Functions/ReproVmss.cs
src/ApiService/ApiService/Log.cs

Closes #3062 by adding an event to track this information; we can see from Application Insights logs how often the Function is invoked but at the moment do not have a way to distinguish between multiple users.
This (obviously) does not do anything about general feature usage tracking, as we are addressing a shorter-term need.

Add an event for Repro VM creation

---

src/ApiService/ApiService/Functions/AgentRegistration.cs
src/ApiService/ApiService/OneFuzzTypes/Enums.cs
src/ApiService/ApiService/TestHooks/NodeOperationsTestHooks.cs
src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs

Add a reason when deleting nodes. This will help us understand circumstances that lead to task being stopped while running

Add more context to the deletion of nodes

---

src/cli/onefuzz/templates/libfuzzer.py

Address this error when running the setup script:
```
sudo apt-get install -y qemu-user g++-aarch64-linux-gnu libasan5-arm64-cross
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 9364 (dpkg)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
Solution from [here](https://askubuntu.com/a/1371734/216901); this option is present in Ubuntu 20.04 and later, which we use.

Increase lock wait timeout for `qemu_user` setup script

---

src/cli/onefuzz/templates/libfuzzer.py

Allow use of `readonly_inputs` for `qemu_user` template

---

src/agent/Cargo.lock
src/agent/onefuzz-agent/Cargo.toml
src/agent/onefuzz-task/Cargo.toml

Dependabot is trying to do this in #3121 #3122 #3124 but failing since they all need to be updated at the same time.

Bump azure_* crates to 0.12

---

src/ci/rust-prereqs.sh

CI builds have been broken by https://github.com/bluejekyll/enum-as-inner/issues/98. Try using `--locked` when setting up our pre-reqs so that we get the versions of the dependencies which the executables have been released (and presumably built) with.

Use --locked when installing Rust pre-reqs

---

src/ApiService/ApiService/Functions/AgentCanSchedule.cs
src/ApiService/ApiService/onefuzzlib/NodeOperations.cs

Fixes a bug where we return `OneFuzzResult.Ok` even if applying scale in protection wasn't OK.
* Only return OK if acquiring scale-in protection was successful
* Add metrics
Will be validating in check-pr

Fix bug for scale-in protection

---

docs/webhook_events.md
src/ApiService/ApiService/Functions/AgentEvents.cs
src/ApiService/ApiService/Functions/Tasks.cs
src/ApiService/ApiService/Functions/TimerTasks.cs
src/ApiService/ApiService/OneFuzzTypes/Enums.cs
src/ApiService/ApiService/onefuzzlib/JobOperations.cs
src/ApiService/ApiService/onefuzzlib/TaskOperations.cs
src/ApiService/IntegrationTests/AgentEventsTests.cs
src/pytypes/onefuzztypes/enums.py

- Added a reason field to MarkStopping
- Added a new ErrorCode `TASK_CANCELLED` to differentiate cancellation from failure.
- If a task is cancelled all dependent task are cancelled
closes #3147

Include a reason when a task has never started

---

.devcontainer/devcontainer.json
src/cli/onefuzz/api.py

Add a command to the CLI for downloading the files to locally repro a crash
Command:
`onefuzz repro get_files <report_container> <report_name> [--output_dir <path>] [--include-setup]`
Ran the command with correct and invalid arguments.

Downloading files to locally repro crashes

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Somehow using the Microsoft package we are ending up with a broken install of `dotnet`. Change to use the Ubuntu-supplied version instead.
Also go ahead and update the devcontainer config to conform to the new standard.

Fix install of dotnet in devcontainer

---

src/agent/onefuzz-task/src/tasks/coverage/generic.rs
src/agent/onefuzz-telemetry/src/lib.rs

When we record coverage, if any of the files fail (e.g. due to timeouts during coverage recording), then we fail the whole process.
Instead, make coverage recording best-effort: if any files fail then we continue to record coverage using the other files. A warning is printed that we can monitor for any ongoing problems.
Closes #3041

Make coverage-recording errors non-fatal

---

src/agent/Cargo.toml

Include debug info in the release binaries to [improve backtraces and debuggability](https://doc.rust-lang.org/cargo/reference/profiles.html#build-dependencies).

Include debug info in the release binaries to improve backtraces and debuggability

---

src/agent/coverage/examples/record.rs

Fail fast if the user passes an input corpus directory, but doesn't include an input marker (`@@`) in the command to execute. Before, this resulted in either an immediate spurious exit or, in the case of libFuzzer targets, a guaranteed timeout.

Require input marker in args when given corpus dir

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

CI is failing because of this advisory: https://rustsec.org/advisories/RUSTSEC-2023-0044

Bump openssl crate

---

docs/troubleshooting.md
docs/unmanaged-nodes.md
src/agent/onefuzz-agent/src/validations.rs

Document how to use the validation tools

---

src/agent/coverage/examples/record.rs
src/agent/coverage/src/binary.rs
src/agent/coverage/src/record.rs
src/agent/coverage/src/record/linux.rs
src/agent/coverage/src/record/windows.rs

Closes #3216.
This PR does _not_ implement caching or analysis reuse in the OneFuzz `coverage` task, but is a preqreq for doing so.

Add cache for coverage locations and debuginfo

---

src/ApiService/ApiService/onefuzzlib/Secrets.cs
src/ApiService/Tests/OrmTest.cs

We were assuming the data stored in keyvault is json but we sometimes store strings as well. When we would attempt to deserialize the string, we'd get an error that it's invalid json.

Handle the case where the secret is not serialized as json

---

.github/workflows/ci.yml

There is no auto-detection for ARM64 in the Codecov action, so we must set it explicitly.

Enable codecov for ARM64

---

src/ApiService/ApiService/Functions/Download.cs
src/ApiService/ApiService/onefuzzlib/Containers.cs
src/ApiService/ApiService/onefuzzlib/Events.cs
src/ApiService/ApiService/onefuzzlib/Extension.cs
src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs
src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs
src/ApiService/IntegrationTests/DownloadTests.cs

This allows us to generate 404s when someone attempts to download from a non-existent container. At the moment we generate a 500 which isn't useful, or very good looks-wise.

Better errors from Download: Make GetFileSasUrl nullable

---

.github/workflows/ci.yml

When .NET appends `VersionSuffix` to the `InformationalVersion` string, it appends it with a `-` separator. For consistency with the other version strings (and semver), we want it appended with a `+` separator. This is now supported by using the explicit `SourceRevisionId` property instead of `VersionSuffix`.

Change how Git hash is appended to .NET version string for pre-release builds

---

src/agent/Cargo.toml
src/ci/agent.sh

I noticed these were getting very big and impacting our CI time due to copying huge artifacts. Presumably this would be slowing down copying in the live environment as well.
Two changes have been made:
- Use `debug=1` instead of `debug=true` (equivalent to `debug=2`); this should be sufficient for our needs
- On Linux, compress debug information after building
| Binary | Before | with `debug=1` | after compression |
|--|--:|--:|--:|
| onefuzz-agent (Linux) | 170 MB | 83 MB | 30 MB |
| onefuzz-task (Linux) | 284 MB  | 134 MB | 46 MB |
| onefuzz_agent.pdb (Windows) | 89 MB | 42 MB | — |
| onefuzz_task.pdb (Windows) | 150 MB | 63 MB | — |
| onefuzz-deployment.zip | 364 MB | 286 MB | 285 MB |
Overall the compressed `release-artifacts` reduced from 374 → 297 MB.
Build speed improvements …

Shrink published Rust debug info

---

.github/workflows/ci.yml

We build integration test executables every time even when they rarely change; so only build them if they change.

Cache integration test artifacts

---

src/ci/agent.sh

This further shaves off the sizes from #3247:
- `onefuzz-agent`: 30 MB → 28 MB
- `onefuzz-task`: 46 MB → 42 MB

Remove .debug_pubnames and .debug_pubtypes sections from agent binaries

---

src/ApiService/ApiService/HttpClient.cs

Try this out as an experiment to see if it helps with Webhooks occasionally failing to send messages

switch to default HttpCompletion, which is ResponseRead

---

src/agent/onefuzz/src/monitor/tests.rs

Increase the test timeout for directory monitor tests as we are seeing this fail fairly often with the ARM64 builds ([see, e.g.](https://github.com/microsoft/onefuzz/actions/runs/5416711609/jobs/9846801082)).

Increase test timeout

---

src/agent/Cargo.lock
src/proxy-manager/Cargo.lock

This is breaking the build via `cargo deny`.

Get rid of yanked `hermit-abi` versions

---

src/ApiService/ApiService/ApiService.csproj
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs
src/ApiService/ApiService/onefuzzlib/notifications/GithubIssues.cs
src/ApiService/ApiService/onefuzzlib/notifications/JinjaTemplateAdapter.cs
src/ApiService/ApiService/onefuzzlib/notifications/NotificationsBase.cs
src/ApiService/ApiService/packages.lock.json
src/ApiService/IntegrationTests/AdoTests.cs
src/ApiService/IntegrationTests/packages.lock.json
src/ApiService/Tests/packages.lock.json

Trim System.Title when longer than 128 characters. Trims some extra characters to append the first 8 chars of the title hash for collision avoidance.
We probably want to write the full System.Title value somewhere in the bug so that the trimmed information isn't just lost.
https://github.com/microsoft/onefuzz/issues/3015

Trim System.Title if length is > 128

---

src/agent/Cargo.lock
src/agent/onefuzz-task/Cargo.toml
src/agent/onefuzz-task/src/tasks/coverage/generic.rs

Use debuginfo cache

---

src/ApiService/ApiService/Functions/Jobs.cs
src/ApiService/ApiService/Functions/Node.cs
src/ApiService/ApiService/Functions/TimerRetention.cs
src/ApiService/ApiService/OneFuzzTypes/Events.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/OneFuzzTypes/Responses.cs
src/ApiService/ApiService/OneFuzzTypes/Webhooks.cs
src/ApiService/ApiService/onefuzzlib/ReproOperations.cs
src/ApiService/ApiService/onefuzzlib/TaskOperations.cs
src/ApiService/ApiService/onefuzzlib/notifications/JinjaTemplateAdapter.cs
src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs
src/ApiService/FunctionalTests/1f-api/ApiClient.cs
src/ApiService/FunctionalTests/FunctionalTests.csproj
src/ApiService/FunctionalTests/packages.lock.json
src/ApiService/IntegrationTests/AdoTests.cs
src/ApiService/IntegrationTests/EventsTests.cs
src/ApiService/IntegrationTests/IntegrationTests.csproj
src/ApiService/IntegrationTests/JobsTests.cs
src/ApiService/IntegrationTests/packages.lock.json
src/ApiService/Tests/OrmModelsTest.cs
src/ApiService/Tests/OrmTest.cs
src/ApiService/Tests/TemplateTests.cs
src/ApiService/Tests/Tests.csproj
src/ApiService/Tests/packages.lock.json

Starts to address #3158.
Rather than storing the UPN and then removing it later, do not store it in the first place.
I found one problem while working on this which was that `UserInfo` was not actually stored on `Job`, so address that as well. This was because properties which are not constructor parameters are not stored by the ORM, so I've also removed other examples from `Task` and `Node` and have them only on the response types.
---
Also started to simplify the ORM roundtripping tests; remove the custom equality comparison and instead simply compare JSON-serialized values. Rely on the FsCheck automatic generation of values where it works, rather than writing a custom Arbitrary which does the same thing.

UPN changes/fixes

---

src/ApiService/ApiService/Functions/Containers.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/OneFuzzTypes/ReturnTypes.cs
src/ApiService/ApiService/onefuzzlib/Containers.cs
src/ApiService/ApiService/onefuzzlib/Storage.cs
src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs
src/ApiService/ApiService/onefuzzlib/orm/Orm.cs
src/ApiService/IntegrationTests/ContainersTests.cs
src/ApiService/IntegrationTests/Fakes/TestContainers.cs
src/ApiService/IntegrationTests/Fakes/TestContext.cs
src/ApiService/IntegrationTests/PoolTests.cs
src/ApiService/IntegrationTests/TestLogTracer.cs

Closes #3156.
From now on, we will store additional information about containers in a table (`ContainerInformation`). This is populated when a container is created, or lazily when looking for a container we have not yet stored in the table.
Reads from this table are also cached in memory for a short period of time (currently 10 minutes).
The table is currently used to speed up lookups for containers across storage accounts; we round-robin creation of containers across multiple storage accounts to spread load, so when we read from a container we need to find what storage account it lives in.
The `ContainerInformation` table could also be used in future to store information about access control (see, e.g. #1419).

Cache FindContainer

---

src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs
src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs
src/ApiService/ApiService/onefuzzlib/notifications/GithubIssues.cs
src/ApiService/ApiService/onefuzzlib/notifications/JinjaTemplateAdapter.cs
src/ApiService/ApiService/onefuzzlib/notifications/NotificationsBase.cs

The [last fix for trimming System.Title](https://github.com/microsoft/onefuzz/pull/3284) wasn't much of a fix as it checked the pre-rendered System.Title length.
This PR fixes that issue by rendering the title in ConstructRenderer() and giving the rendered title a public accessor.
System.Title trim fix and some logging that happens when the title is too long.
Deployed changes to a manual instance and filed a bug that triggers the updated code.

Render System.Title before trying to trim

---

src/cli/onefuzz/backend.py

opentelemetry claims requests ~= 2.0 is not installed with the following message:
```
DependencyConflict: requested: "requests ~= 2.0" but found: "None"
```
This is false however, `requests` is installed and we should leave it up to pip to decide what's installed or not.

Fix 'missing' dependency

---

src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs

Add an info-level trace when trimming the System.Title.

Add extra logging when System.Title is too long

---

src/agent/LibFuzzerDotnetLoader/Program.cs

When `LibFuzzerDotNetLoader` loads DLLs that have dependencies, they are not currently resolved correctly, as sibling DLLs in the same directory are not considered. In order to do this, we need to provide a custom `AssemblyLoadContext`. This PR does so, based on the [dotnet core example code](https://learn.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support).
Validated with custom fuzzer implementation; we don't yet have a full test for this in check-pr.
Closes #3326.

Fix resolution of sibling .NET DLLs

---

src/agent/LibFuzzerDotnetLoader/LibFuzzerDotnetLoader.csproj
src/ci/dotnet-fuzzing-tools.ps1
src/ci/dotnet-fuzzing-tools.sh

This reverts commit 25f125748dc0352d66385281e7a4468621233739.
The change broke the libfuzzer dotnet template (I could have sworn I validated first with check-pr but…)
Two things didn't work:
1. the path to the LibFuzzerDotNetLoader needed to change; I attempted to fix this in #3324 
2. minidumps weren't being captured, for an unknown reason. I haven't figured out why yet, thus I'm going to simply revert the change so we have this working for the next release.

Revert "Update packaging of LibFuzzerDotNetLoader (#3248)"

---

src/cli/onefuzz/api.py

https://github.com/microsoft/onefuzz/issues/3338
`onefuzz repro get_files` only handles `reports` and not `regression_reports`.
Adds logic for checking that the fields expected in a normal report exist before falling back on fields expected from a regression report. An error is logged otherwise.

Update `repro get_files` to handle regression reports

---

src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs

Closes #3339. RegressionReports don't always include an inputblob since they reference existing

Populate InputBlob when possible

---

src/ApiService/ApiService/Functions/Jobs.cs
src/ApiService/ApiService/OneFuzzTypes/Model.cs
src/ApiService/ApiService/OneFuzzTypes/Responses.cs
src/ApiService/IntegrationTests/JobsTests.cs
src/cli/onefuzz/api.py
src/pytypes/onefuzztypes/models.py
src/pytypes/onefuzztypes/requests.py

`onefuzz jobs get <job_id> --with_tasks` now include the full task information
closes #3330

Implement with_tasks option to expand the task information

---

src/ApiService/ApiService/Functions/QueueFileChanges.cs
src/ApiService/ApiService/OneFuzzTypes/Enums.cs
src/ApiService/ApiService/TestHooks/NotificationOperationsTestHooks.cs
src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs

Requeue ado notification on ff

---

src/agent/onefuzz-task/src/main.rs

The default behavior or the runtime is [wait for all spawned work](https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#shutdown) to be done before exiting. This was causing the task to hang when  exiting. 
This change adds a force shutdown at the end of the main function of the task.
closes #3377

Forcefully shut down the runtime before existing the main task

---

src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs

Closes #3382
Adds duplicate checking for `"Microsoft.VSTS.Common.ResolvedReason"`

Handle another duplicate field

---

src/ApiService/ApiService/Log.cs

Give precedence to the tags produced by log message over the added tags prior to the call with the clashing name to avoid the following issues:

fix tag shadowing

---

src/agent/.rustfmt.toml
src/agent/Cargo.toml
src/agent/atexit/Cargo.toml
src/agent/debugger/Cargo.toml
src/agent/input-tester/Cargo.toml
src/agent/libclusterfuzz/Cargo.toml
src/agent/onefuzz-agent/Cargo.toml
src/agent/onefuzz-agent/src/heartbeat.rs
src/agent/onefuzz-agent/src/main.rs
src/agent/onefuzz-agent/src/panic.rs
src/agent/onefuzz-agent/src/scheduler.rs
src/agent/onefuzz-task/Cargo.toml
src/agent/onefuzz-task/src/tasks/coverage/generic.rs
src/agent/onefuzz-telemetry/Cargo.toml
src/agent/onefuzz-telemetry/src/lib.rs
src/agent/onefuzz/Cargo.toml
src/agent/onefuzz/src/auth.rs
src/agent/onefuzz/src/az_copy.rs
src/agent/onefuzz/src/blob/url.rs
src/agent/onefuzz/src/expand.rs
src/agent/onefuzz/src/triage.rs
src/agent/stacktrace-parser/Cargo.toml
src/agent/storage-queue/Cargo.toml
src/agent/win-util/Cargo.toml
src/integration-tests/libfuzzer-rust/Cargo.toml
src/integration-tests/libfuzzer-rust/fuzz/Cargo.toml
src/proxy-manager/Cargo.lock
src/proxy-manager/Cargo.toml
src/utils/telemetry-stats/Cargo.toml

Changes mostly done by `cargo fix --edition`.

Update Rust edition to 2021 across all crates

---

src/agent/onefuzz/src/monitor.rs

Fixing an error encountered in prod:
```
task failed. exit_status:ExitStatus { Code = 1, Signal = , Success = False }
ERROR [onefuzz_task::managed::cmd] error running task: Failure in monitor_inputs
Caused by:
0: checking metadata for file
1: The system cannot find the file specified. (os error 2)
```

Tolerate errors when attempting to fetch metadata for some `CreateKind`s

---

src/agent/cobertura/src/lib.rs
src/agent/coverage/examples/cobertura.rs
src/agent/coverage/examples/record.rs
src/agent/coverage/src/cobertura.rs
src/agent/coverage/src/source.rs
src/agent/coverage/tests/snapshot.rs
src/agent/onefuzz-file-format/src/coverage/binary.rs
src/agent/onefuzz-file-format/src/coverage/binary/v1.rs
src/agent/onefuzz-file-format/src/coverage/source.rs
src/agent/onefuzz-file-format/src/coverage/source/v1.rs
src/agent/onefuzz-task/src/tasks/coverage/generic.rs

The Coverage file was loading the output of the coverage in memory before writing it to the output file. 
This could cause an increase in memory consumption. This change updates the logic to serialize the output directly in the output file without loading it in the memory.
closes #3420

Deserialize the coverage files directly into the output files

---

src/ApiService/ApiService/onefuzzlib/Defs.cs
src/agent/onefuzz-task/src/local/libfuzzer_fuzz.rs
src/agent/onefuzz-task/src/local/template.rs
src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer/common.rs
src/agent/onefuzz-task/src/tasks/fuzz/supervisor.rs

Make crashdumps optional in task definition so that old CLI clients are not rejected.

Make crashdumps optional in config

---

.devcontainer/devcontainer.json

Microsoft C# vs code extension is broken with latest release. Enabling omnisharp as a workaround. 
See: https://github.com/dotnet/vscode-csharp/issues/6218#issuecomment-1692647319

Use `omnisharp` language features.

---

src/ApiService/ApiService/OneFuzzTypes/Enums.cs
src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs
src/ApiService/Tests/TreePathTests.cs
src/pytypes/onefuzztypes/enums.py

Adds validation against the path naming restrictions defined in https://learn.microsoft.com/en-us/azure/devops/organizations/settings/about-areas-iterations?view=azure-devops#naming-restrictions
The newly added checks each have their own error message for their violation, so, for example, users that delimit their paths with a forward slash instead of a backslash will get a message saying:
"Area Path "Foo/Bar" is invalid. "Foo/Bar" contains an invalid character (\ / : * ? " < > | ; # $ * { } , + = [ ])."
"Make sure that the path is separated by backslashes (\\) and not forward slashes (/)."

Improve area/iteration path validation

---

src/ApiService/ApiService/Functions/Jobs.cs
src/ApiService/ApiService/OneFuzzTypes/Events.cs

Add this info so that developers and users can track which version of OneFuzz a job was submitted with.
Logs don't indicate any failures after using the cli to create a new job against my own instance.

Add OneFuzz service version to job created events

---

src/agent/onefuzz-task/src/check_for_update.rs
src/agent/onefuzz-task/src/main.rs
src/agent/onefuzz-task/src/managed/cmd.rs

Both the bin and lib for `onefuzz-task` include the same modules, which means some code is being compiled twice, and this leads to confusing errors if you update the bin code and not the lib code (e.g. adding new modules or something similar).
Instead, make the bin code depend on the lib code.
Also remove `extern crate` and `macro_use`, which are an older way of doing things. Macros are simply imported now.

Fixup onefuzz-task dependencies

---

src/ApiService/ApiService/ApiService.csproj
src/ApiService/ApiService/OneFuzzTypes/Enums.cs
src/ApiService/ApiService/Program.cs
src/ApiService/ApiService/onefuzzlib/Versions.cs
src/ApiService/ApiService/packages.lock.json
src/ApiService/FunctionalTests/Auth.cs
src/ApiService/FunctionalTests/FunctionalTests.csproj
src/ApiService/FunctionalTests/TestContainer.cs
src/ApiService/FunctionalTests/TestInfo.cs
src/ApiService/FunctionalTests/TestNode.cs
src/ApiService/FunctionalTests/TestPool.cs
src/ApiService/FunctionalTests/TestProxy.cs
src/ApiService/FunctionalTests/TestScaleset.cs
src/ApiService/FunctionalTests/TestTasks.cs
src/ApiService/FunctionalTests/TestVersionCheckMiddleware.cs
src/ApiService/FunctionalTests/packages.lock.json
src/ApiService/IntegrationTests/packages.lock.json
src/ApiService/Tests/packages.lock.json
src/cli/onefuzz/backend.py
src/pytypes/onefuzztypes/enums.py

Adds middleware to the ApiService that checks for two headers: `cli-version` and `strict-version`
If both headers are present _and_ the `strict-version` is set to true, then the middleware will compare the supplied version with the service version and immediately send back a 400 response to requests with out of date versions.
On the CLI end, this feature is opted into by setting the `ONEFUZZ_STRICT_VERSIONING` environment variable to true (case insensitive).
Added unit tests for the following cases:
(Both valid and invalid values are tested for each case, where applicable)

Add middleware for optional strict CLI version checking

---

src/cli/onefuzz/debug.py

A few facets to this PR:
1. Add an optional `--out_dir` parameter to specify where to download the logs.
2. Deprecate the `--last` and `--all` options, making them no-ops.
3. Update the behavior to now always download all available logs (see #3572).
4. Update the logs to the console to reflect the new behavior.
Local validation

Make `debug logs get` behave more intuitively

---

src/ApiService/ApiService/Functions/QueueFileChanges.cs
src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs

Move event-skipping behaviour earlier so it is also performed for the retention policy handler. This will help churn through these events faster.

Shortcut file-added earlier

---

src/cli/examples/domato.py
src/cli/examples/honggfuzz.py
src/cli/examples/llvm-source-coverage/source-coverage-libfuzzer.py
src/cli/examples/llvm-source-coverage/source-coverage.py
src/cli/onefuzz/api.py
src/cli/onefuzz/templates/__init__.py
src/cli/onefuzz/templates/afl.py
src/cli/onefuzz/templates/libfuzzer.py
src/cli/onefuzz/templates/ossfuzz.py
src/cli/onefuzz/templates/radamsa.py
src/cli/onefuzz/templates/regression.py
src/cli/tests/test_template_helper.py

- Decoupled the job creation from the JobHelper initialization
- Move the job creation after the all the files have been uploaded
closes #3563

Create job after the upload is done
