docs/command-replacements.md, docs/known-issues.md
Removing internal MSR work items
Removes MSR internal work items
N/A
=> remove internal work item refs

src/deployment/data_migration.py, src/deployment/deploy.py
added new option to the deployment script to specify a migration to apply during the deployment
- Deployed onefuzz 0.9
- Ran a couple of jobs
- Applied the migration when upgrading to 1.0
- Verified that the task created in 0.9 can still be queried via the cli 
- Verified that the repro machine can me created from the reports generated in 0.9
=> Data migration in the deployment script

docs/terminology.md
Defines pool, node, and scalesets.
Defines pool, node, and scalesets.
N/A
=> add definitions for pool, node, and scaleset

src/deployment/requirements.txt
=> fixing deployment script requirements

src/api-service/__app__/agent_can_schedule/__init__.py, src/api-service/__app__/agent_can_schedule/function.json, src/api-service/__app__/onefuzzlib/pools.py, src/pytypes/onefuzztypes/models.py, src/pytypes/onefuzztypes/requests.py, src/pytypes/onefuzztypes/responses.py
=> can schedule endpoint

src/agent/onefuzz-supervisor/src/config.rs, src/api-service/__app__/agent_registration/__init__.py, src/api-service/__app__/onefuzzlib/pools.py, src/pytypes/onefuzztypes/requests.py
=> reimage outdated nodes

src/api-service/__app__/agent_events/__init__.py, src/api-service/__app__/agent_registration/__init__.py, src/api-service/__app__/onefuzzlib/pools.py
=> fix formatting

src/api-service/__app__/agent_events/__init__.py, src/api-service/__app__/agent_registration/__init__.py, src/api-service/__app__/onefuzzlib/pools.py, src/cli/examples/azure-functions-example/README.md, src/cli/examples/azure-functions-example/host.json, src/cli/examples/azure-functions-example/info/__init__.py, src/cli/examples/azure-functions-example/info/function.json, src/cli/examples/azure-functions-example/requirements.txt
Adds an example consumer of the SDK
Adds an extremely simple onefuzz SDK demo using Azure Functions
Deployed it to an azure functions via `func azure functionapp publish onefuzz-api-example --python`
=> Example sdk in azure functions

src/api-service/__app__/agent_events/__init__.py, src/api-service/__app__/agent_registration/__init__.py, src/api-service/__app__/onefuzzlib/pools.py, src/api-service/__app__/tasks/__init__.py, src/pytypes/onefuzztypes/models.py
This change add a new property to the task entity to show the node assignment
create a job then query a task from the cli and observe that an  new property called nodes contains the node assignments
=> Adding node assignment to the task entity

src/runtime-tools/win64/onefuzz-run.ps1
In the case the agent dies, we should restart it.  
(note, systemd auto-restarts the agent on linux)
=> run supervisor/repro in a loop

src/api-service/__app__/agent_commands/__init__.py, src/api-service/__app__/agent_registration/__init__.py
deployed and manually tested command get and delete
=> reading command from the body instead of URI

src/pytypes/onefuzztypes/requests.py
Fixing `unauthorized agent` and `version field required`. My guess is that PR #33 introduced the field and recent version changes are causing it.
However fixing it, doesn't resolve the next issue where tasks are not assigned to nodes.
I first receive token verification unauthorized agent and after a while version field required
Manual testing.
=> Updating the default version value

src/api-service/__app__/agent_can_schedule/__init__.py, src/api-service/__app__/agent_events/__init__.py, src/api-service/__app__/agent_registration/__init__.py, src/api-service/__app__/node/__init__.py, src/api-service/__app__/onefuzzlib/azure/queue.py, src/api-service/__app__/onefuzzlib/azure/vmss.py, src/api-service/__app__/onefuzzlib/pools.py, src/api-service/__app__/onefuzzlib/tasks/main.py, src/api-service/__app__/requirements.txt, src/api-service/__app__/scaleset/__init__.py, src/api-service/__app__/scaleset_events/__init__.py, src/pytypes/onefuzztypes/models.py
This moves the node state management in the hands of the agent, and we tell the agent when to shut down, etc.
=> refactor node state to fully put the agent in charge

src/agent/Cargo.lock, src/agent/debugger/Cargo.toml, src/agent/debugger/src/dbghelp.rs, src/agent/debugger/src/debugger.rs, src/agent/debugger/src/stack.rs
Update to match the latest of the internal version.
=> Update Windows debugger crate

src/deployment/deploy.py, src/deployment/requirements.txt
Addresses two initial deployment errors:
1. Handles a race condition between when an app registration has completed and when a password can be created for it. 
2. Addresses the incompatible python library versions from the deployment.  Fixes #137 
1. Deploy to a new instance.  
2. Verify there are now python prereq conflicts.
=> address initial deploy errors

src/cli/onefuzz/api.py
The `_delete_component` signature is different.
=> fix incorrect resetting of components

src/cli/onefuzz/api.py
Adds user confirmation to container reset added in #198
=> add user confirmation to container reset

src/ci/onefuzztypes.sh
In #243, I observed that `pytypes` tests were not running. Adding it in the pipeline in this PR
=> Running pytypes tests in pipeline

src/deployment/registration.py
=> fixing exception when instantiating GraphQueryError

src/deployment/requirements.txt
=> pin urllib3 for deployment prereqs

contrib/deploy-onefuzz-via-azure-devops/deploy-onefuzz.yml
=> Add `--upgrade` to the Azure Devops deployment pipeline

.github/workflows/ci.yml, contrib/deploy-onefuzz-via-azure-devops/deploy-onefuzz.yml, src/ci/agent.sh
This PR adds PDBs for the supervisor & agent binaries.
Fixes #260
=> add symbols for windows agents

docs/webhooks.md
Fix broken markdown link in documentation
=> fix webhook events doc link

src/api-service/__app__/jobs/__init__.py, src/api-service/__app__/onefuzzlib/repro.py, src/api-service/__app__/repro_vms/__init__.py, src/pytypes/onefuzztypes/models.py
This adds information about the user that created a job or repro VM to the respective resources.
This expands on the addition made to tasks in #303.
=> Add user_info to Jobs & Repro

.github/workflows/ci.yml, src/deployment/data_migration.py, src/deployment/deploy.py, src/deployment/mypy.ini, src/deployment/registration.py
Adds black, isort, and mypy to the deployment tools.
=> Add linting to deployment tools

src/api-service/__app__/onefuzzlib/azure/creds.py
PR #353 provided the wrong app-insights key.  This uses the instance-specific app insights key.
=> use the correct instrumentation key

src/proxy-manager/src/config.rs
This fixes an issue raised in the latest version of clippy.
=> fix clippy issue

src/agent/onefuzz/data/asan-odr-violation.txt, src/agent/onefuzz/src/asan.rs
=> support ASAN odr-violation outputs

src/api-service/__app__/onefuzzlib/extension.py, src/api-service/__app__/onefuzzlib/pools.py, src/runtime-tools/linux/setup.sh, src/runtime-tools/win64/setup.ps1
Adds a scaleset specific setup script, which allows us to save the scaleset based SSH keys into the VM on setup.
=> Re-add windows ssh key

src/ci/aflpp.sh
Update the version of AFL++ provided in OneFuzz to 3.00b, which was released yesterday.
=> upgrade AFL++ to 3.00b

src/api-service/__app__/onefuzzlib/tasks/scheduler.py
By comparing container names rather than SAS urls, this removes a race condition that prevented co-locatable tasks from being co-located.
=> compare containers rather than SAS urls when building worksets

docs/getting-started.md
=> Add missing prerequisites to the Getting Started guide

src/agent/onefuzz-supervisor/src/work.rs
=> Update QueueClient with latest SAS URL upon renewing registration

src/api-service/__app__/onefuzzlib/pools.py
=> remove early-exit from cleanup_nodes that broke dead node cleanup

docs/command-replacements.md
This expands the documentation to demonstrate how nested lists are handled in practice, as well as to provide examples for how to deal with the nested list expansion.
=> Update expansion documentation to describe nested options as implemented

src/agent/onefuzz-agent/src/tasks/analysis/generic.rs, src/agent/onefuzz-agent/src/tasks/merge/generic.rs
=> Expand tools_dir accessibility in variable expansion

docs/command-replacements.md, src/agent/onefuzz-agent/src/tasks/analysis/generic.rs, src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs, src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs, src/agent/onefuzz-agent/src/tasks/merge/generic.rs, src/agent/onefuzz/src/expand.rs
Fixes #479 
Note, this is built on top of #480
=> Add task_id & job_id to variable expansion

src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
=> add logging to generic analysis task

docs/webhook_events.md, src/api-service/__app__/onefuzzlib/tasks/main.py, src/pytypes/extra/generate-docs.py, src/pytypes/onefuzztypes/events.py
=> add task config to all task events

src/cli/onefuzz/api.py, src/cli/onefuzz/azcopy.py, src/cli/onefuzz/backend.py, src/cli/onefuzz/debug.py, src/cli/onefuzz/templates/__init__.py
=> add `onefuzz containers files download_dir`

src/agent/coverage/src/block/windows.rs
Remove redundant `Result` wrapping flagged by the linter.
=> Rewrite redundant `Result` wraps

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
enable CodeQL pipeline on OneFuzz
=> add CodeQL pipeline

docs/webhook_events.md, src/api-service/__app__/onefuzzlib/events.py, src/api-service/__app__/queue_node_heartbeat/__init__.py, src/api-service/__app__/queue_task_heartbeat/__init__.py, src/pytypes/extra/generate-docs.py, src/pytypes/onefuzztypes/events.py
This adds node & task heartbeats and makes the event data available as a structured data in the logs.
=> add node & task heartbeat events

src/ci/aflpp.sh
Updates AFL++ to https://github.com/AFLplusplus/AFLplusplus/releases/tag/3.10c
=> update AFL++ to 3.10c

src/api-service/__app__/onefuzzlib/azure/containers.py, src/api-service/__app__/requirements.txt, src/cli/requirements.txt
Note, this makes use of the new feature, `ContainerClient.exists()` which models our existing mechanism for doing container existence checking.
=> upgrade azure-storage-blob to 12.8.0

docs/webhook_events.md, src/api-service/__app__/onefuzzlib/jobs.py, src/ci/onefuzztypes.sh, src/pytypes/extra/generate-docs.py, src/pytypes/onefuzztypes/events.py
=> Add job stopped task info

src/api-service/__app__/onefuzzlib/jobs.py, src/api-service/__app__/onefuzzlib/tasks/main.py
=> stop jobs once all tasks are stopped

src/agent/onefuzz-agent/src/local/common.rs
=> Fix parsing of list of synced dir

docs/webhook_events.md, src/pytypes/onefuzztypes/models.py
Expose the functionality from #591 to the python library
=> expose new minimized stack fields in the crash report model

src/agent/onefuzz-agent/src/local/generic_analysis.rs, src/agent/onefuzz-agent/src/tasks/analysis/generic.rs, src/agent/onefuzz/src/blob/url.rs
=> fix local generic analysis

contrib/deploy-onefuzz-via-azure-devops/Pipfile.lock
Update 3rd party dependencies required by the ADO deploy task.
=> update ADO deploy dependencies

src/agent/onefuzz-agent/src/local/tui.rs
specify the events we want, rather than the events we don't
=> invert the TUI event filter

src/agent/Cargo.lock, src/agent/coverage/Cargo.toml
Picks up some small bugfixes and panic removals.
=> Update `pdb` to 0.7

src/agent/coverage/src/report.rs
=> Increase visibility of coverage report fields

src/agent/onefuzz/src/syncdir.rs
=> explicitly ignore azcopy temporary files from directory monitoring

src/agent/coverage/examples/elf_sancov_tables.rs, src/agent/coverage/examples/pdb_sancov_tables.rs, src/agent/coverage/src/cache.rs, src/agent/coverage/src/elf.rs, src/agent/coverage/src/lib.rs
=> Try to use Sancov tables when analyzing ELF modules

src/agent/coverage/src/elf.rs, src/agent/onefuzz-agent/src/local/generic_analysis.rs, src/agent/onefuzz-agent/src/local/generic_generator.rs, src/agent/onefuzz-agent/src/local/libfuzzer_fuzz.rs, src/agent/onefuzz-agent/src/local/libfuzzer_merge.rs, src/agent/onefuzz-agent/src/local/tui.rs, src/agent/onefuzz-agent/src/tasks/heartbeat.rs, src/agent/onefuzz-agent/src/tasks/regression/generic.rs, src/agent/onefuzz-agent/src/tasks/regression/libfuzzer.rs, src/agent/onefuzz-agent/src/tasks/stats/afl.rs, src/agent/onefuzz-supervisor/src/config.rs, src/agent/onefuzz-telemetry/src/lib.rs, src/agent/stacktrace-parser/src/asan.rs, src/proxy-manager/Cargo.lock
This PR address the following new clippy issues:
https://rust-lang.github.io/rust-clippy/master/index.html#from_str_radix_10
https://rust-lang.github.io/rust-clippy/master/index.html#inconsistent_struct_constructor
https://rust-lang.github.io/rust-clippy/master/index.html#manual_flatten
=> address clippy issues in latest rust release

src/ci/onefuzztypes.sh, src/pytypes/extra/generate-docs.py
This uplifts functionality from #839 in a simplified fashion.
=> force ASCII generation of markdown document generation

docs/AADEntitites.md
Added a description of the configuration of azure AD entities
closes #875
=> Azure AD entities description

src/cli/onefuzz/azcopy.py, src/cli/onefuzz/backend.py
=> use azcopy for upload_dir

docs/command-replacements.md, src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
=> add setup_dir to generator task

src/cli/onefuzz/api.py, src/cli/onefuzz/job_templates/handlers.py, src/cli/onefuzz/template.py, src/cli/onefuzz/templates/__init__.py
=> add `onefuzz jobs containers delete JOB_ID`

src/deployment/registration.py
address the racing condition when authorizing an application by retrying 
closes #938
=> add retry logic to authorize application

src/agent/onefuzz-supervisor/src/coordinator.rs
This is primarily a refactoring of existing code to remove the get_request_builder and replace it with requiring the requests succeed through a try_clone.
This simplifies the logic as well as adds additional Anyhow based error context.
=> remove RequestBuilder abstraction in onefuzz-supervisor coordinator

src/api-service/__app__/onefuzzlib/azure/vmss.py
=> handle scaleset resize exceptions

src/api-service/__app__/onefuzzlib/workers/nodes.py
=> reimage/delete expired nodes even with the debug_keep_node flag

src/api-service/__app__/onefuzzlib/workers/scalesets.py
In a previous commit, reimage_queued was added to prevent reimaging a node while it is reimaging.  However, this means reimaging failures due to Azure issues don't finish reimaging.
This will reset the this flag allowing the node to reimage in the following cleanup cycle.
=> handle reimaging failures by resetting reimage_queued

src/api-service/__app__/onefuzzlib/secrets.py, src/api-service/__app__/requirements.txt
Note, this also removes azure-keyvault and azure-keyvault-keys which are
not used at this time.
=> update azure-keyvault-secrets to 4.3.0

src/agent/libclusterfuzz/data/parsed-traces/rust_ignores.json, src/agent/libclusterfuzz/data/parsed-traces/swift_invalid_free.json, src/agent/libclusterfuzz/data/parsed-traces/v8_check_no_sourcefile.json, src/agent/libclusterfuzz/data/parsed-traces/v8_check_trap.json, src/agent/libclusterfuzz/data/parsed-traces/v8_process_oom.json, src/agent/libclusterfuzz/data/stack-traces/rust_ignores.txt, src/agent/libclusterfuzz/data/stack-traces/swift_invalid_free.txt, src/agent/libclusterfuzz/data/stack-traces/v8_check_no_sourcefile.txt, src/agent/libclusterfuzz/data/stack-traces/v8_check_trap.txt, src/agent/libclusterfuzz/data/stack-traces/v8_process_oom.txt
Merge latest updates from libclusterfuzz  https://github.com/google/clusterfuzz/commit/c9c3623e9307dfb058f4328d9f85f7988468e75a
=> update from google/clusterfuzz 

docs/webhook_events.md, src/api-service/__app__/onefuzzlib/autoscale.py, src/api-service/__app__/onefuzzlib/workers/scalesets.py, src/api-service/__app__/scaleset/__init__.py, src/pytypes/extra/generate-docs.py, src/pytypes/onefuzztypes/enums.py, src/pytypes/onefuzztypes/events.py
This breaks out the scaleset resize event from the autoscale PR
=> add EventScalesetResizeScheduled

docs/webhook_events.md, src/pytypes/onefuzztypes/models.py, src/pytypes/onefuzztypes/requests.py
Using the built-in size validators means the documentation includes the
min/max values
=> use pydantic built-in size validators

src/api-service/__app__/agent_registration/__init__.py, src/api-service/__app__/onefuzzlib/workers/nodes.py, src/api-service/__app__/onefuzzlib/workers/scalesets.py
this is pulled up from the autoscale PR
=> set pool_id on node creation

src/api-service/__app__/queue_file_changes/__init__.py
This allows us to ignore events that are not file creation faster.
=> check change event type before container name

src/utils/add-corpus-storage-accounts/add-corpus-storage-account.py
A recent upgrade in the azure-storage libraries broke these utilities.  This fixes the utils.
=> fix the premium storage account utilities

src/api-service/__app__/onefuzzlib/notifications/main.py
=> fix format in notification

docs/command-replacements.md, src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs, src/agent/onefuzz/src/expand.rs, src/api-service/__app__/onefuzzlib/tasks/defs.py
=> expose `coverage` as an optional directory that gets synced to supervisor tasks

docs/command-replacements.md, src/agent/onefuzz/src/expand.rs
=> add support for expanding `machine_id`

src/cli/onefuzz/cli.py
=> fix rendering SecretData for jmespath filtering

src/agent/onefuzz-telemetry/src/lib.rs
=> Replace machine name in telemetry with "Redacted"

src/api-service/__app__/proxy/__init__.py
=> fix scaleset proxy reset to reset all of the proxies in the region specified

src/integration-tests/libfuzzer-rust/Makefile
=> work around issues between released version of cargo-fuzz and nightly

src/cli/requirements.txt, src/deployment/requirements.txt, src/utils/add-corpus-storage-accounts/add-corpus-storage-account.py, src/utils/add-corpus-storage-accounts/requirements.txt
=> Bump azure cli to 2.27.2

src/utils/README.md, src/utils/lint.sh
Script to lint code locally intended for running before performing `push`.
=> Quality of life improvement: local lint

src/api-service/__app__/onefuzzlib/azure/nsg.py, src/api-service/__app__/timer_proxy/__init__.py
=> Address NSG PR comments

src/api-service/__app__/instance_config/__init__.py, src/api-service/__app__/onefuzzlib/azure/nsg.py, src/api-service/__app__/onefuzzlib/azure/subnet.py, src/utils/check-pr/check-pr.py
Addressing PR comments from feature branch into main PR
=> address PR comments

src/utils/check-pr/check-pr.py, src/utils/check-pr/cleanup_ad.py, src/utils/check-pr/mypy.ini, src/utils/check-pr/requirements.txt, src/utils/lint.sh
Script to cleanup Azure AD. Script can be run by itself, and also is invoked from `check-pr.py` during cleanup to remove AppRegistration created for the test run.
=> Utility: Cleanup user owned AppRegistrations created by check-pr

src/api-service/__app__/onefuzzlib/azure/nsg.py
Change logging from `error` to `debug`
1) having error logged fails `integration-test.py`
2) Method returns `None` and caller should decide whether this is an error or not
Update log message method
Run `check-pr.py` to validate that `get_nsg` does not trigger `check-pr.py` failure when logs are inspected at the end of the run
=> Change logging from `error` to `debug` in get_nsg method

src/cli/onefuzz/templates/radamsa.py
exposing the target_timeout parameter through the radamsa template
closes #1491 
run check-pr
=> exposing the target_timeout parameter through the radamsa template

src/utils/check-pr/check-pr.py
I accidentally left 'python' as 'python3' in check-pr. This fixes the change. 
=> Fixing python call in check-pr.

src/api-service/__app__/onefuzzlib/azure/vm.py
I introduced a bug with my VM and VMSS tag PR. This PR resolves the bug by fixing the way in which tags are checked and uploaded during VM creation. 
=> Fixing Failing Proxy when no tags present

CHANGELOG.md
=> Missed a change in the changelog.

src/api-service/__app__/requirements.txt
=> bump jinja2 to 3.0.3

src/api-service/__app__/requirements.txt
=> bump azure-core to 1.21.1

docs/AADEntitites.md, src/deployment/deploy.py
I am updating the AAD Entity Doc that describes the Service Principals used by OneFuzz. 
These changes reflect the new UserAssigment role and requirement. 
Changes to AADEntities.md and deploy.py
=> Updating AAD Docs and UserAssignment Roel Description.

src/api-service/__app__/requirements.txt
=> Bump azure-identity to 1.7.1

src/agent/Cargo.lock, src/agent/debugger/src/breakpoint.rs, src/agent/srcview/src/srcview.rs, src/agent/win-util/src/pipe_handle.rs, src/agent/win-util/src/process.rs
Fixing multiple build breaks caused by clippy
=> Fix clippy-caused build break

src/api-service/__app__/requirements.txt
bumpt azure-mgmt-compute to 24.0.1
=> bumpt azure-mgmt-compute to 24.0.1

src/cli/onefuzz/backend.py
Lint for `backend.py` is [failing](https://github.com/microsoft/onefuzz/runs/5003555601?check_suite_focus=true#step:8:145), not sure if a configuration changed since that file hasn't been touched in months. Either way, this PR fixes the lint error.
=> Fix lint error

src/api-service/functional_tests/requirements.txt, src/cli/requirements.txt, src/deployment/requirements.txt, src/utils/add-corpus-storage-accounts/requirements.txt, src/utils/check-pr/requirements.txt
bump azure-cli-core and azure-cli to 2.32.0
=> bump azure-cli-core and azure-cli to 2.32.0

.github/workflows/ci.yml
Create a virtual environment to fix the cli build break
=> fix cli build

src/agent/Cargo.lock, src/proxy-manager/Cargo.lock
Update yanked block-buffer from 0.10.0 to 0.10.1
=> Update yanked block-buffer from 0.10.0 to 0.10.1

src/runtime-tools/win64/onefuzz.ps1
=> Fix typo in installation command

src/agent/Cargo.lock, src/agent/onefuzz/Cargo.toml, src/agent/onefuzz/src/blob/url.rs
=> Unescape blob name in BlobUrl

src/integration-tests/integration-test.py
increase the polling period in functional tests
=> increase the polling period in functional tests

src/agent/onefuzz-agent/src/local/tui.rs, src/agent/onefuzz-agent/src/tasks/stats/afl.rs, src/agent/stacktrace-parser/src/lib.rs
=> Fixes clippy lint

src/agent/onefuzz/src/input_tester.rs, src/ci/agent.sh
=> Clippy fix fell through the cracks

src/agent/Cargo.lock, src/agent/coverage/Cargo.toml, src/agent/libclusterfuzz/Cargo.toml, src/agent/onefuzz/Cargo.toml, src/agent/srcview/Cargo.toml, src/agent/stacktrace-parser/Cargo.toml, src/agent/storage-queue/Cargo.toml
regex v1.5.4 is vulnerable, upgrade to patched 1.5.5
Broken CI link: https://github.com/microsoft/onefuzz/runs/5466954836?check_suite_focus=true#step:7:70
=> Upgrade regex crate

src/cli/onefuzz/backend.py
Fixing missing type definition which caused the CLI fail to build. 
=> Add type definition

.github/workflows/ci.yml, src/api-service/requirements-dev.txt, src/cli/requirements-lint.txt, src/pytypes/requirements-lint.txt, src/utils/add-corpus-storage-accounts/requirements-lint.txt, src/utils/check-pr/requirements-lint.txt
pin click to 8.0.4 to fix break in black
=> pin click to fix black

docs/how-to/add-edit-workbook.md, docs/managed-identities.md, src/deployment/azuredeploy.bicep, src/deployment/azuredeploy.json, src/deployment/deploy.py
Bicep offers us:
- easier to write and understand Azure Deployment templates
- better tooling
=> port arm template to bicep

src/ApiService/ApiService/ApiService.csproj, src/ApiService/ApiService/Program.cs, src/ApiService/ApiService/QueueFileChanges.cs, src/ApiService/ApiService/onefuzzlib/Creds.cs, src/ApiService/ApiService/onefuzzlib/Storage.cs, src/ApiService/ApiService/packages.lock.json
=> Refactor queue file changes

src/ApiService/ApiService/ApiService.csproj, src/ApiService/ApiService/QueueSignalREvents.cs, src/ApiService/ApiService/packages.lock.json
Changes necessary for #1759 
1. Enable SignalR Live Trace in a dev deployment
2. Set the SignalR connection string in local.settings.json using the default name `AzureSignalRConnectionString` (same one that our current function uses.
3. Capture a normal signalr event message by logging it in the python function
4. Post that same message in the input queue to trigger the c# function
5. Verify the message shows up in live trace
=> Refactor signal events azure function

.github/workflows/ci.yml, src/ApiService/.editorconfig, src/ApiService/ApiService/EnvironmentVariables.cs, src/ApiService/ApiService/HttpClient.cs, src/ApiService/ApiService/Log.cs, src/ApiService/ApiService/OneFuzzTypes/Enums.cs, src/ApiService/ApiService/OneFuzzTypes/Events.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/OneFuzzTypes/ReturnTypes.cs, src/ApiService/ApiService/OneFuzzTypes/Webhooks.cs, src/ApiService/ApiService/Program.cs, src/ApiService/ApiService/QueueFileChanges.cs, src/ApiService/ApiService/QueueNodeHearbeat.cs, src/ApiService/ApiService/QueueSignalREvents.cs, src/ApiService/ApiService/UserCredentials.cs, src/ApiService/ApiService/onefuzzlib/Creds.cs, src/ApiService/ApiService/onefuzzlib/Events.cs, src/ApiService/ApiService/onefuzzlib/NodeOperations.cs, src/ApiService/ApiService/onefuzzlib/Queue.cs, src/ApiService/ApiService/onefuzzlib/Storage.cs, src/ApiService/ApiService/onefuzzlib/Utils.cs, src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs, src/ApiService/ApiService/onefuzzlib/orm/CaseConverter.cs, src/ApiService/ApiService/onefuzzlib/orm/CustomConverterFactory.cs, src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs, src/ApiService/ApiService/onefuzzlib/orm/Orm.cs, src/ApiService/ApiService/onefuzzlib/orm/StorageProvider.cs, src/ApiService/Tests/OrmTest.cs
Check the formatting in the build and apply default formatting to the C# solution using `dotnet format` 
Only formatting is applies **No other code changes**
=> Add formatting step to the build And apply default formatting

src/ApiService/ApiService/EnvironmentVariables.cs, src/ApiService/ApiService/Info.cs, src/ApiService/ApiService/Log.cs, src/ApiService/ApiService/QueueFileChanges.cs, src/ApiService/ApiService/QueueNodeHearbeat.cs, src/ApiService/ApiService/QueueProxyHeartbeat.cs, src/ApiService/ApiService/QueueSignalREvents.cs, src/ApiService/ApiService/UserCredentials.cs, src/ApiService/ApiService/onefuzzlib/Events.cs, src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs, src/ApiService/ApiService/onefuzzlib/Queue.cs, src/ApiService/ApiService/onefuzzlib/Storage.cs, src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs
once we start using middleware, can move log instantiation and setting of Correlation ID in there
=> switch to our logger

src/ApiService/ApiService/ApiService.csproj, src/ApiService/ApiService/onefuzzlib/Creds.cs, src/ApiService/ApiService/onefuzzlib/Storage.cs, src/ApiService/ApiService/onefuzzlib/orm/StorageProvider.cs, src/ApiService/ApiService/packages.lock.json
- bump nuget dependencies
- remove/implement "cached todo" from some methods,
=> bump dependencies to latest

src/ApiService/ApiService/Log.cs, src/ApiService/ApiService/QueueProxyHeartbeat.cs, src/ApiService/ApiService/onefuzzlib/Events.cs, src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs
=> Thread safe log

src/ApiService/ApiService/OneFuzzTypes/Enums.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/Program.cs, src/ApiService/ApiService/TimerDaily.cs, src/ApiService/ApiService/onefuzzlib/Events.cs, src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs, src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs, src/ApiService/ApiService/onefuzzlib/orm/Orm.cs
=> Migrating timer_daily

src/ApiService/ApiService/OneFuzzTypes/Events.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/onefuzzlib/Events.cs, src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs, src/ApiService/Tests/OrmTest.cs
=> fix event deserialization

src/deployment/azuredeploy.bicep
Update python function name string to manage conflict after deleting the python function app. This is needed because of the manual deployment step we have to employ upgrading from 5.2.0 to 5.3.0.
=> Update python function name string 

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/post-create-script.sh, .devcontainer/workspace.code-workspace, .gitignore
Builds on #1768. It uses the built in 'features' capability to install most of the dev tools we need. The ones that aren't available (azure functions tools and azcopy) are added manually. 
Does additional setup for each of our projects like fetching dependencies (intentionally not building since that's a time consuming process) and setting up venv/linting for python.
Adds workspaces for vscode users so that extensions can easily pick up the environment config.
Moves some processing to _after_ the container is created so that we can examine code quicker.
Click the Code button at the top right of this PR and then click the green button
=> Add dev container

src/ApiService/ApiService/OneFuzzTypes/Enums.cs, src/ApiService/ApiService/OneFuzzTypes/Events.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/TimerProxy.cs, src/ApiService/ApiService/onefuzzlib/Creds.cs, src/ApiService/ApiService/onefuzzlib/InstanceConfig.cs, src/ApiService/ApiService/onefuzzlib/Network.cs, src/ApiService/ApiService/onefuzzlib/NodeOperations.cs, src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs, src/ApiService/ApiService/onefuzzlib/Nsg.cs, src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs, src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs, src/ApiService/ApiService/onefuzzlib/Storage.cs, src/ApiService/ApiService/onefuzzlib/Subnet.cs, src/ApiService/ApiService/onefuzzlib/TaskOperations.cs, src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs, src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs, src/ApiService/ApiService/onefuzzlib/orm/Orm.cs, src/ApiService/Tests/OrmModelsTest.cs
=> [WIP] migrate timer_proxy

docs/OneFuzz-Docker-CLI.md, src/Dockerfile
Dockerize OneFuzz CLI
(Deployment scripts are not included)
=> OneFuzz CLI Docker container

src/ApiService/ApiService/Program.cs
IProxyForwardOperations was somehow removed from program.cs. Re-adding. 
=> Fixing ProxyForward Import.

src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs, src/ApiService/Tests/OrmTest.cs
=> Allow PartitonKey and RowKey on the the same property

src/ApiService/ApiService/Log.cs, src/ApiService/ApiService/OneFuzzTypes/Enums.cs, src/ApiService/ApiService/OneFuzzTypes/Events.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/ServiceConfiguration.cs, src/ApiService/ApiService/TimerRetention.cs, src/ApiService/ApiService/TimerWorkers.cs, src/ApiService/ApiService/onefuzzlib/InstanceConfig.cs, src/ApiService/ApiService/onefuzzlib/NodeOperations.cs, src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs, src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs, src/ApiService/ApiService/onefuzzlib/Scheduler.cs, src/ApiService/ApiService/onefuzzlib/ShrinkQueue.cs, src/ApiService/ApiService/onefuzzlib/TaskOperations.cs, src/ApiService/ApiService/onefuzzlib/VmssOperations.cs, src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs, src/ApiService/ApiService/onefuzzlib/orm/Queries.cs, src/ApiService/Tests/OrmModelsTest.cs, src/ApiService/Tests/QueryTest.cs
=> timer workers (part 2)

src/ApiService/ApiService/TestHooks.cs, src/ApiService/ApiService/TestHooks/ContainerTestHooks.cs, src/ApiService/ApiService/TestHooks/CredsTestHookks.cs, src/ApiService/ApiService/TestHooks/DiskOperationsTestHooks.cs, src/ApiService/ApiService/TestHooks/InstanceConfigTestHooks.cs, src/ApiService/ApiService/TestHooks/UriExtension.cs, src/ApiService/ApiService/onefuzzlib/Creds.cs, src/ApiService/ApiService/onefuzzlib/ReproOperations.cs
added some test hooks to be able to poke at the service and
found and fixed a bug
=> test hooks and a bug fix

src/api-service/__app__/onefuzzlib/tasks/config.py, src/pytypes/onefuzztypes/models.py
=> Allow jobs with no log data to be schedule

src/ApiService/ApiService/TestHooks.cs, src/ApiService/ApiService/TestHooks/LogAnalyticsTestHooks.cs, src/ApiService/ApiService/TestHooks/NotificationOperationsTestHooks.cs, src/ApiService/ApiService/TestHooks/NsgOperationsTestHooks.cs, src/ApiService/ApiService/onefuzzlib/NsgOperations.cs
=> nsg operations test hooks and some bug fixes

src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs, src/ApiService/Tests/OrmTest.cs
=> Set the table value to null when a property is null

src/ApiService/ApiService/OneFuzzTypes/Enums.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/onefuzzlib/orm/CustomConverterFactory.cs, src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs, src/ApiService/Tests/OrmTest.cs
Use the json serializer to convert enum to the DB
closes #1908
=> Use the json serializer to convert enum to the DB

.github/workflows/ci.yml
enable locked restore for NET code
=> enable locked restore on NET code

.github/workflows/ci.yml, src/ApiService/ApiService/TimerTasks.cs, src/ApiService/ApiService/onefuzzlib/TaskOperations.cs, src/ApiService/ApiService/onefuzzlib/orm/Orm.cs
Upgrading dotnet version to 6.0.300
=> Upgrading dotnet version to 6.0.300

src/ApiService/ApiService/OneFuzzTypes/ReturnTypes.cs, src/ApiService/ApiService/TestHooks/VmssTestHooks.cs, src/ApiService/ApiService/onefuzzlib/VmssOperations.cs
Use suggestion from : https://github.com/Azure/azure-sdk-for-net/issues/28491
=> scaleset vm instance scale-in protection

.devcontainer/devcontainer.json, .devcontainer/post-create-script.sh, .devcontainer/pre-commit
Automatically run any and all appropriate linters/formatters in a pre-commit step.
**This only applies to the devcontainer.**
=> Auto lint before committing in devcontainer

src/ApiService/ApiService/TimerRepro.cs, src/ApiService/Tests/Tests.csproj, src/ApiService/Tests/TimerReproTests.cs
Updates `TimerRepro` to use `IOnefuzzContext` and adds some unit tests.
=> Test timer repro

src/api-service/__app__/requirements.txt
=> Pin protobuf

.github/dependabot.yml
=> Fix yml formatting

docs/webhook_events.md, src/api-service/__app__/onefuzzlib/endpoint_authorization.py, src/api-service/tests/test_auth_check.py, src/pytypes/onefuzztypes/models.py
I realized that the when we switched this `instance_config` param name from `allow_pool_management` we didn't switch the logic. 
Changes to instance config logic. 
=> Fix Instance Config Logic.

src/agent/coverage/examples/coverage.rs, src/agent/coverage/examples/elf_sancov_tables.rs, src/agent/coverage/examples/pdb_sancov_tables.rs, src/agent/coverage/examples/src-cov.rs, src/agent/coverage/src/block.rs, src/agent/coverage/src/block/linux.rs, src/agent/coverage/src/cobertura.rs, src/agent/coverage/src/demangle.rs, src/agent/coverage/src/source.rs, src/agent/input-tester/src/crash_detector.rs, src/agent/onefuzz-task/src/local/cmd.rs, src/agent/onefuzz-task/src/tasks/config.rs, src/agent/onefuzz-task/src/tasks/fuzz/libfuzzer_fuzz.rs, src/agent/onefuzz-task/src/tasks/fuzz/supervisor.rs, src/agent/onefuzz-task/src/tasks/generic/input_poller/tests.rs, src/agent/onefuzz-task/src/tasks/report/crash_report.rs, src/agent/onefuzz-task/src/tasks/task_logger.rs, src/agent/onefuzz-telemetry/src/lib.rs, src/agent/onefuzz/examples/test-input.rs, src/agent/onefuzz/src/fs.rs, src/agent/onefuzz/src/syncdir.rs, src/agent/onefuzz/src/utils.rs, src/agent/srcview/examples/dump_srcloc.rs, src/agent/srcview/src/modoff.rs, src/agent/stacktrace-parser/src/asan.rs, src/agent/stacktrace-parser/src/lib.rs, src/agent/win-util/src/pipe_handle.rs, src/ci/agent.sh, src/ci/proxy.sh
While I'm browsing around the code clippy is shouting at me, so here's a janitorial exercise to clean up clippy lints and become a little more familiar with the codebase.
Fix all outstanding clippy lints. Fixes are almost mechanical, although I didn't automate them.
=> Make Clippy run on all targets in CI

.devcontainer/devcontainer.json, .devcontainer/post-create-script.sh
Add extensions for:
* Bicep 
* .NET test runner
* Azure Functions
Include in setup script:
* `cargo-audit` & `cargo-license` (pre-reqs for the CI script)
=> Devcontainer additions

.github/workflows/sync-issue-to azure-devops-work-item.yml
Workflow is not triggering. Adding manual trigger and adjusted spacing in the yaml.
=> Update auto-issue creation workflow

src/ApiService/ApiService/QueueNodeHearbeat.cs, src/ApiService/ApiService/QueueTaskHearbeat.cs
Enabling C# functions
- QueueNodeHeartbeat
- QueueTaskHeartbeat
#1769 
#1751
=> Enabling functions

src/ApiService/ApiService/QueueSignalREvents.cs
Enable the queue_signalr_events function in .net so we can test it
=> Enable queue_signalr_events

src/ApiService/ApiService/OneFuzzTypes/Events.cs, src/ApiService/ApiService/onefuzzlib/NodeOperations.cs
Porting the divergeant code added in #2024. 
closes #2025
=> Adding Node State to Node Heartbeat

src/ApiService/ApiService/QueueNodeHeartbeat.cs, src/ApiService/ApiService/QueueTaskHeartbeat.cs
fixes typo in QueueNodeHeartbeat and QueueTasHeartbeat
=> fix typo in function name

.devcontainer/post-create-script.sh, .github/workflows/ci.yml, src/ApiService/ApiService/ServiceConfiguration.cs, src/ApiService/ApiService/onefuzzlib/Containers.cs, src/ApiService/ApiService/onefuzzlib/Queue.cs, src/ApiService/ApiService/onefuzzlib/Storage.cs, src/ApiService/ApiService/onefuzzlib/orm/Orm.cs, src/ApiService/ApiService/onefuzzlib/orm/Queries.cs, src/ApiService/Tests/Fakes/TestContext.cs, src/ApiService/Tests/Fakes/TestEvents.cs, src/ApiService/Tests/Fakes/TestHttpRequestData.cs, src/ApiService/Tests/Fakes/TestServiceConfiguration.cs, src/ApiService/Tests/Functions/_FunctionTestBase.cs, src/ApiService/Tests/Integration/AzureStorage.cs, src/ApiService/Tests/Integration/AzuriteStorage.cs, src/ApiService/Tests/QueryTest.cs, src/ApiService/Tests/TestLogTracer.cs
Add support for function tests and the ability to run them against either real Azure Storage or the Azurite emulator.
See follow-up PR #2032 for actual usage.
=> Test infrastructure for C# Azure Function testing

src/utils/check-pr/check-pr.py
Allow setting nsg-config when running check-pr
=> Add nsg config to check-pr

src/ApiService/ApiService/Download.cs, src/ApiService/ApiService/onefuzzlib/Containers.cs, src/ApiService/ApiService/onefuzzlib/Request.cs, src/ApiService/Tests/Fakes/TestHttpRequestData.cs, src/ApiService/Tests/Functions/DownloadTests.cs
Port the `download` function to the C# service.
=> Implement the `download` Function for C#

src/ApiService/ApiService/AgentEvents.cs, src/ApiService/ApiService/Download.cs, src/ApiService/ApiService/GroupMembershipChecker.cs, src/ApiService/ApiService/Info.cs, src/ApiService/ApiService/Node.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/onefuzzlib/Creds.cs, src/ApiService/ApiService/onefuzzlib/EndpointAuthorization.cs, src/ApiService/ApiService/onefuzzlib/InstanceConfig.cs, src/ApiService/ApiService/onefuzzlib/RequestAccess.cs, src/ApiService/IntegrationTests/Fakes/TestCreds.cs, src/ApiService/Tests/OrmModelsTest.cs, src/ApiService/Tests/RequestAccessTests.cs, src/deployment/deploy.py
C# HTTP functions won’t take effect by default so it is safe to enable them in code.
=> Enable C# functions in code & fill out missing functionality

src/ApiService/ApiService/AgentCanSchedule.cs, src/ApiService/ApiService/AgentCommands.cs, src/ApiService/ApiService/AgentEvents.cs, src/ApiService/ApiService/onefuzzlib/EndpointAuthorization.cs, src/ApiService/IntegrationTests/AgentCanScheduleTests.cs, src/ApiService/IntegrationTests/AgentCommandsTests.cs, src/ApiService/IntegrationTests/AgentEventsTests.cs
The routes and auth were missing from the "agents" functions.
=> Add correct routes and auth to "agents" Functions

.devcontainer/Dockerfile, .devcontainer/post-create-script.sh
Update devcontainer to 22.04, and remove adding the MS PPA since it is already present (this currently results in warnings every time that apt is invoked).
=> Update devcontainer to 22.04

src/ApiService/ApiService/AgentRegistration.cs, src/ApiService/ApiService/OneFuzzTypes/Responses.cs, src/ApiService/ApiService/onefuzzlib/PoolOperations.cs, src/ApiService/ApiService/onefuzzlib/Queue.cs, src/ApiService/IntegrationTests/AgentRegistrationTests.cs, src/ApiService/IntegrationTests/Fakes/TestContext.cs, src/ApiService/IntegrationTests/Fakes/TestCreds.cs, src/ApiService/IntegrationTests/Fakes/TestHttpRequestData.cs, src/ApiService/IntegrationTests/Integration/AzuriteStorage.cs
Port `agent_registration` from Python to C#.
=> Refactor `agent_registration` to C#

src/agent/LibFuzzerDotnetLoader/README.md
Add README with motivation, usage, and build instructions.
=> Add `LibFuzzerDotnetLoader` docs

src/agent/input-tester/src/logging.rs
=> Fix clippy error

src/cli/onefuzz/backend.py
=> Drop support for pre 3.0.0 authentication in the cli

src/cli/onefuzz/api.py
ignore the state when a job_id is specified in tasks list
closes #2170
=> ignore the state whent a job_id is specified in tasks list

src/ApiService/ApiService/Functions/Jobs.cs, src/ApiService/ApiService/Jobs.cs, src/ApiService/ApiService/OneFuzzTypes/Enums.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/OneFuzzTypes/Requests.cs, src/ApiService/ApiService/OneFuzzTypes/Responses.cs, src/ApiService/ApiService/OneFuzzTypes/ReturnTypes.cs, src/ApiService/ApiService/UserCredentials.cs, src/ApiService/ApiService/onefuzzlib/orm/Orm.cs, src/ApiService/IntegrationTests/Fakes/TestHttpRequestData.cs, src/ApiService/IntegrationTests/JobsTests.cs
#2156 - convert the `jobs` function from Python to C#
=> Convert `jobs` function for C#

src/cli/onefuzz/api.py, src/cli/onefuzz/backend.py
Make the dotnet endpoint and functions configurable in the cli
=> Make the dotnet endpoint and functions configurable in the cli

src/ApiService/ApiService/onefuzzlib/Config.cs, src/ApiService/ApiService/onefuzzlib/Defs.cs
- Adding a missing config for the generator env
- Fix the input queue sas url
This fixes the check-pr issues when enabling TimerTasks
=> Fix TimerTasks bugs

src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs, src/ApiService/ApiService/onefuzzlib/Request.cs, src/ApiService/ApiService/onefuzzlib/Secrets.cs, src/ApiService/Tests/OrmModelsTest.cs
Porting the secret behavior to C#
- Saves the secret values in keyvault for the notification templates
- theows an Exception when attempting to serialize a secret
=> saving secrets in Keyvault

src/ApiService/ApiService/Functions/TimerProxy.cs, src/ApiService/ApiService/onefuzzlib/NsgOperations.cs
=> fix return value when associating nsg subnet

src/ApiService/ApiService/TestHooks/IpOperationsTestHooks.cs, src/ApiService/ApiService/onefuzzlib/IpOperations.cs, src/ApiService/ApiService/onefuzzlib/Network.cs, src/ApiService/ApiService/onefuzzlib/NsgOperations.cs, src/ApiService/ApiService/onefuzzlib/Subnet.cs
Related to migrating `timer_repro`, in order to keep the PR sizes manageable this is a part of the new API surface required to migrate the whole functionality.
=> Add networking related operations for C# refactor

src/ApiService/ApiService/ApiService.csproj, src/ApiService/ApiService/Functions/Proxy.cs, src/ApiService/ApiService/Functions/TimerProxy.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/OneFuzzTypes/Requests.cs, src/ApiService/ApiService/OneFuzzTypes/Responses.cs, src/ApiService/ApiService/onefuzzlib/Creds.cs, src/ApiService/ApiService/onefuzzlib/IpOperations.cs, src/ApiService/ApiService/onefuzzlib/Network.cs, src/ApiService/ApiService/onefuzzlib/ProxyForwardOperations.cs, src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs, src/ApiService/ApiService/onefuzzlib/Storage.cs, src/ApiService/ApiService/onefuzzlib/Subnet.cs, src/ApiService/ApiService/onefuzzlib/VmssOperations.cs, src/ApiService/ApiService/onefuzzlib/orm/EntityConverter.cs, src/ApiService/ApiService/packages.lock.json, src/ApiService/IntegrationTests/packages.lock.json, src/ApiService/Tests/OrmModelsTest.cs, src/ApiService/Tests/packages.lock.json
=> migrate proxy 

src/ApiService/ApiService/Functions/ReproVmss.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/OneFuzzTypes/Requests.cs, src/ApiService/ApiService/onefuzzlib/ReproOperations.cs, src/ApiService/Tests/TimerReproTests.cs
=> migrate repro_vmss

src/ApiService/ApiService/Functions/TimerDaily.cs
=> enable timer daily

src/deployment/azuredeploy.bicep
Set the clientSecret parameter as secure to prevent this from being written to logs/deployment history.
Updated: 
src/deployment/azuredeploy.bicep
=> Add secure decorator to clientSecret parameter in azuredeploy.bicep

src/ApiService/ApiService/Functions/TimerRetention.cs
=> Enable TimerRetention

src/ApiService/ApiService/Functions/Containers.cs
=> Enable `containers` function

src/ApiService/ApiService/Functions/AgentCommands.cs, src/ApiService/ApiService/OneFuzzTypes/Events.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/onefuzzlib/Events.cs, src/ApiService/ApiService/onefuzzlib/Extension.cs, src/ApiService/ApiService/onefuzzlib/ReproOperations.cs, src/ApiService/ApiService/onefuzzlib/Storage.cs, src/ApiService/ApiService/onefuzzlib/VmOperations.cs, src/ApiService/ApiService/onefuzzlib/orm/Orm.cs, src/ApiService/IntegrationTests/Fakes/TestContext.cs
Several of the `NotImplementedException`s (interpreted as TODO) should really be `NotSupportedException`.
=> Change some NotImplementedException to NotSupportedException

src/ApiService/ApiService/Functions/AgentRegistration.cs, src/ApiService/ApiService/Functions/Node.cs, src/ApiService/ApiService/Functions/Pool.cs, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/OneFuzzTypes/Requests.cs, src/ApiService/ApiService/OneFuzzTypes/Responses.cs, src/ApiService/ApiService/Program.cs, src/ApiService/ApiService/onefuzzlib/Containers.cs, src/ApiService/ApiService/onefuzzlib/Creds.cs, src/ApiService/ApiService/onefuzzlib/PoolOperations.cs, src/ApiService/ApiService/onefuzzlib/Request.cs, src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs, src/ApiService/ApiService/onefuzzlib/orm/Orm.cs, src/ApiService/IntegrationTests/AgentRegistrationTests.cs, src/ApiService/IntegrationTests/Fakes/TestContainers.cs, src/ApiService/IntegrationTests/Fakes/TestContext.cs, src/ApiService/IntegrationTests/Fakes/TestCreds.cs, src/ApiService/IntegrationTests/Fakes/TestEndpointAuthorization.cs, src/ApiService/IntegrationTests/Fakes/TestServiceConfiguration.cs, src/ApiService/IntegrationTests/JobsTests.cs, src/ApiService/IntegrationTests/NodeTests.cs, src/ApiService/IntegrationTests/PoolTests.cs, src/ApiService/Tests/JsonTests.cs
=> Convert `pool` function to C#

src/api-service/__app__/onefuzzlib/workers/scalesets.py
Updates the default together with the minimum when scaling down a scale set during shut down
The behavior of #2232 should stay the same without the error seen in #2249.
=> Auto scale default capacity must be greater than or equal to minimum

.devcontainer/post-create-script.sh, .github/workflows/ci.yml, src/agent/coverage/examples/coverage.rs, src/agent/coverage/examples/src-cov.rs, src/agent/coverage/src/report.rs, src/agent/debugger/src/dbghelp.rs, src/agent/debugger/src/module.rs, src/agent/debugger/src/stack.rs, src/agent/debugger/src/target.rs, src/agent/input-tester/src/appverifier.rs, src/agent/input-tester/src/test_result/mod.rs, src/agent/onefuzz/src/expand.rs, src/agent/win-util/src/pipe_handle.rs, src/ci/agent.sh, src/ci/proxy.sh, src/ci/rust-prereqs.sh, src/proxy-manager/src/config.rs
New release of [1.63](https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html).
=> Bump to Rust 1.63

src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/onefuzzlib/AutoScale.cs, src/ApiService/ApiService/onefuzzlib/NodeOperations.cs, src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs
fixing up some of the issues from previous PR 
merged previous PR to avoid blocking development of other parts of the code
=> timer workers fix up

src/deployment/deploylib/registration.py
The script was using the wrong date format when querying MSgraph
=> fix deploy.py

src/ApiService/ApiService/onefuzzlib/Events.cs
The code was modifying  the JsonSerializerOption which caused an exception.
=> Clone the JsonSerilizerOption instead of modifying it

CHANGELOG.md
Pull in a couple of PR's into the 5.11 release to fix an issue found in canary.
Includes PR's #2004 and #2280 
Check-pr
=> Pull in a couple of PR's into the release.

src/agent/Cargo.lock, src/agent/onefuzz-task/Cargo.toml, src/agent/onefuzz-task/src/tasks/task_logger.rs
Dependabot tried and failed to do this.
=> Update Rust azure_* crates

src/ApiService/ApiService/onefuzzlib/Events.cs
=> Include serialization options when sending event message

src/ApiService/ApiService/Functions/ReproVmss.cs
=> Fix function name

src/ApiService/ApiService.sln, src/ApiService/ApiService/Functions/Pool.cs, src/ApiService/ApiService/Functions/Scaleset.cs, src/ApiService/ApiService/HttpClient.cs, src/ApiService/ApiService/onefuzzlib/AutoScale.cs, src/ApiService/ApiService/onefuzzlib/NodeOperations.cs, src/ApiService/ApiService/onefuzzlib/NsgOperations.cs, src/ApiService/ApiService/onefuzzlib/PoolOperations.cs, src/ApiService/ApiService/onefuzzlib/Queue.cs, src/ApiService/ApiService/onefuzzlib/Request.cs, src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs, src/ApiService/ApiService/onefuzzlib/VmssOperations.cs, src/ApiService/FunctionalTests/Auth.cs, src/ApiService/FunctionalTests/FunctionalTests.csproj, src/ApiService/FunctionalTests/Scalesets.cs, src/ApiService/FunctionalTests/Usings.cs, src/ApiService/FunctionalTests/packages.lock.json
Auto Scaling works on par with Python code.
Started to add some testing code to be able to validate behavior of live C# instance
=> Port autoscaling to C#

src/ApiService/ApiService/Functions/Negotiate.cs
=> Implement `negotiate` for C#

src/agent/onefuzz/src/az_copy.rs
prints out the attempt number and failure counter when the az_copy fails
=> Added some logging to az_copy 

src/api-service/__app__/onefuzzlib/notifications/ado.py
Adding some logging to the bug filing
=> log the work item id when notifying ado

src/integration-tests/integration-test.py
Specifying initial_size when scalesets are created in the integration tests. 
=> Specifying initial size for scaleset create in integration-tests.

src/ApiService/ApiService/Program.cs, src/ApiService/ApiService/onefuzzlib/orm/Orm.cs, src/ApiService/IntegrationTests/_FunctionTestBase.cs
Attempt to create storage tables upon startup rather than once per table client.
=> Create tables on startup

src/pytypes/requirements-lint.txt
=> trying to fix python break

src/deployment/deploy.py
Setting them one-by-one is slow.
=> Update deploy to set all settings at once

src/ApiService/ApiService/onefuzzlib/InstanceConfig.cs, src/ApiService/IntegrationTests/Fakes/TestContext.cs
We read this a lot and we don’t need to, as it should change very rarely.
=> Cache InstanceConfig

src/ApiService/ApiService/Functions/AgentCanSchedule.cs, src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs, src/ApiService/ApiService/onefuzzlib/Scheduler.cs
Fixes bug that was preventing scaleset state advancement
=> Bug fixes to enable timer_workers running properly

.gitignore, docs/how-to/remote-debugging-dotnet.md, src/deployment/azuredeploy.bicep, src/deployment/bicep-templates/autoscale-settings.bicep, src/deployment/bicep-templates/function.bicep, src/deployment/bicep-templates/server-farms.bicep, src/deployment/deploy.py
=> enable running dot-net function on Windows to allow attaching remote debugger

src/ApiService/ApiService/onefuzzlib/JobOperations.cs, src/ApiService/ApiService/onefuzzlib/NodeMessageOperations.cs, src/ApiService/ApiService/onefuzzlib/NodeOperations.cs, src/ApiService/ApiService/onefuzzlib/NodeTasksOperations.cs, src/ApiService/ApiService/onefuzzlib/PoolOperations.cs, src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs, src/ApiService/ApiService/onefuzzlib/ReproOperations.cs, src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs, src/ApiService/ApiService/onefuzzlib/TaskOperations.cs, src/ApiService/ApiService/onefuzzlib/orm/Orm.cs, src/ApiService/FunctionalTests/1f-api/Helpers.cs
Don't ignore missing state transitions in `StatefulOrm` static constructor test, instead error out. 
`Scaleset` was missing the `Resize` transition.
=> Check if state transitions exist at test time

src/ApiService/ApiService/OneFuzzTypes/Enums.cs, src/ApiService/ApiService/onefuzzlib/NodeOperations.cs, src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs, src/ApiService/ApiService/onefuzzlib/VmssOperations.cs, src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs
`ScalesetOperations` was missing:
* `ReimageNodes`
* `DeleteNodes`
=> Implement not implemented bits

src/integration-tests/libfuzzer-rust/Makefile
=> Fix: use latest cargo-fuzz

src/api-service/__app__/requirements.txt, src/api-service/functional_tests/requirements.txt, src/utils/add-corpus-storage-accounts/requirements.txt, src/utils/check-pr/requirements.txt
Updating the azure-cli & azure-cli-core versions to 2.40.0 and updating azure-identity to 1.10.0 to support this.
=> Updating all azure-cli and azure-cli-core versions to 2.40

.github/workflows/validate-devcontainer.yml
When a PR is sent that changes devcontainer configuration files (under `.devcontainer`), ensure that the devcontainer can be built and run.
=> Validate changes to devcontainer files

src/ApiService/ApiService/onefuzzlib/NodeOperations.cs, src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs, src/ApiService/ApiService/onefuzzlib/ProxyForwardOperations.cs, src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs, src/ApiService/ApiService/onefuzzlib/VmssOperations.cs
Closes #2374.
This PR fixes the above issue and includes another fix (#2376) that was merged into this PR for ease-of-testing.
----
Validating via `check-pr`.
=> Two fixes for C# port

src/ApiService/ApiService/onefuzzlib/PoolOperations.cs
Delete pool queue when pool is deleted
closes #2430
=> Delete pool queue when pool is deleted

src/ApiService/ApiService/onefuzzlib/Queue.cs, src/ApiService/ApiService/onefuzzlib/ShrinkQueue.cs
Bring C# code in line with Python code: if queue does not exist, return `false`.
=> Handle 404 in Queue.RemoveFirstMessage

src/ApiService/ApiService/onefuzzlib/notifications/NotificationsBase.cs
=> EnsureNotNull doesn't support our custom formatter

src/ApiService/ApiService/OneFuzzTypes/Validated.cs, src/ApiService/Tests/ValidatedStringTests.cs
Loosen Pool name validation slightly.
=> Permit periods in Pool names

src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs
`UpdateConfigs` would never set `NeedsConfigUpdate` to `false`.
=> C#: Fix UpdateConfigs

src/ApiService/ApiService/onefuzzlib/ImageOperations.cs, src/ApiService/ApiService/onefuzzlib/LogAnalytics.cs
=> Adding missing caching from python code

.devcontainer/Dockerfile, .github/workflows/ci.yml, src/agent/coverage/src/debuginfo.rs, src/agent/debugger/src/target.rs
[Release notes.](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html)
Probably one of the more important things is:
> performance improvements of 10-20% for compiling Rust code on Windows
=> Update to Rust 1.64

src/api-service/__app__/onefuzzlib/notifications/ado.py
=> Undo tab change from previous PR

src/ApiService/ApiService/TestHooks/VmssTestHooks.cs, src/ApiService/ApiService/onefuzzlib/NodeOperations.cs, src/ApiService/ApiService/onefuzzlib/VmssOperations.cs, src/ApiService/IntegrationTests/Fakes/TestVmssOperations.cs
This PR remove the reqeuest to get the machine information before sending the scaleinProtection update.
=> Update the logic update the scaleinProtection

src/ApiService/ApiService/onefuzzlib/notifications/GithubIssues.cs
Need to set `is:issue` even when querying for issues.
=> Fix github issue query

docs/notifications/ado.md
Updating documentation per #2530.
=> Remove suggestion to reset `IterationPath` upon duplicate

src/ApiService/ApiService/onefuzzlib/VmssOperations.cs
=> Downgrade instance not found exception

src/cli/onefuzz/status/cmd.py
=> fix onefuzz status pool

src/cli/onefuzz/backend.py
=> fix path onefuzz config path

src/ApiService/ApiService/OneFuzzTypes/Enums.cs, src/ApiService/ApiService/onefuzzlib/VmssOperations.cs
Adding a more granular catching mechanism for the model error during calls of `UpdateAsync`.
=> Catching Model Exceptions During VMSS Update

src/proxy-manager/src/proxy.rs
Somehow this just started failing builds…
=> Fix clippy failure

src/agent/Cargo.lock, src/agent/onefuzz-task/Cargo.toml, src/agent/onefuzz-task/src/tasks/report/dotnet/common.rs, src/deny.toml
A very simple test, mostly to show the expected input format.
=> Add a test for parse_sos_print_exception_output

src/ApiService/ApiService/onefuzzlib/ScalesetOperations.cs, src/ApiService/ApiService/onefuzzlib/VmssOperations.cs, src/ApiService/IntegrationTests/Fakes/TestVmssOperations.cs
=> Only warn on cannot delete nodes from scaleset warning

src/ApiService/ApiService/Functions/Info.cs, src/ApiService/ApiService/OneFuzzTypes/Responses.cs
This will return a string such as ".NET 6.0.11 (win10-x86)".
=> Include dotnet version in info response

src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs
=> Fixed the database query to retrieve the proxy for a region

src/agent/coverage/src/record.rs, src/agent/coverage/src/record/windows.rs
If callbacks failed, our Windows debugger component would log a warning, then cleanly terminate the process. This could happen if (for example) we hit a dangling breakpoint. This is primarily to avoid unexpected hangs or otherwise-confusing results. Callers had no way of observing that this happened.
Instead, save the callback error to a nullable field, so callers can inspect it. In the coverage recorder, check this value, and convert it to a recording error if present.
=> Convert debugger callback errors to coverage recording errors

src/ApiService/ApiService/onefuzzlib/WebhookOperations.cs
* Fixes a bug where a webhook message is small enough for Azure table but too large for Azure queue
Extended from #2742
=> Truncate webhooks for azure queue as well

src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs, src/cli/onefuzz/api.py, src/cli/onefuzz/cli.py, src/cli/onefuzz/debug.py, src/cli/onefuzz/job_templates/handlers.py, src/cli/onefuzz/status/top_view.py, src/cli/onefuzz/templates/__init__.py, src/cli/onefuzz/templates/libfuzzer.py, src/cli/onefuzz/templates/regression.py, src/cli/tests/test_template_helper.py, src/deployment/deploy.py, src/deployment/deploylib/configuration.py, src/deployment/deploylib/registration.py, src/pytypes/onefuzztypes/events.py, src/utils/check-pr/check-pr.py, src/utils/check-pr/cleanup_ad.py, src/utils/check-pr/github_client.py
The query was supposed to be on the partition
=> Fix query to get the existing proxy

contrib/deploy-onefuzz-via-azure-devops/deploy-onefuzz.yml, contrib/onefuzz-job-azure-devops-pipeline/azure-pipelines.yml, contrib/onefuzz-job-github-actions/github-pipeline.yml
Update `./contrib` examples such that they use the correct `--client_id`, `--client_secret`, etc. flag updates. 
=> Updating  Files w/ New  Flags

src/agent/Cargo.lock, src/agent/onefuzz-task/Cargo.toml
Dependabot tried to do this here but these must all be bumped at the same time: #2868
=> Bump azure_* libs

src/integration-tests/integration-test.py
=> Fix .NET integration tests

docs/unmanaged-nodes.md
Update miss-spelled document name.
=> Update the unmanaged-node document name.

docs/command-replacements.md, src/agent/onefuzz-agent/src/setup.rs, src/agent/onefuzz-agent/src/worker.rs, src/cli/onefuzz/templates/libfuzzer.py, src/integration-tests/integration-test.py
=> fix extra container intilization

contrib/onefuzz-job-github-actions/github-pipeline.yml, src/cli/examples/azure-functions-example/info/__init__.py, src/cli/onefuzz/api.py
Reverting `override_client_id` to `client_id`
=> Reverting `client_id`  Name Change

contrib/deploy-onefuzz-via-azure-devops/deploy-onefuzz.yml, contrib/onefuzz-job-azure-devops-pipeline/azure-pipelines.yml
=> Revert YML Param Changes.

docs/unmanaged-nodes.md, src/agent/Cargo.lock, src/agent/onefuzz-agent/Cargo.toml, src/agent/onefuzz-agent/src/scheduler.rs, src/agent/onefuzz-agent/src/worker.rs, src/agent/onefuzz-agent/src/worker/double.rs, src/agent/onefuzz-agent/src/worker/tests.rs, src/agent/onefuzz-task/Cargo.toml, src/agent/onefuzz-task/src/local/common.rs, src/agent/onefuzz-task/src/managed/cmd.rs, src/agent/onefuzz-task/src/tasks/config.rs, src/agent/onefuzz-task/src/tasks/fuzz/generator.rs, src/agent/onefuzz-task/src/tasks/fuzz/supervisor.rs, src/agent/onefuzz/src/ipc.rs, src/agent/onefuzz/src/lib.rs, src/ci/agent.sh, src/ci/check-dependencies.sh, src/ci/proxy.sh, src/deny.toml
Reverts microsoft/onefuzz#2886
=> Revert "Create 2 way IPC connection between agent and task"

.devcontainer/Dockerfile, .github/workflows/ci.yml, src/ci/check-dependencies.sh, src/proxy-manager/Cargo.lock
No code changes required, this time.
=> Bump to Rust 1.68

src/cli/examples/azure-functions-example/requirements.txt, src/proxy-manager/Cargo.lock, src/proxy-manager/Cargo.toml
=> Fix WS-2023-0045  and CVE-2023-0286

src/ApiService/ApiService/ApiService.csproj, src/ApiService/ApiService/FeatureFlags.cs, src/ApiService/ApiService/Program.cs, src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs, src/ApiService/ApiService/onefuzzlib/notifications/NotificationsBase.cs, src/ApiService/ApiService/packages.lock.json, src/ApiService/IntegrationTests/packages.lock.json, src/ApiService/Tests/packages.lock.json, src/deployment/bicep-templates/feature-flags.bicep
Fixes an issue where 2 feature flags were using the same id.
* Update and bump the version of the app configuration nuget package
* Use new IDs for both scriban related feature flags
Try to create a new notification config.
Check logs to see what feature state the service used.
=> Update feature configuration package

.github/workflows/ci.yml
Includes Rust errors in code review, for example:
=> Rust problem matchers

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
Add `src/ApiService` and `src/proxy-manager`.
=> Update CodeQL config

src/ApiService/ApiService/Functions/Notifications.cs
=> Fix Notification delete

src/deny.toml
=> Remove old RUSTSEC suppression

src/ApiService/ApiService/ApiService.csproj, src/ApiService/ApiService/packages.lock.json, src/ApiService/IntegrationTests/packages.lock.json, src/ApiService/Tests/packages.lock.json, src/agent/Cargo.lock, src/proxy-manager/Cargo.lock
Bumping packages mentioned in latest Component Governance report: GHSA-f8vr-r385-rh5r
=> Update packages from CG report

.github/workflows/ci.yml, src/agent/Cargo.lock, src/agent/coverage/src/record/linux.rs, src/agent/coverage/src/record/linux/debugger.rs, src/ci/agent.sh, src/ci/check-dependencies.sh
Just enough changes to permit the build & unit tests to pass. No validation of the service in deployment has been performed. Coverage has not been validated manually (there are few tests that currently "cover" this).
=> Basic Linux ARM64 build

src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/Tests/ReportTests.cs
=> Collect additional report field in an ExtensionData property

.devcontainer/Dockerfile
This is the github commandline tool
=> Add `gh` to devcontainer

src/cli/onefuzz/templates/libfuzzer.py
=> fix logic to set check_fuzzer_help

src/cli/requirements.txt
Updates Python requests version from 2.27.1 to 2.31.0 to fix CVE-2023-32681
=> Update requests version in CLI requirements to fix CVE

src/agent/Cargo.lock, src/agent/onefuzz-agent/Cargo.toml, src/agent/onefuzz-agent/src/commands.rs
The `users` crate hasn't seen any action since 2020-10-08. The developer seems [MIA] since.
=> remove dependency on the users crate

src/agent/Cargo.lock, src/agent/onefuzz-task/Cargo.toml, src/agent/onefuzz-task/src/local/common.rs, src/agent/onefuzz-task/src/local/tui.rs
=> Switch tui to ratatui

src/ApiService/ApiService/ApiService.csproj, src/ApiService/ApiService/packages.lock.json, src/ApiService/FunctionalTests/FunctionalTests.csproj, src/ApiService/FunctionalTests/packages.lock.json, src/ApiService/IntegrationTests/IntegrationTests.csproj, src/ApiService/IntegrationTests/packages.lock.json, src/ApiService/Tests/Tests.csproj, src/ApiService/Tests/packages.lock.json
Updating System.Security.Cryptography.Pkcs ver to 7.0.2
* Passes integration tests
=> updated System.Security.Cryptography.Pkcs ver to 7.0.2

src/cli/onefuzz/debug.py
Adds the ability to send a specific report to test a notification template
`onefuzz debug notification test_template <template> [--task_id <task_id> [--report <report>]`
=> Allow report to be sent when debugging

src/agent/coverage/examples/record.rs, src/agent/coverage/src/source.rs, src/agent/onefuzz-task/src/tasks/coverage/generic.rs
=> Apply allowlist to source conversion

src/ApiService/ApiService/onefuzzlib/Queue.cs
=> Downgrade error to warning when retrying because of message too large

src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs, src/ApiService/ApiService/onefuzzlib/notifications/GithubIssues.cs, src/ApiService/ApiService/onefuzzlib/notifications/JinjaTemplateAdapter.cs, src/ApiService/ApiService/onefuzzlib/notifications/NotificationsBase.cs
Closes #3235 
* Makes template rendering synchronous
* Fix a bug where we call AddRange on the `notificationInfo` array
* Some small Roslyn suggestions
=> Make rendering synchronou

src/ApiService/FunctionalTests/TestContainer.cs
After #3229 the test needs to be updated.
=> Update container functional test

src/agent/Cargo.lock, src/proxy-manager/Cargo.lock
Might help with build speed a little.
=> Remove old windows crates

codecov.yaml, codecov.yml
Don't count examples or test code towards coverage.
=> Basic codecov config

docs/webhook_events.md, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/onefuzzlib/Defs.cs, src/ApiService/ApiService/onefuzzlib/Scheduler.cs, src/ApiService/ApiService/onefuzzlib/notifications/JinjaTemplateAdapter.cs, src/agent/onefuzz-agent/src/agent/tests.rs, src/agent/onefuzz-agent/src/debug.rs, src/agent/onefuzz-agent/src/work.rs, src/agent/onefuzz-agent/src/worker.rs, src/agent/onefuzz-agent/src/worker/tests.rs, src/agent/onefuzz-task/src/local/generic_analysis.rs, src/agent/onefuzz-task/src/tasks/analysis/generic.rs, src/cli/onefuzz/api.py, src/cli/onefuzz/templates/libfuzzer.py, src/pytypes/onefuzztypes/models.py
introduce a new `target_env` parameter to specify the environment variable of a task
closes #1623
=> allow tasks environment variables to be set

src/agent/coverage/README.md
Customer report that `'@@'` should be `"@@"`
=> Update coverage docs

src/ApiService/ApiService/FeatureFlags.cs, src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs, src/deployment/bicep-templates/feature-flags.bicep
=> Feature flag work item creation

src/ApiService/ApiService/onefuzzlib/AutoScale.cs, src/deployment/azuredeploy.bicep, src/deployment/bicep-templates/autoscale-settings.bicep
The retention policy setting is [deprecated](https://github.com/hashicorp/terraform-provider-azurerm/issues/23051). This is causing failures in the scaleset deployment.  
closes #3451
=> Remove the retention policy setting

.github/workflows/ci.yml
=> install LLVm 16 before running dotnet-fuzzing-tools.ps1

.github/workflows/ci.yml, src/agent/onefuzz-agent/src/work.rs, src/ci/dotnet-fuzzing-tools.ps1
The change introduced in #3432 will update the path of the setup folder which could change the string used to deduplicates bugs in the ado templates. 
This change reverts the path of the setup folder to the original path.
=> Revert the location of the setupFolder

src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs
Address the post-merge comments made on #3467
Essentially, I was passing a dictionary to a method that already had access to it from one of its member variables.
This PR changes the code to just use the member variable instead.
=> Remove unnecessary method argument

src/agent/Cargo.lock, src/agent/onefuzz-agent/Cargo.toml, src/agent/onefuzz-task/Cargo.toml
Dependabot is trying to do this but it all needs to be done at once.
=> Bump azure_* crates

src/ci/build_cli.ps1, src/ci/set-versions.sh, src/ci/unset-versions.sh, src/cli/requirements.txt
=> Fix sed checks for CLI versioning

src/agent/coverage/src/record/windows.rs
Closes #3492
Do not bail when we encounter a breakpoint we haven't set ourselves.
=> Improve handling of unexpected breakpoints

src/agent/Cargo.lock, src/agent/onefuzz-agent/Cargo.toml, src/agent/onefuzz-task/Cargo.toml
Dependabot once again trying to do this and failing.
=> Update azure_* crates

README.md
Update README with a target archive date for the repo.
=> Update archive notice.

src/agent/onefuzz-task/src/local/template.rs, src/agent/onefuzz-task/tests/template_integration.rs
Users can write a directory in the yaml template and we will create the directories if they don't exist.
* When using the local template, create the listed directories if they don't already exist
* Update the integration test to use this functionality
* Updated integration test
=> Create directories if they don't exist in the template

src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/OneFuzzTypes/Responses.cs, src/pytypes/onefuzztypes/models.py
Add a start time to the job and task
closes #3357
=> Add a start time to the job and task

src/agent/coverage/src/allowlist.rs, src/agent/coverage/src/allowlist/tests.rs, src/agent/onefuzz-task/src/tasks/coverage/generic.rs
=> Fix default windows interceptor list

src/agent/onefuzz/src/libfuzzer.rs
=> log the command line as info

src/cli/onefuzz/api.py, src/cli/onefuzz/debug.py, src/integration-tests/integration-test.py
Re-adding `repro` and `debug` VM CLI commands
=> Revert PR #3494 "Disable `repro` and `debug` VM CLI commands. "

src/integration-tests/integration-test.py, src/proxy-manager/Cargo.lock
Didn't clear all of repro steps. 
=> Removing additional repro test step

docs/webhook_events.md, src/ApiService/ApiService/OneFuzzTypes/Model.cs, src/ApiService/ApiService/onefuzzlib/Config.cs, src/ApiService/ApiService/onefuzzlib/notifications/JinjaTemplateAdapter.cs, src/agent/onefuzz-task/src/managed/cmd.rs, src/cli/onefuzz/api.py, src/cli/onefuzz/templates/afl.py, src/cli/onefuzz/templates/libfuzzer.py, src/cli/onefuzz/templates/ossfuzz.py, src/cli/onefuzz/templates/radamsa.py, src/cli/onefuzz/templates/regression.py, src/pytypes/onefuzztypes/models.py
Makes `min_available_memory_mb` configurable per task from the CLI and service.
=> Make `min_available_memory_mb` configurable

src/agent/coverage/fuzz/Cargo.lock, src/agent/coverage/fuzz/Cargo.toml, src/agent/coverage/fuzz/fuzz_targets/fuzz_target_allowlist_parse.rs
Added a rust libfuzzer target to fuzz the allow list parse function in the coverage project. 
https://github.com/microsoft/onefuzz/blob/679309a87a27251ffabf698fdd9eae2c643467b6/src/agent/coverage/src/allowlist.rs#L25C47-L25C47
=> allow list fuzzer 

src/deployment/azuredeploy.bicep, src/deployment/bicep-templates/function-settings.bicep, src/deployment/bicep-templates/function.bicep, src/deployment/bicep-templates/signalR.bicep, src/deployment/bicep-templates/storageAccounts.bicep
refactor bicep templates to keep secrets secret
=> do not expose secrets as part of deployment output during azure deployment
